import type { CodeRefKind, LoomModel, RequirementIR, TraceabilityIR } from "../ir/types/loom-ir.js";
import { type LinesPart, lines } from "../util/code-builder.js";

// ---------------------------------------------------------------------------
// Traceability documentation — derived views over the
// requirement / solution / testCase artifacts and the precomputed
// `TraceabilityIR` index (`src/ir/enrich/enrichments.ts`).  Same status as
// the Mermaid diagrams and wire-spec: pure derivations, not contracts.
//
// Emitted under `<outdir>/.loom/` once per build (the artifacts are
// model-global — requirements may reference code across systems):
//
//   traceability.md          human-readable spec: requirement tree +
//                            its solution, tests, and covered code.
//   coverage.md              code / requirement / solution coverage
//                            with roll-up percentages.
//   gaps.md                  requirements without solution/tests,
//                            entitled-but-untested code, low-coverage
//                            solutions.
//   traceability-matrix.md   requirements × testCases grid.
//   traceability.mmd         Mermaid graph: Requirement -> Solution ->
//                            Code and TestCase -> Code.
//   traceability.json        machine-readable index for CI gates.
//
// All built procedurally via `lines(...)` — no template engine.
// ---------------------------------------------------------------------------

/** True iff the model declares any traceability artifact. */
export function hasTraceability(loom: LoomModel): boolean {
  return loom.requirements.length > 0 || loom.solutions.length > 0 || loom.testCases.length > 0;
}

/** path (relative to the output root) → file content. */
export function renderTraceabilityArtifacts(loom: LoomModel): Map<string, string> {
  const out = new Map<string, string>();
  if (!hasTraceability(loom)) return out;
  out.set(".loom/traceability.md", renderTraceabilityDoc(loom));
  out.set(".loom/coverage.md", renderCoverageReport(loom));
  out.set(".loom/gaps.md", renderGapsReport(loom));
  out.set(".loom/traceability-matrix.md", renderMatrix(loom));
  out.set(".loom/traceability.mmd", renderTraceabilityDiagram(loom));
  out.set(".loom/traceability.json", renderTraceabilityJson(loom));
  return out;
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function trace(loom: LoomModel): TraceabilityIR {
  if (!loom.traceability) {
    throw new Error(
      "internal: traceability index not populated — render must consume " +
        "an IR produced by enrichLoomModel(lowerModel(model)).",
    );
  }
  return loom.traceability;
}

function pct(covered: number, total: number): string {
  if (total === 0) return "n/a";
  return `${Math.round((covered / total) * 100)}%`;
}

/** Roots of the requirement forest (no parent), in source order. */
function rootRequirements(loom: LoomModel): RequirementIR[] {
  return loom.requirements.filter((r) => !r.parentId);
}

function requirementById(loom: LoomModel): Map<string, RequirementIR> {
  return new Map(loom.requirements.map((r) => [r.id, r]));
}

function check(b: boolean): string {
  return b ? "✅" : "❌";
}

// ---------------------------------------------------------------------------
// traceability.md — the human-readable spec
// ---------------------------------------------------------------------------

function renderTraceabilityDoc(loom: LoomModel): string {
  const t = trace(loom);
  const byId = requirementById(loom);

  const renderReq = (id: string, depth: number): string[] => {
    const r = byId.get(id);
    if (!r) return [];
    const indent = "  ".repeat(depth);
    const status = r.status ? ` _(${r.status})_` : "";
    const head = `${indent}- **${r.id}** [${r.type}] ${r.title}${status}`;
    const detail: string[] = [];
    const sol = t.solutionByRequirement[r.id];
    if (sol) detail.push(`${indent}  - solution: \`${sol}\``);
    const tests = t.testsByRequirement[r.id] ?? [];
    detail.push(
      `${indent}  - tests: ${tests.length ? tests.map((x) => `\`${x}\``).join(", ") : "_none_"}`,
    );
    const kids = (t.childrenOf[r.id] ?? []).flatMap((c) => renderReq(c, depth + 1));
    return [head, ...detail, ...kids];
  };

  return (
    lines(
      "# Traceability",
      "",
      "_Generated by Loom. Derived view — do not edit._",
      "",
      "## Requirements",
      "",
      rootRequirements(loom).flatMap((r) => renderReq(r.id, 0)),
      "",
      "## Solutions",
      "",
      loom.solutions.length === 0
        ? "_No solutions declared._"
        : loom.solutions.map((s) =>
            lines(
              `### ${s.id} — ${s.title || "(untitled)"}`,
              `for: \`${s.forRequirement}\``,
              "",
              "Entitles:",
              s.entitles.length === 0
                ? "- _nothing_"
                : s.entitles.map((c) => `- \`${c.qualifiedName}\` (${c.kind})`),
              "",
            ),
          ),
      "## Test cases",
      "",
      loom.testCases.length === 0
        ? "_No test cases declared._"
        : loom.testCases.map((tc) =>
            lines(
              `### ${tc.id} — ${tc.title || "(untitled)"}`,
              `verifies: \`${tc.verifies}\``,
              `executable tests: ${
                (t.execTestsByTestCase[tc.id] ?? []).map((x) => `"${x}"`).join(", ") || "_none_"
              }`,
              "",
              "Covers:",
              tc.covers.length === 0
                ? "- _nothing_"
                : tc.covers.map((c) => `- \`${c.qualifiedName}\` (${c.kind})`),
              "",
            ),
          ),
    ) + "\n"
  );
}

// ---------------------------------------------------------------------------
// coverage.md
// ---------------------------------------------------------------------------

function renderCoverageReport(loom: LoomModel): string {
  const t = trace(loom);

  // Code coverage.
  const codeElems = Object.keys(t.codeElements).sort();
  const coveredCode = codeElems.filter((q) => (t.testsByCodeElement[q] ?? []).length > 0);
  const codeRows = codeElems.map((q) => {
    const tests = t.testsByCodeElement[q] ?? [];
    return `| \`${q}\` | ${t.codeElements[q]} | ${tests.length} | ${check(tests.length > 0)} |`;
  });

  // Requirement coverage.
  const reqRows = loom.requirements.map((r) => {
    const tests = t.testsByRequirement[r.id] ?? [];
    return `| \`${r.id}\` | ${r.type} | ${tests.length} | ${check(tests.length > 0)} |`;
  });
  const coveredReqs = loom.requirements.filter(
    (r) => (t.testsByRequirement[r.id] ?? []).length > 0,
  );

  // Solution coverage — fraction of each solution's entitled code that
  // is covered by at least one test case.
  const solRows = loom.solutions.map((s) => {
    const total = s.entitles.length;
    const covered = s.entitles.filter(
      (c) => (t.testsByCodeElement[c.qualifiedName] ?? []).length > 0,
    ).length;
    return `| \`${s.id}\` | \`${s.forRequirement}\` | ${covered}/${total} | ${pct(covered, total)} |`;
  });

  return (
    lines(
      "# Coverage",
      "",
      "_Generated by Loom. Derived view — do not edit._",
      "",
      "## Code coverage",
      "",
      `Overall: **${pct(coveredCode.length, codeElems.length)}** (${coveredCode.length}/${codeElems.length} referenced code elements covered by a test case).`,
      "",
      "| Code element | Kind | Tests | Covered |",
      "| --- | --- | --: | :-: |",
      codeRows.length ? codeRows : "| _none_ |  |  |  |",
      "",
      "## Requirement coverage",
      "",
      `Overall: **${pct(coveredReqs.length, loom.requirements.length)}** (${coveredReqs.length}/${loom.requirements.length} requirements have a verifying test, counting tests on child requirements).`,
      "",
      "| Requirement | Type | Tests | Covered |",
      "| --- | --- | --: | :-: |",
      reqRows.length ? reqRows : "| _none_ |  |  |  |",
      "",
      "## Solution coverage",
      "",
      "| Solution | For | Covered entitlements | % |",
      "| --- | --- | --: | --: |",
      solRows.length ? solRows : "| _none_ |  |  |  |",
    ) + "\n"
  );
}

// ---------------------------------------------------------------------------
// gaps.md
// ---------------------------------------------------------------------------

function renderGapsReport(loom: LoomModel): string {
  const t = trace(loom);

  const reqsNoSolution = loom.requirements.filter(
    (r) => r.type === "UserStory" && t.solutionByRequirement[r.id] === null,
  );
  const reqsNoTests = loom.requirements.filter(
    (r) => (t.testsByRequirement[r.id] ?? []).length === 0,
  );
  const codeNoTests = Object.keys(t.codeElements)
    .filter((q) => (t.testsByCodeElement[q] ?? []).length === 0)
    .sort();
  const testCasesNoExec = loom.testCases.filter(
    (tc) => (t.execTestsByTestCase[tc.id] ?? []).length === 0,
  );

  const section = (title: string, items: string[]): LinesPart => [
    `## ${title}`,
    "",
    items.length ? items.map((i) => `- ${i}`) : ["_none_"],
    "",
  ];

  return (
    lines(
      "# Traceability gaps",
      "",
      "_Generated by Loom. Derived view — do not edit._",
      "",
      section(
        "User stories without a solution",
        reqsNoSolution.map((r) => `\`${r.id}\` — ${r.title}`),
      ),
      section(
        "Requirements without tests",
        reqsNoTests.map((r) => `\`${r.id}\` [${r.type}] — ${r.title}`),
      ),
      section(
        "Referenced code without a covering test",
        codeNoTests.map((q) => `\`${q}\` (${t.codeElements[q]})`),
      ),
      section(
        "Test cases without an executable test",
        testCasesNoExec.map((tc) => `\`${tc.id}\` — ${tc.title}`),
      ),
    ) + "\n"
  );
}

// ---------------------------------------------------------------------------
// traceability-matrix.md
// ---------------------------------------------------------------------------

function renderMatrix(loom: LoomModel): string {
  const t = trace(loom);
  const tcIds = loom.testCases.map((tc) => tc.id);
  if (tcIds.length === 0) {
    return lines("# Traceability matrix", "", "_No test cases declared._") + "\n";
  }
  const header = `| | ${tcIds.map((id) => `${id}`).join(" | ")} |`;
  const sep = `| --- | ${tcIds.map(() => ":-:").join(" | ")} |`;

  const reqRows = loom.requirements.map((r) => {
    const tests = new Set(t.testsByRequirement[r.id] ?? []);
    return `| \`${r.id}\` | ${tcIds.map((id) => (tests.has(id) ? "✓" : "·")).join(" | ")} |`;
  });
  const codeRows = Object.keys(t.codeElements)
    .sort()
    .map((q) => {
      const tests = new Set(t.testsByCodeElement[q] ?? []);
      return `| \`${q}\` | ${tcIds.map((id) => (tests.has(id) ? "✓" : "·")).join(" | ")} |`;
    });

  return (
    lines(
      "# Traceability matrix",
      "",
      "_Generated by Loom. Derived view — do not edit._",
      "",
      "## Requirements × test cases",
      "",
      header,
      sep,
      reqRows,
      "",
      "## Code elements × test cases",
      "",
      header,
      sep,
      codeRows,
    ) + "\n"
  );
}

// ---------------------------------------------------------------------------
// traceability.mmd — Mermaid graph
// ---------------------------------------------------------------------------

const KIND_SHAPE: Record<CodeRefKind, [string, string]> = {
  subdomain: ["[[", "]]"],
  context: ["[[", "]]"],
  aggregate: ["[", "]"],
  operation: ["([", "])"],
  valueobject: ["[", "]"],
  event: [">", "]"],
  repository: ["[(", ")]"],
  workflow: ["{{", "}}"],
  deployable: ["[/", "/]"],
  api: ["{{", "}}"],
};

let nodeSeq = 0;
function nodeId(prefix: string, key: string, cache: Map<string, string>): string {
  const existing = cache.get(key);
  if (existing) return existing;
  const id = `${prefix}${nodeSeq++}`;
  cache.set(key, id);
  return id;
}

function esc(s: string): string {
  return s.replace(/"/g, "'");
}

function renderTraceabilityDiagram(loom: LoomModel): string {
  nodeSeq = 0;
  const codeNodes = new Map<string, string>();
  const emitted = new Set<string>();
  const body: string[] = [];

  const codeNode = (qn: string, kind: CodeRefKind): string => {
    const id = nodeId("c", qn, codeNodes);
    if (!emitted.has(id)) {
      emitted.add(id);
      const [l, r] = KIND_SHAPE[kind];
      body.push(`  ${id}${l}"${esc(qn)}"${r}`);
    }
    return id;
  };

  const reqNodes = new Map<string, string>();
  for (const r of loom.requirements) {
    const id = nodeId("r", r.id, reqNodes);
    body.push(`  ${id}["${esc(r.id)}: ${esc(r.title)}"]`);
  }
  for (const r of loom.requirements) {
    if (r.parentId && reqNodes.has(r.parentId)) {
      body.push(`  ${reqNodes.get(r.parentId)} --> ${reqNodes.get(r.id)}`);
    }
  }

  for (const s of loom.solutions) {
    const sid = `s${nodeSeq++}`;
    body.push(`  ${sid}{{"${esc(s.id)}"}}`);
    if (reqNodes.has(s.forRequirement))
      body.push(`  ${reqNodes.get(s.forRequirement)} -->|for| ${sid}`);
    for (const c of s.entitles)
      body.push(`  ${sid} -->|entitles| ${codeNode(c.qualifiedName, c.kind)}`);
  }

  for (const tc of loom.testCases) {
    const tid = `t${nodeSeq++}`;
    body.push(`  ${tid}["${esc(tc.id)}"]`);
    if (reqNodes.has(tc.verifies)) body.push(`  ${tid} -->|verifies| ${reqNodes.get(tc.verifies)}`);
    for (const c of tc.covers)
      body.push(`  ${tid} -.->|covers| ${codeNode(c.qualifiedName, c.kind)}`);
  }

  return lines("flowchart LR", body) + "\n";
}

// ---------------------------------------------------------------------------
// traceability.json — machine-readable index for CI gates
// ---------------------------------------------------------------------------

function renderTraceabilityJson(loom: LoomModel): string {
  const t = trace(loom);
  const codeElems = Object.keys(t.codeElements);
  const coveredCode = codeElems.filter((q) => (t.testsByCodeElement[q] ?? []).length > 0);
  const coveredReqs = loom.requirements.filter(
    (r) => (t.testsByRequirement[r.id] ?? []).length > 0,
  );

  return (
    JSON.stringify(
      {
        version: 1,
        requirements: loom.requirements,
        solutions: loom.solutions,
        testCases: loom.testCases,
        index: {
          childrenOf: t.childrenOf,
          testsByRequirement: t.testsByRequirement,
          solutionByRequirement: t.solutionByRequirement,
          codeElements: t.codeElements,
          testsByCodeElement: t.testsByCodeElement,
          execTestsByTestCase: t.execTestsByTestCase,
          // Provenance for the verification join (suite + kind per
          // executable test) — consumed by `ddd verify` and the
          // playground's live Definition-of-Done overlay.
          execTests: t.execTests,
        },
        summary: {
          codeCoverage: { covered: coveredCode.length, total: codeElems.length },
          requirementCoverage: { covered: coveredReqs.length, total: loom.requirements.length },
        },
      },
      null,
      2,
    ) + "\n"
  );
}
