import type { ExprIR, MessageIR, PathIR, ProvSite, StmtIR } from "../../ir/types/loom-ir.js";
import { walkStmtExprsDeep } from "../../ir/util/walk.js";
import { escapeCsharpIdent, upperFirst } from "../../util/naming.js";
import { collectLeaves, provTempNames, wrapProvCapture } from "../_stmt/leaves.js";
import { renderStmtChunksWith, renderStmtsWith, type StmtTarget } from "../_stmt/target.js";
import type { CsRenderContext } from "./render-expr.js";
import { addCsExprUsing, renderCsExpr } from "./render-expr.js";

// ---------------------------------------------------------------------------
// Statement LEAF TABLE for the .NET backend.  The 11-kind `StmtIR` dispatch,
// the chunk/join pair and the `variant-match` guard live once in
// `../_stmt/target.ts`; this file supplies only the per-kind spelling
// (audit finding C1).
// ---------------------------------------------------------------------------

const INDENT = "        ";
const DEFAULT_CTX: CsRenderContext = { thisName: "this" };

/** Compile-time --trace context — mirrors render-stmt.ts on the Hono
 *  side.  The catalog's `value_computed` and `precondition_evaluated`
 *  lines need the enclosing aggregate + op names, neither of which are
 *  on the per-statement IR.  Threaded through the renderer rather than
 *  re-discovered at each emission site.  When `emitTrace` is false the
 *  renderer behaves byte-identically to its pre-trace output. */
export interface TraceCtx {
  emitTrace: boolean;
  aggregate: string;
  op: string;
  /** True when rendering a body on an event-sourced (`persistedAs: eventLog`)
   *  aggregate.  An `emit` then both records the event AND folds it via
   *  `_Apply(ev)` so the in-memory aggregate stays consistent for the
   *  command's response — the state transition the appliers own.  Off ⇒
   *  `emit` is byte-identical to the legacy notification-event add. */
  eventSourced?: boolean;
}

const NO_TRACE: TraceCtx = { emitTrace: false, aggregate: "", op: "" };

export function renderCsStatements(
  stmts: StmtIR[],
  ctx: CsRenderContext = DEFAULT_CTX,
  traceCtx: TraceCtx = NO_TRACE,
): string {
  return renderStmtsWith(stmts, csStmtTarget(ctx, traceCtx));
}

/** Same rendering as `renderCsStatements`, but one (possibly multi-line)
 *  string per statement instead of the pre-joined whole — exactly the map
 *  `renderCsStatements` joins with `"\n"` today, so `chunks.join("\n")` is
 *  byte-identical to it.  Lets a caller that owns the final file content
 *  (the .NET entity emitter) recover each statement's own line span inside
 *  an operation body for `SourceMapRecorder.fragment` — see
 *  `statementSubRegions` (re-exported below). */
export function renderCsStatementChunks(
  stmts: StmtIR[],
  ctx: CsRenderContext = DEFAULT_CTX,
  traceCtx: TraceCtx = NO_TRACE,
): string[] {
  return renderStmtChunksWith(stmts, csStmtTarget(ctx, traceCtx));
}

// `statementSubRegions` lives in src/generator/_trace/sourcemap.ts —
// origin-generic (works for any statement IR carrying `origin?`), so every
// backend's chunk-producing renderer shares the one cursor walk.  Re-exported
// here so call sites in this backend's emitters can import it alongside
// `renderCsStatementChunks` from a single module.
export { statementSubRegions } from "../_trace/sourcemap.js";

/** Namespaces a statement body reaches into beyond the SDK's implicit
 *  usings — the union of `collectCsExprUsings` over every expression
 *  these statements render through `renderCsExpr`.  Mirrors the
 *  per-kind expression set of the leaf table below. */
export function collectCsStmtUsings(
  stmts: StmtIR[],
  into: Set<string>,
  /** Forwarded to `collectCsExprUsings` so a domain-service call in any
   *  statement body adds `${ns}.Domain.Services`.  Required for the same
   *  reason it is required there — an omitted `ns` is silently a missing
   *  `using`, i.e. C# that does not compile. */
  ns: string,
): Set<string> {
  // Rides `walkStmtExprsDeep` (M-T6.50 class, wave-2 packet 2.3): the switch
  // it replaced had no `variant-match` arm, so a `using`-triggering
  // expression nested in an arm/else body was silently dropped.
  for (const s of stmts) {
    walkStmtExprsDeep(s, (e) => addCsExprUsing(e, into, ns));
  }
  return into;
}

/** The .NET leaf table.  Built per call so the arms close over the C#
 *  render context and the `--trace` context instead of threading them
 *  through the shared spine. */
function csStmtTarget(ctx: CsRenderContext, traceCtx: TraceCtx): StmtTarget {
  return {
    backendName: ".NET",
    // PRESERVED INCONSISTENCY (audit C1): .NET numbers statement temps by
    // POSITION in the body, python numbers them per-kind.  Normalising the two
    // moves generated bytes, so it stays a separate, deliberately-gated change.
    indexing: "positional",

    precondition: (s, ix) => precondition(s.expr, s.source, s.message, ix.pre, ctx, traceCtx),

    requires: (s) =>
      // Authorization gate — surfaces as 403 (handled by
      // DomainExceptionFilter mapping ForbiddenException → 403).
      `${INDENT}if (!(${renderCsExpr(s.expr, ctx)})) throw new ForbiddenException(${JSON.stringify(`Forbidden: ${s.source}`)});`,

    let: (s) =>
      // `let`-names may collide with a C# keyword (`let base = …` → `var
      // @base`); the same escape applies at every `refKind: "let"` use site.
      `${INDENT}var ${escapeCsharpIdent(s.name)} = ${renderCsExpr(s.expr, ctx)};`,

    assign: (s, ix) => {
      const base = `${INDENT}${renderPath(s.target)} = ${renderCsExpr(s.value, ctx)};`;
      // NOTE the wrap ORDER: .NET (like java / python) puts `value_computed`
      // INSIDE the provenance capture; node puts it outside.  Preserved.
      const traced = withValueComputed(base, s.target, traceCtx);
      const full = withProvCapture(traced, s.prov, s.target, s.value, ix.prov, ctx);
      return isSelfAssign(s.target, s.value) ? withCa2245Suppressed(full) : full;
    },

    add: (s, ix) => {
      const base = `${INDENT}${renderPrivatePath(s.target, ctx)}.Add(${renderCsExpr(s.value, ctx)});`;
      return withProvCapture(base, s.prov, s.target, s.value, ix.prov, ctx);
    },

    remove: (s, ix) => {
      const base = `${INDENT}${renderPrivatePath(s.target, ctx)}.Remove(${renderCsExpr(s.value, ctx)});`;
      return withProvCapture(base, s.prov, s.target, s.value, ix.prov, ctx);
    },

    emit: (s) => {
      const args = s.fields
        .map((f) => `${upperFirst(f.name)}: ${renderCsExpr(f.value, ctx)}`)
        .join(", ");
      // Event-sourced: record the event and fold it immediately, so the
      // aggregate's in-memory state reflects the transition before the
      // command returns (the applier is the only place state changes).
      if (traceCtx.eventSourced) {
        return `${INDENT}{ var __ev = new ${s.eventName}(${args}); _domainEvents.Add(__ev); _Apply(__ev); }`;
      }
      return `${INDENT}_domainEvents.Add(new ${s.eventName}(${args}));`;
    },

    call: (s) => {
      const args = s.args.map((a) => renderCsExpr(a, ctx)).join(", ");
      return `${INDENT}this.${upperFirst(s.name)}(${args});`;
    },

    expression: (s) => `${INDENT}${renderCsExpr(s.expr, ctx)};`,

    return: (s) => {
      // Exception-less operation return (exception-less.md): a tagged return
      // constructs the Domain union's variant record `<Union>_<Tag>(...)`.  A
      // record variant orders its positional args by the variant's declared
      // field order (from `ctx.returnUnion.members`), looking each up by name in
      // the lowered object literal; a scalar wraps the single value; `none` is
      // the empty unit.  Untagged returns (plain value) render the value as-is.
      if (!s.variantTag || !ctx.returnUnion) {
        return `${INDENT}return ${renderCsExpr(s.value, ctx)};`;
      }
      const variant = `${ctx.returnUnion.name}_${s.variantTag}`;
      if (s.variantShape === "none") return `${INDENT}return new ${variant}();`;
      if (s.variantShape === "scalar") {
        return `${INDENT}return new ${variant}(${renderCsExpr(s.value, ctx)});`;
      }
      const member = ctx.returnUnion.members.find((m) => m.tag === s.variantTag);
      const objFields = s.value.kind === "object" ? s.value.fields : [];
      const order = member && member.shape === "record" ? member.fields : [];
      const args = order.map((mf) => {
        const f = objFields.find((of) => of.name === mf.name);
        return f ? renderCsExpr(f.value, ctx) : "default";
      });
      return `${INDENT}return new ${variant}(${args.join(", ")});`;
    },
  };
}

/** Render a precondition.  Trace-off: the one-liner throw.  Trace-on:
 *  bind the boolean to a temp so BOTH pass and fail outcomes log
 *  (precondition_evaluated) before the conditional throw fires off the
 *  same temp.  Pattern matches the Hono render-stmt.ts shape exactly. */
function precondition(
  expr: ExprIR,
  source: string,
  message: MessageIR | undefined,
  index: number,
  ctx: CsRenderContext,
  traceCtx: TraceCtx,
): string {
  // Author `message "..."` becomes the domain-floor detail; else the default.
  const detail = message ? message.text : `Precondition failed: ${source}`;
  const thrown = `throw new DomainException(${JSON.stringify(detail)})`;
  if (!traceCtx.emitTrace) {
    return `${INDENT}if (!(${renderCsExpr(expr, ctx)})) ${thrown};`;
  }
  const ok = `__pre_${index}_ok`;
  return [
    `${INDENT}var ${ok} = (${renderCsExpr(expr, ctx)});`,
    `${INDENT}${ns_DomainLog}.LogTrace("{Event} aggregate={Aggregate} op={Op} expr={Expr} passed={Passed}", "precondition_evaluated", "${traceCtx.aggregate}", "${traceCtx.op}", ${JSON.stringify(source)}, ${ok});`,
    `${INDENT}if (!${ok}) ${thrown};`,
  ].join("\n");
}

/** Under --trace, append a `value_computed` trace line after a scalar
 *  assign so the post-write value is observable.  Skipped for paths
 *  into containments (length > 1) — those are write-through paths to
 *  a sub-object, not a top-level field of the aggregate. */
function withValueComputed(base: string, target: PathIR, traceCtx: TraceCtx): string {
  if (!traceCtx.emitTrace) return base;
  if (target.segments.length !== 1) return base;
  const field = target.segments[0]!;
  return [
    base,
    `${INDENT}${ns_DomainLog}.LogTrace("{Event} aggregate={Aggregate} field={Field} value={Value}", "value_computed", "${traceCtx.aggregate}", "${field}", ${renderPath(target)});`,
  ].join("\n");
}

/** Wrap a provenanced write (a statement carrying a `ProvSite`) with lineage
 *  capture — the .NET mirror of the Hono `withTrace`.  Snapshot the leaf
 *  inputs *before* the mutation (so a self-referential `x := x + n` records the
 *  pre-write value), perform the write, then build the `ProvLineage` (rule
 *  snapshot + inputs + post-write computed value) and route it to both sinks:
 *  the co-located `<Field>Provenance` property (current lineage, persisted on
 *  the row) and the per-instance `_provTraces` buffer (drained into
 *  provenance_records by the repository inside the save transaction).
 *
 *  PRESERVED INCONSISTENCY (audit C1): .NET and java gate on `prov` presence
 *  alone (no `emitProvenance` switch — the entity emitter only threads a `prov`
 *  when it emits the co-located slot) and skip write-throughs into a
 *  containment; node and python honour the switch and capture at any path
 *  depth.  Kept verbatim — reconciling them is a behaviour change on some
 *  backend, not a refactor. */
function withProvCapture(
  base: string,
  prov: ProvSite | undefined,
  target: PathIR,
  value: ExprIR,
  index: number,
  ctx: CsRenderContext,
): string {
  if (!prov) return base;
  // Co-located capture is for top-level provenanced fields of the aggregate
  // root (the `<Field>Provenance` property + `_provTraces` buffer live on the
  // root).  A write-through into a containment (segments.length > 1) targets a
  // sub-object, which carries no co-located lineage slot — skip, mirroring the
  // value-computed trace's same guard.
  if (target.segments.length !== 1) return base;
  const inputs = collectLeaves(value, (x) => renderCsExpr(x, ctx))
    .map((l) => `new ProvInput(${JSON.stringify(l.path)}, ${l.value})`)
    .join(", ");
  const { tmp, lin } = provTempNames(index);
  const computed = renderPath(target);
  const field = `${upperFirst(prov.target.field)}Provenance`;
  const targetLit = `new ProvTarget(${JSON.stringify(prov.target.type)}, ${JSON.stringify(prov.target.field)})`;
  return wrapProvCapture(base, {
    snapshot: `${INDENT}var ${tmp} = new List<ProvInput> { ${inputs} };`,
    lineage: `${INDENT}var ${lin} = new ProvLineage(${JSON.stringify(prov.snapshotId)}, ${targetLit}, ${tmp}, ${computed});`,
    colocated: `${INDENT}this.${field} = ${lin};`,
    sink: `${INDENT}this._provTraces.Add(${lin});`,
  });
}

// `DomainLog` is the static AsyncLocal accessor emitted under
// Domain/Common/ when --trace is on (see emit/domain-log.ts).  The
// trace-injected calls reference it unqualified — same-namespace
// (`<ns>.Domain.<Plural>`) → `<ns>.Domain.Common`.  C# resolves the
// unqualified `DomainLog.LogTrace(…)` via the entity file's `using
// <ns>.Domain.Common;` (which the entity emitter adds when emitTrace
// is on).
const ns_DomainLog = "DomainLog";

function renderPath(p: PathIR): string {
  return p.segments.map((s) => upperFirst(s)).join(".");
}

/** `x := x` on an entity field — a write whose value is the field's own
 *  current value.  Legal Loom (a private command that only re-runs the
 *  invariants is the canonical case, cf. `test/fixtures/corpus/audited.ddd`),
 *  and it lowers to a single-segment target plus a `this-prop` ref naming that
 *  same property. */
function isSelfAssign(target: PathIR, value: ExprIR): boolean {
  return (
    target.segments.length === 1 &&
    value.kind === "ref" &&
    value.refKind === "this-prop" &&
    value.name === target.segments[0]
  );
}

/** Roslyn's CA2245 rejects `Quantity = this.Quantity`, and the generated .NET
 *  projects build with `/warnaserror` — so a self-assignment that is perfectly
 *  valid `.ddd` would fail the compile tier (it did: `corpus × dotnet`).
 *
 *  Suppressed at the statement rather than dropped, deliberately: the write
 *  site still carries its provenance capture and `#line` trace mapping, both
 *  of which are observable, and skipping the emission would silently discard
 *  them.  The pragma is the outermost wrapper so it covers whatever those
 *  layers added.
 *
 *  WHY ONLY .NET.  The other backends emit the same self-assignment and none of
 *  them needs a suppression, but for DIFFERENT reasons — worth stating, because
 *  "the linter is off" is the plausible-sounding wrong answer:
 *
 *    - node: `biome.generated.json` sets `recommended: true`, so
 *      `correctness/noSelfAssign` IS enabled.  It simply does not cover member
 *      expressions — it fires on `x = x` and not on `this._q = this._q`, which
 *      is the only shape this emitter produces.  Verified against the rule, not
 *      inferred from the config.
 *    - java / python / elixir: `x = x` on a field is neither an error nor a
 *      lint failure in their emitted-code gates.
 *
 *  So the asymmetry is Roslyn's analyzer being stricter than the rest, not a
 *  gap in the other backends' gates.  If biome ever extends `noSelfAssign` to
 *  member expressions, node needs the `// biome-ignore` twin of this pragma. */
function withCa2245Suppressed(rendered: string): string {
  return [
    `${INDENT}#pragma warning disable CA2245 // \`x := x\` is a valid no-op write in Loom`,
    rendered,
    `${INDENT}#pragma warning restore CA2245`,
  ].join("\n");
}

// For collection mutation we go via the private backing field — EXCEPT when
// the head is not a CONTAINMENT, in which case the entity emitter exposes a
// writable `List<T>` property with no `_` backing field and the public surface
// IS the mutable list.  Two shapes land there:
//
//   - `Id<T>[]` reference collections (`Target id[]`), identified via
//     `ctx.agg.associations`;
//   - plain SCALAR arrays (`codes: int[]`, `tags: string[]`), identified by
//     the head naming a declared `field` rather than a `contains`.  Missing
//     that case emitted `_codes.Add(...)` against a class whose only member is
//     `public List<int> Codes` — CS0103, "the name '_codes' does not exist".
//     Found while adding the `collection-op-shapes` corpus fixture: no
//     fixture had ever mutated a scalar array, so the compile tier could not
//     see it.  (Sibling of audit A13, which is the Java half of the same
//     "scalar-array mutation" blind spot.)
//
// Falls back to the containment convention when there's no aggregate context.
function renderPrivatePath(p: PathIR, ctx?: CsRenderContext): string {
  if (p.segments.length === 0) return "this";
  const [head, ...tail] = p.segments;
  const isRefColl = !!ctx?.agg?.associations?.some((a) => a.fieldName === head);
  const isScalarField = !!ctx?.agg?.fields?.some((f) => f.name === head);
  const headPath = isRefColl || isScalarField ? upperFirst(head!) : `_${head}`;
  return `${headPath}${tail.map((t) => `.${upperFirst(t)}`).join("")}`;
}
