// .NET runtime capability translation, end-to-end.
//
// Capability AST (contributed by `with auditable` / `with softDeletable`)
// must reach the generated .cs output via the existing expression
// renderer.  No marker interfaces, no per-aggregate handler code,
// no hardcoded field names — just AST translation.
//
// What the tests verify:
//   - Entity class declaration stays plain (no `: IAuditable, ISoftDeletable`).
//   - Domain/Common/IAuditable.cs and Domain/Common/ISoftDeletable.cs
//     are NOT emitted (those were the old marker-interface path).
//   - HasQueryFilter is generated by translating the macro-supplied
//     predicate expression — so a `!this.isDeleted` predicate renders
//     as `x => !x.IsDeleted` (the lambda binder substitutes for `this`).
//   - The AuditableInterceptor is registry-driven: a switch on
//     entity type with per-aggregate stamping bodies; no
//     IAuditable-typed change-tracker scan.

import { NodeFileSystem } from "langium/node";
import { parseHelper } from "langium/test";
import { describe, expect, it } from "vitest";
import { generateDotnet } from "../../src/generator/dotnet/index.js";
import { createDddServices } from "../../src/language/ddd-module.js";
import type { Model } from "../../src/language/generated/ast.js";

async function modelFrom(source: string): Promise<Model> {
  const services = createDddServices(NodeFileSystem);
  const helper = parseHelper<Model>(services.Ddd);
  const doc = await helper(source, { validation: true });
  return doc.parseResult.value;
}

// `auditable` references Id<User> and currentUser, so the source
// always declares a sibling User aggregate (legacy single-context
// mode doesn't go through `system { user { ... } }` here).
const aggregateOnly = (extras: string) => `
  context Sales {
    aggregate User { name: string }
    aggregate Order ${extras} {
      subject: string
    }
    repository Orders for Order { }
    repository Users for User { }
  }
`;

describe(".NET generator: marker interfaces are gone", () => {
  it("does not emit Domain/Common/IAuditable.cs", async () => {
    const model = await modelFrom(aggregateOnly("with auditable"));
    const files = generateDotnet(model);
    expect([...files.keys()]).not.toContain("Domain/Common/IAuditable.cs");
  });

  it("does not emit Domain/Common/ISoftDeletable.cs", async () => {
    const model = await modelFrom(aggregateOnly("with softDeletable"));
    const files = generateDotnet(model);
    expect([...files.keys()]).not.toContain("Domain/Common/ISoftDeletable.cs");
  });

  it("entity class declaration carries no capability interface clause", async () => {
    const model = await modelFrom(aggregateOnly("with auditable, softDeletable"));
    const files = generateDotnet(model);
    const orderCs = files.get("Domain/Orders/Order.cs")!;
    expect(orderCs).toMatch(/public sealed class Order\n/);
    expect(orderCs).not.toMatch(/: IAuditable/);
    expect(orderCs).not.toMatch(/: ISoftDeletable/);
  });
});

describe(".NET generator: HasQueryFilter from contextFilter translation", () => {
  it("emits a translated lambda predicate, not a hardcoded one", async () => {
    const model = await modelFrom(aggregateOnly("with softDeletable"));
    const files = generateDotnet(model);
    const cfg = files.get("Infrastructure/Persistence/Configurations/OrderConfiguration.cs")!;
    // The macro contributes `!this.isDeleted`; rendered into a
    // lambda context with `x` as the binder, it becomes `!x.IsDeleted`.
    expect(cfg).toMatch(/b\.HasQueryFilter\(x => !x\.IsDeleted\)/);
  });

  it("does NOT install HasQueryFilter for non-softDeletable aggregates", async () => {
    const model = await modelFrom(aggregateOnly(""));
    const files = generateDotnet(model);
    const cfg = files.get("Infrastructure/Persistence/Configurations/OrderConfiguration.cs")!;
    expect(cfg).not.toMatch(/HasQueryFilter/);
  });
});

describe(".NET generator: registry-driven SaveChangesInterceptor", () => {
  it("emits AuditableInterceptor.cs when any aggregate has contextStamps", async () => {
    const model = await modelFrom(aggregateOnly("with auditable"));
    const files = generateDotnet(model);
    const path = "Infrastructure/Persistence/AuditableInterceptor.cs";
    expect([...files.keys()]).toContain(path);
    const src = files.get(path)!;
    // The interceptor is driven by a switch on entry.Entity's type
    // — no IAuditable scan.  Order is the aggregate carrying
    // stamping rules, so a `case Order ...` arm is present.
    expect(src).toMatch(/switch \(entry\.Entity\)/);
    expect(src).toMatch(/case Order /);
    // No marker-interface filter.
    expect(src).not.toMatch(/Entries<IAuditable>/);
  });

  it("interceptor body assigns the macro-supplied fields with rendered expressions", async () => {
    const model = await modelFrom(aggregateOnly("with auditable"));
    const files = generateDotnet(model);
    const src = files.get("Infrastructure/Persistence/AuditableInterceptor.cs")!;
    // onCreate stamps CreatedAt + CreatedBy; onUpdate stamps UpdatedAt + UpdatedBy.
    // The `now()` magic identifier renders as the same source the rest of
    // the .NET output uses for it; we just check the assignment lines exist.
    expect(src).toMatch(/e\.CreatedAt =/);
    expect(src).toMatch(/e\.CreatedBy =/);
    expect(src).toMatch(/e\.UpdatedAt =/);
    expect(src).toMatch(/e\.UpdatedBy =/);
  });

  it("Program.cs registers the interceptor when stamping is used", async () => {
    const model = await modelFrom(aggregateOnly("with auditable"));
    const files = generateDotnet(model);
    const program = files.get("Program.cs")!;
    expect(program).toMatch(/AddScoped<Sales\.Infrastructure\.Persistence\.AuditableInterceptor>/);
    expect(program).toMatch(/AddInterceptors\(sp\.GetRequiredService/);
  });

  it("does NOT emit interceptor or register it when no aggregate has contextStamps", async () => {
    const model = await modelFrom(aggregateOnly(""));
    const files = generateDotnet(model);
    expect([...files.keys()]).not.toContain(
      "Infrastructure/Persistence/AuditableInterceptor.cs",
    );
    const program = files.get("Program.cs")!;
    expect(program).not.toMatch(/AuditableInterceptor/);
  });

  it("softDeletable alone does NOT trigger stamping interceptor emission", async () => {
    const model = await modelFrom(aggregateOnly("with softDeletable"));
    const files = generateDotnet(model);
    // softDeletable contributes only contextFilters; no contextStamps,
    // so no interceptor is needed.
    expect([...files.keys()]).not.toContain(
      "Infrastructure/Persistence/AuditableInterceptor.cs",
    );
  });
});
