// ---------------------------------------------------------------------------
// Typed in-system api client (M-T4.8 slice 4d) — the Phoenix/Elixir caller
// half, and the last one: with this the `REMOTE_API_OP_UNSUPPORTED` set empties
// and the honest-gap validator that guarded the feature goes away.
//
// Same contract as the four siblings; Elixir idiom.  One
// `<resource>_<operation_id>/N` per operation the CALLEE exposes, replacing the
// untyped `get(path)` / `post(path, body)` verbs the `storage restApi` binding
// carries.  Paths come from `deriveContextOperations`, the response shape from
// `forApiRead(wireFieldsForAggregate(...))` — the same two derivations every
// other client reads, so none of them can drift from the callee.
//
// The boundary check is a PROJECTION, not a schema parse.  `Req` decodes JSON
// into a STRING-keyed map, and `o.code` in domain code is Elixir map-dot, which
// only works on ATOM keys — so the client rebuilds the response as an
// atom-keyed map naming exactly the callee's wire fields.  That is what makes
// the field list load-bearing here: an unknown field is dropped and a missing
// one lands as `nil` under its proper name, rather than the whole call
// succeeding with a shape the caller cannot read at all.
//
// Atom keys are safe because every key is a COMPILE-TIME literal from the wire
// shape — no `String.to_atom` on remote input, so no atom-table exhaustion.
//
// `req` is declared as a hex dep HERE.  An api-bound resource has no `storage`,
// so it never reaches the `restApi` ResourceAdapter that normally declares it —
// exactly the defect that shipped a `httpx`-importing Python client into a
// project with no `httpx` dependency.
// ---------------------------------------------------------------------------

import { forApiRead, wireFieldsForAggregate } from "../../ir/enrich/wire-projection.js";
import type { AggregateIR, SystemIR } from "../../ir/types/loom-ir.js";
import type { ApiResourceBinding } from "../../ir/util/api-resource-binding.js";
import { type ApiOperationIR, deriveContextOperations } from "../../ir/util/api-surface.js";
import { snake } from "../../util/naming.js";
import { resourceEnvUrlVar } from "../../util/resource-env.js";

/** The module the render layer calls into. */
export function apiClientModuleName(appModule: string): string {
  return `${appModule}.Resources.ApiClients`;
}

function aggregateNamed(sys: SystemIR, name: string): AggregateIR | undefined {
  for (const sd of sys.subdomains) {
    for (const ctx of sd.contexts) {
      const agg = ctx.aggregates.find((a) => a.name === name);
      if (agg) return agg;
    }
  }
  return undefined;
}

function servedContexts(sys: SystemIR, apiName: string) {
  const api = sys.apis.find((a) => a.name === apiName);
  if (!api) return [];
  return sys.subdomains.find((s) => s.name === api.sourceModule)?.contexts ?? [];
}

/** `/api/orders/{id}` → an Elixir string expression with path params encoded. */
function pathExpr(op: ApiOperationIR): string {
  const parts: string[] = [];
  let rest = op.path;
  for (const p of op.params) {
    if (p.location !== "path") continue;
    const token = `{${p.name}}`;
    const at = rest.indexOf(token);
    if (at < 0) continue;
    parts.push(JSON.stringify(rest.slice(0, at)));
    parts.push(`URI.encode_www_form(to_string(${snake(p.name)}))`);
    rest = rest.slice(at + token.length);
  }
  parts.push(JSON.stringify(rest));
  return parts.filter((s) => s !== '""').join(" <> ") || '""';
}

/** Emit the client module, or nothing when this deployable binds no in-system
 *  api (the gate that keeps existing projects byte-identical). */
export function emitElixirApiClients(
  bindings: readonly ApiResourceBinding[],
  sys: SystemIR,
  appModule: string,
): string | undefined {
  if (bindings.length === 0) return undefined;

  const out: string[] = [
    "# Auto-generated by Loom.  Typed in-system api clients (M-T4.8).",
    `defmodule ${apiClientModuleName(appModule)} do`,
    "  defmodule RemoteCallError do",
    '    @moduledoc """',
    "    Raised when an in-system call answers with a status the callee's contract",
    "    does not describe as a success.  Carries the status so a caller can branch",
    "    on it rather than string-matching a message.",
    '    """',
    "    defexception [:resource, :operation_id, :status]",
    "",
    "    @impl true",
    "    def message(e) do",
    '      "in-system call #{e.resource}.#{e.operation_id} failed with status #{e.status}"',
    "    end",
    "  end",
    "",
  ];

  for (const b of bindings) {
    const res = snake(b.resource.name);
    out.push(
      `  # ---- ${b.resource.name} -> api '${b.apiName}' (served by '${b.server.name}')`,
      "  #",
      "  # A FUNCTION, not a `@module_attribute`.  An attribute is evaluated at",
      "  # COMPILE time, and a release is compiled in the Docker image build —",
      "  # long before compose sets the variable — so the attribute form would",
      "  # bake in the localhost fallback and never see the real address.  No",
      "  # compiler can see that; it is a silent wrong-URL at runtime.",
      `  defp ${res}_base_url do`,
      `    System.get_env("${resourceEnvUrlVar(b.resource.name)}") || "http://localhost:3000"`,
      "  end",
      "",
    );

    for (const ctx of servedContexts(sys, b.apiName)) {
      for (const op of deriveContextOperations(ctx)) {
        const respAgg = op.responseType?.kind === "entity" ? op.responseType.name : undefined;
        const agg = respAgg ? aggregateNamed(sys, respAgg) : undefined;

        const bodyParams = op.params.filter((p) => p.location === "body");
        // Two body shapes, both derived (api-surface.ts): `create` carries ONE
        // whole-shape param, while a domain operation carries one per declared
        // argument, which the callee reads as a flat JSON object.  Sending only
        // the first silently drops every argument after it.
        const wholeShapeBody = bodyParams.length === 1 && bodyParams[0]?.type.kind === "entity";
        const query = op.params.filter((p) => p.location === "query");
        const params = op.params.map((p) => snake(p.name));

        out.push(
          `  def ${res}_${snake(op.id)}(${params.join(", ")}) do`,
          `    path = ${pathExpr(op)}`,
        );
        if (query.length > 0) {
          out.push(
            "    path =",
            "      path <>",
            '        "?" <>',
            "        URI.encode_query(%{",
            ...query.map((q) => `          ${JSON.stringify(q.name)} => ${snake(q.name)},`),
            "        })",
          );
        }
        const reqOpts = [`url: ${res}_base_url() <> path`, `method: :${op.method.toLowerCase()}`];
        if (bodyParams.length > 0) {
          const payload = wholeShapeBody
            ? snake(bodyParams[0]?.name ?? "body")
            : `%{${bodyParams.map((p) => `${JSON.stringify(p.name)} => ${snake(p.name)}`).join(", ")}}`;
          reqOpts.push(`json: ${payload}`);
        }
        out.push(
          "",
          "    res =",
          "      Req.request!(",
          ...reqOpts.map((o) => `        ${o},`),
          // No `decode_body:` — Req decodes JSON from the content-type by
          // default, and naming an option this emitter has not verified is how
          // a plausible-looking client fails at runtime rather than at compile.
          "        retry: false",
          "      )",
          "",
          "    if res.status >= 400 do",
          "      raise RemoteCallError,",
          `        resource: ${JSON.stringify(b.resource.name)},`,
          `        operation_id: ${JSON.stringify(op.id)},`,
          "        status: res.status",
          "    end",
          "",
        );
        if (agg) {
          // Project the STRING-keyed decoded body onto atom keys naming the
          // callee's wire fields — `o.code` in domain code is map-dot, which
          // only resolves atom keys.  Every key here is a compile-time literal.
          const fields = forApiRead(wireFieldsForAggregate(agg));
          out.push(
            // `payload`, not `body`: a whole-shape create takes a PARAMETER
            // named `body`, and rebinding it here reads as a bug even though
            // Elixir permits it.
            "    payload = res.body || %{}",
            "",
            "    %{",
            // No trailing comma on the last entry — Elixir map literals reject
            // one, and it is a parse error the emitter cannot see.
            ...fields.map(
              (wf, i) =>
                `      ${snake(wf.name)}: Map.get(payload, ${JSON.stringify(wf.name)})${
                  i === fields.length - 1 ? "" : ","
                }`,
            ),
            "    }",
          );
        } else {
          out.push("    :ok");
        }
        out.push("  end", "");
      }
    }
  }

  out.push("end", "");
  return out.join("\n");
}
