import type { StmtIR } from "../../ir/types/loom-ir.js";

// ---------------------------------------------------------------------------
// The shared operation-body statement spine — the `StmtIR` analogue of the
// `ExprTarget` seam in `_expr/target.ts` and the `WorkflowStmtTarget` seam in
// `_workflow/stmt-target.ts`.
//
// Every domain-logic backend's `render-stmt.ts` walks the same body: the
// 11-kind `StmtIR` sequence in declaration order, one chunk per statement,
// joined with `"\n"`.  Only the per-kind *spelling* diverges (the expression
// renderer, the indent, the throw/append/push idiom, the per-backend render
// context) plus the temp-name index model.  Without this seam each backend
// re-implements the whole switch, the `map`/`join` chunking pair, and the
// `variant-match` guard.
//
// `renderStmtChunksWith` owns the dispatch + the index bookkeeping once; each
// backend supplies a `StmtTarget` leaf table.  A new `StmtIR` kind is a compile
// error here (exhaustive switch) AND in every target (the interface), exactly
// like adding an `ExprIR.kind`.
//
// NOTE: `StmtIR` is FLAT for backend bodies — no kind nests a statement list
// (`variant-match` does, but it is frontend-only and never reaches a backend),
// so unlike `renderWorkflowStmts` this spine has no recursion to own.
//
// NOTE: the *indent* is deliberately NOT part of the contract.  Three backends
// hold it as a module constant and Python threads it per call; either way it is
// closed over by the leaf table its factory builds, which makes it a purer leaf
// concern than `WorkflowStmtTarget.indentUnit` (that one has to be shared
// because the workflow spine itself indents nested bodies).  The same is true of
// each backend's render context (`CsRenderContext` / `JavaRenderContext` /
// `PyStmtCtx`) and its trace context.
// ---------------------------------------------------------------------------

type ByKind<K extends StmtIR["kind"]> = Extract<StmtIR, { kind: K }>;

/**
 * Temp-name indices for the statement being rendered — the `N` in a traced
 * precondition's `__pre_N_ok` binding and in a provenanced write's
 * `__prov_N` / `__lin_N` pair.
 *
 * Two live models, kept apart because they produce DIFFERENT names for the same
 * body and byte-identity is the extraction's acceptance gate (see
 * `StmtTarget.indexing`).
 */
export interface StmtIndex {
  /** Index used for a traced precondition's `__pre_<n>_ok` binding. */
  readonly pre: number;
  /** Index used for a provenanced write's `__prov_<n>` / `__lin_<n>` pair. */
  readonly prov: number;
}

/**
 * How a backend numbers its statement temps.
 *
 * - `"positional"` — both indices are the statement's position in the body.
 *   Used by node / .NET / java.
 * - `"per-kind"` — `pre` counts only `precondition` statements and `prov` only
 *   provenanced `assign`/`add` statements, each from 0.  Used by python.
 *
 * PRESERVED INCONSISTENCY (audit C1): the two models are not equivalent — a
 * body whose second statement is its first precondition names the temp
 * `__pre_1_ok` on node/.NET/java and `__pre_0_ok` on python.  Nothing depends on
 * the numbering beyond uniqueness within a body, so both are correct; they are
 * merely inconsistent.  Normalising them is a deliberate, separately-gated
 * change (it moves generated bytes on one backend), NOT a side effect of this
 * extraction.
 */
export type StmtIndexing = "positional" | "per-kind";

/**
 * The per-backend leaf table for one statement body.
 *
 * Built by a factory that closes over everything the arms need (the indent, the
 * backend's expression render context, the `--trace` context, the
 * provenance-on flag), so the contract stays free of per-backend types.  Each
 * method returns the statement's whole — possibly multi-line — chunk.
 */
export interface StmtTarget {
  /** Backend name spliced into the `variant-match` guard's message
   *  (`"TS"` / `".NET"` / `"Java"` / `"Python"`). */
  readonly backendName: string;

  /** Temp-numbering model — see `StmtIndexing`. */
  readonly indexing: StmtIndexing;

  precondition(s: ByKind<"precondition">, ix: StmtIndex): string;
  /** Authorization gate — every backend renders a negated guard throwing its
   *  own Forbidden type, which the route layer maps to 403. */
  requires(s: ByKind<"requires">, ix: StmtIndex): string;
  let(s: ByKind<"let">, ix: StmtIndex): string;
  assign(s: ByKind<"assign">, ix: StmtIndex): string;
  add(s: ByKind<"add">, ix: StmtIndex): string;
  remove(s: ByKind<"remove">, ix: StmtIndex): string;
  emit(s: ByKind<"emit">, ix: StmtIndex): string;
  call(s: ByKind<"call">, ix: StmtIndex): string;
  expression(s: ByKind<"expression">, ix: StmtIndex): string;
  return(s: ByKind<"return">, ix: StmtIndex): string;
}

/** Render a statement body to the pre-joined whole — exactly
 *  `renderStmtChunksWith(...).join("\n")`, the shape every backend's
 *  `render<X>Statements` already had. */
export function renderStmtsWith(stmts: readonly StmtIR[], target: StmtTarget): string {
  return renderStmtChunksWith(stmts, target).join("\n");
}

/**
 * Render a statement body to one (possibly multi-line) chunk per statement.
 *
 * The chunk form is what a caller owning the final file content needs to
 * recover each statement's own line span for `SourceMapRecorder.fragment` (see
 * `statementSubRegions` in `../_trace/sourcemap.ts`, whose cursor walk is keyed
 * 1:1 against `stmts`).
 */
export function renderStmtChunksWith(stmts: readonly StmtIR[], target: StmtTarget): string[] {
  let pre = 0;
  let prov = 0;
  return stmts.map((s, i) => {
    // Order matters for `"per-kind"`: `pre` is evaluated before `prov`, and a
    // statement bumps at most one of the two — one single pass.
    const ix: StmtIndex =
      target.indexing === "positional"
        ? { pre: i, prov: i }
        : {
            pre: s.kind === "precondition" ? pre++ : 0,
            prov: (s.kind === "assign" || s.kind === "add") && s.prov ? prov++ : 0,
          };
    return renderStmt(s, target, ix);
  });
}

function renderStmt(s: StmtIR, target: StmtTarget, ix: StmtIndex): string {
  switch (s.kind) {
    case "precondition":
      return target.precondition(s, ix);
    case "requires":
      return target.requires(s, ix);
    case "let":
      return target.let(s, ix);
    case "assign":
      return target.assign(s, ix);
    case "add":
      return target.add(s, ix);
    case "remove":
      return target.remove(s, ix);
    case "emit":
      return target.emit(s, ix);
    case "call":
      return target.call(s, ix);
    case "expression":
      return target.expression(s, ix);
    case "return":
      return target.return(s, ix);
    case "variant-match":
      // Frontend-only effect statement (`match await op() { … }`,
      // async-actions-and-effects.md Stage 2) — gated to page/component action
      // bodies, never lowered into a backend body.  One guard for all four
      // backends.
      throw new Error(
        `variant-match statement is frontend-only; it must not reach the ${target.backendName} backend`,
      );
  }
}
