import type { MigrationsIR } from "../../../ir/types/migrations-ir.js";
import { lines } from "../../../util/code-builder.js";
import { renderPgStep } from "../../sql-pg.js";

// ---------------------------------------------------------------------------
// MigrationsIR → Flyway-style versioned SQL under
// `src/main/resources/db/migration/`.  The steps are rendered by the
// shared Postgres-SQL renderer (`src/generator/sql-pg.ts`) — Java only
// translates `MigrationStep[]` into files; it never re-derives schema.
//
// Version scheme: `V<version>.<n>__<Module>_<Name>.sql` — `<version>` is
// the module's snapshot-stamped timestamp and `<n>` the module's index
// within the deployable, keeping Flyway versions unique when several
// modules share the canonical BASE_TIMESTAMP.
// ---------------------------------------------------------------------------

export function emitJavaMigrations(migrations: MigrationsIR[], out: Map<string, string>): void {
  migrations.forEach((m, i) => {
    if (m.steps.length === 0) return;
    const sql = lines(
      `-- Auto-generated by Loom for module ${m.module} — do not edit by hand.`,
      `-- Derived from the shared MigrationsIR (see docs/migrations.md).`,
      ``,
      ...m.steps.map((s) => renderPgStep(s)),
      ``,
    );
    const name = `V${m.version}.${i + 1}__${sanitize(m.module)}_${sanitize(m.name)}.sql`;
    out.set(`src/main/resources/db/migration/${name}`, sql);
  });
}

/** Flyway descriptions: word characters only (anything else would shift
 *  the `__` separator parse). */
function sanitize(s: string): string {
  return s.replace(/[^A-Za-z0-9]/g, "");
}
