import { lines } from "../../../util/code-builder.js";

// ---------------------------------------------------------------------------
// Observability catalog — JSON event lines on stdout, the cross-backend
// envelope the obs e2e suites assert:
//
//   server_starting → server_listening → request_start {method,path} →
//   request_end {status, durationMs} → server_shutdown → server_drained
//
// Emitted as flat JSON objects via a tiny writer (no logging-framework
// configuration to drift).  Mirrors dotnet's AddJsonConsole catalog and
// Hono's pino lines in event vocabulary.
// ---------------------------------------------------------------------------

export function renderCatalogLogger(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.time.Instant;`,
    `import java.util.Map;`,
    ``,
    `import org.slf4j.MDC;`,
    ``,
    `/** Catalog event writer — one flat JSON object per line on stdout.  Every`,
    ` *  line leads with the cross-backend envelope (\`ts\`, \`level\`, \`event\`),`,
    ` *  then the ambient carrier ids (request_id / scope_id / actor_id) read`,
    ` *  from MDC so a log line joins to the audit / provenance rows of the same`,
    ` *  request frame (omitted on boot-time lines, where no frame is active).`,
    ` *`,
    ` *  Emission is gated by the \`LOG_LEVEL\` env var (default \`info\`); a line`,
    ` *  whose level is below the threshold is dropped.  Java has no \`trace\``,
    ` *  level, so a catalog \`trace\` event folds to \`debug\` (both for the`,
    ` *  emitted \`level\` value and for threshold comparison) — matching the`,
    ` *  Hono \`level: process.env.LOG_LEVEL ?? "info"\` channel. */`,
    `public final class CatalogLog {`,
    `    private CatalogLog() {`,
    `    }`,
    ``,
    `    // Numeric rank per level — higher = more severe.  trace folds onto debug.`,
    `    private static final Map<String, Integer> RANK = Map.of(`,
    `        "trace", 10, "debug", 10, "info", 20, "warn", 30, "error", 40);`,
    ``,
    `    private static final int THRESHOLD =`,
    `        RANK.getOrDefault(normalize(System.getenv("LOG_LEVEL")), 20);`,
    ``,
    `    /** Fold an incoming/configured level to a known rank key (trace → debug); `,
    `     *  null / unknown → "info". */`,
    `    private static String normalize(String level) {`,
    `        if (level == null) {`,
    `            return "info";`,
    `        }`,
    `        var l = level.toLowerCase();`,
    `        if (l.equals("trace")) {`,
    `            return "debug";`,
    `        }`,
    `        return RANK.containsKey(l) ? l : "info";`,
    `    }`,
    ``,
    `    /** kvs alternate key/value; values are JSON-escaped strings or raw numbers. */`,
    `    public static void event(String name, String level, Object... kvs) {`,
    `        var lvl = normalize(level);`,
    `        if (RANK.get(lvl) < THRESHOLD) {`,
    `            return;`,
    `        }`,
    `        var sb = new StringBuilder("{\\"ts\\":\\"").append(Instant.now().toString()).append('"');`,
    `        sb.append(",\\"level\\":\\"").append(lvl).append('"');`,
    `        sb.append(",\\"event\\":\\"").append(name).append('"');`,
    `        appendId(sb, "request_id", MDC.get(RequestContext.CORRELATION_ID));`,
    `        appendId(sb, "scope_id", MDC.get(RequestContext.SCOPE_ID));`,
    `        appendId(sb, "actor_id", MDC.get(RequestContext.ACTOR_ID));`,
    `        for (int i = 0; i + 1 < kvs.length; i += 2) {`,
    `            sb.append(",\\"").append(kvs[i]).append("\\":");`,
    `            var value = kvs[i + 1];`,
    `            if (value instanceof Number) {`,
    `                sb.append(value);`,
    `            } else {`,
    `                sb.append('"').append(escape(String.valueOf(value))).append('"');`,
    `            }`,
    `        }`,
    `        sb.append('}');`,
    `        System.out.println(sb);`,
    `    }`,
    ``,
    `    /** Append a carrier id when present (skipped on boot-time lines, where`,
    `     *  no request frame is active so MDC has no value). */`,
    `    private static void appendId(StringBuilder sb, String key, String value) {`,
    `        if (value != null) {`,
    `            sb.append(",\\"").append(key).append("\\":\\"").append(escape(value)).append('"');`,
    `        }`,
    `    }`,
    ``,
    `    private static String escape(String s) {`,
    `        return s.replace("\\\\", "\\\\\\\\").replace("\\"", "\\\\\\"");`,
    `    }`,
    `}`,
    ``,
  );
}

/** Flyway migration-lifecycle catalog events.  Spring Boot auto-configures
 *  Flyway and runs the emitted `db/migration/V*.sql` on boot; this callback
 *  hangs off that in-process run and surfaces the same
 *  migrations_starting / migration_applied / migrations_complete /
 *  migration_failed events the other backends emit — through CatalogLog, so
 *  they share the envelope.  Wired via a FlywayConfigurationCustomizer bean,
 *  emitted only when the project ships migrations. */
export function renderMigrationCatalogCallback(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import org.flywaydb.core.api.callback.Callback;`,
    `import org.flywaydb.core.api.callback.Context;`,
    `import org.flywaydb.core.api.callback.Event;`,
    `import org.springframework.boot.flyway.autoconfigure.FlywayConfigurationCustomizer;`,
    `import org.springframework.context.annotation.Bean;`,
    `import org.springframework.context.annotation.Configuration;`,
    ``,
    `/** Emits the cross-backend migration-lifecycle catalog events from Flyway's`,
    ` *  in-process boot run.  \`id\` = the migration version, \`name\` = its`,
    ` *  description; durations are Flyway's per-migration execution time. */`,
    `@Configuration`,
    `public class MigrationCatalogConfig {`,
    `    @Bean`,
    `    FlywayConfigurationCustomizer migrationCatalogCustomizer() {`,
    `        return configuration -> configuration.callbacks(new MigrationCatalogCallback());`,
    `    }`,
    ``,
    `    static final class MigrationCatalogCallback implements Callback {`,
    `        @Override`,
    `        public boolean supports(Event event, Context context) {`,
    `            return event == Event.BEFORE_MIGRATE`,
    `                || event == Event.AFTER_EACH_MIGRATE`,
    `                || event == Event.AFTER_MIGRATE`,
    `                || event == Event.AFTER_EACH_MIGRATE_ERROR`,
    `                || event == Event.AFTER_MIGRATE_ERROR;`,
    `        }`,
    ``,
    `        @Override`,
    `        public boolean canHandleInTransaction(Event event, Context context) {`,
    `            return true;`,
    `        }`,
    ``,
    `        @Override`,
    `        public void handle(Event event, Context context) {`,
    `            var info = context.getMigrationInfo();`,
    `            switch (event) {`,
    `                case BEFORE_MIGRATE -> CatalogLog.event("migrations_starting", "info");`,
    `                case AFTER_EACH_MIGRATE -> {`,
    `                    if (info != null) {`,
    `                        CatalogLog.event("migration_applied", "info",`,
    `                            "id", String.valueOf(info.getVersion()),`,
    `                            "name", info.getDescription(),`,
    `                            "duration_ms", info.getExecutionTime());`,
    `                    }`,
    `                }`,
    `                case AFTER_MIGRATE -> CatalogLog.event("migrations_complete", "info");`,
    `                case AFTER_EACH_MIGRATE_ERROR, AFTER_MIGRATE_ERROR -> {`,
    `                    if (info != null) {`,
    `                        CatalogLog.event("migration_failed", "error",`,
    `                            "id", String.valueOf(info.getVersion()),`,
    `                            "name", info.getDescription(),`,
    `                            "error", "migration failed");`,
    `                    } else {`,
    `                        CatalogLog.event("migration_failed", "error", "error", "migration failed");`,
    `                    }`,
    `                }`,
    `                default -> {`,
    `                }`,
    `            }`,
    `        }`,
    ``,
    `        @Override`,
    `        public String getCallbackName() {`,
    `            return "MigrationCatalogCallback";`,
    `        }`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderLifecycleCatalog(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import org.springframework.boot.context.event.ApplicationReadyEvent;`,
    `import org.springframework.context.event.ContextClosedEvent;`,
    `import org.springframework.context.event.EventListener;`,
    `import org.springframework.stereotype.Component;`,
    ``,
    `/** Server lifecycle catalog events (server_starting is printed by`,
    ` *  Application.main before the context boots). */`,
    `@Component`,
    `public class LifecycleCatalog {`,
    `    @EventListener(ApplicationReadyEvent.class)`,
    `    public void onReady() {`,
    `        CatalogLog.event("server_listening", "info");`,
    `    }`,
    ``,
    `    @EventListener(ContextClosedEvent.class)`,
    `    public void onClosed() {`,
    `        CatalogLog.event("server_shutdown", "info");`,
    `        CatalogLog.event("server_drained", "info");`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderRequestCatalogFilter(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.io.IOException;`,
    ``,
    `import org.springframework.stereotype.Component;`,
    `import org.springframework.web.filter.OncePerRequestFilter;`,
    `import org.springframework.web.servlet.HandlerMapping;`,
    ``,
    `import jakarta.servlet.FilterChain;`,
    `import jakarta.servlet.ServletException;`,
    `import jakarta.servlet.http.HttpServletRequest;`,
    `import jakarta.servlet.http.HttpServletResponse;`,
    ``,
    `/** Catalog request span — request_start / request_end with status +`,
    ` *  duration, the cross-backend access-log shape.  Also records the`,
    ` *  Prometheus HTTP metrics at the request_end seam. */`,
    `@Component`,
    `public class RequestCatalogFilter extends OncePerRequestFilter {`,
    `    private final HttpMetrics metrics;`,
    ``,
    `    public RequestCatalogFilter(HttpMetrics metrics) {`,
    `        this.metrics = metrics;`,
    `    }`,
    ``,
    `    @Override`,
    `    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)`,
    `            throws ServletException, IOException {`,
    `        var startedAt = System.nanoTime();`,
    `        CatalogLog.event("request_start", "info", "method", request.getMethod(), "path", request.getRequestURI());`,
    `        try {`,
    `            chain.doFilter(request, response);`,
    `        } finally {`,
    `            var durationMs = (System.nanoTime() - startedAt) / 1_000_000.0;`,
    `            CatalogLog.event(`,
    `                "request_end",`,
    `                "info",`,
    `                "method", request.getMethod(),`,
    `                "path", request.getRequestURI(),`,
    `                "status", response.getStatus(),`,
    `                "duration_ms", durationMs);`,
    // The matched handler pattern (`/api/carts/{id}`) is stashed on the
    // request by DispatcherServlet during chain.doFilter; read it here for a
    // bounded Prometheus `route` label, falling back to the raw URI.
    `            var pattern = request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE);`,
    `            var route = pattern instanceof String s ? s : request.getRequestURI();`,
    `            metrics.record(request.getMethod(), route, response.getStatus(), durationMs);`,
    `        }`,
    `    }`,
    `}`,
    ``,
  );
}
