// ---------------------------------------------------------------------------
// Project-shell emitters for the Java backend: build.gradle.kts +
// settings.gradle.kts, Application.java, application.yml, the /health +
// /ready endpoints, Dockerfile.
//
// Gradle (Kotlin DSL) is the build — the right default for the Java
// ecosystem and for future multi-module emission (composite builds).
// The Spring Boot plugin's dependency management pins every version we
// don't set explicitly (Hibernate, Jackson, the Postgres driver, Flyway),
// so the generated build file stays small and upgrade-friendly.  No
// gradle-wrapper.jar is committed: the generator emits text files only,
// and every environment the toolchain controls provides Gradle itself
// (the Dockerfile's `gradle` base image, CI's runner toolchain, local
// dev with Gradle ≥ 8 — or run `gradle wrapper` once to add one).
// ---------------------------------------------------------------------------

import { lines } from "../../../util/code-builder.js";

/** Spring Boot release the generated projects build against.  Bumping it
 *  is a single-constant change validated by `LOOM_JAVA_BUILD=1`. */
export const SPRING_BOOT_VERSION = "4.1.0";

/** Spring's Gradle dependency-management plugin (BOM import). */
export const DEPENDENCY_MANAGEMENT_VERSION = "1.1.7";

/** Java language level for the generated projects. */
export const JAVA_VERSION = "21";

/** jMolecules DDD/event annotation libraries — metadata-only deps that
 *  make the generated domain idiomatically DDD (@AggregateRoot /
 *  @ValueObject / @DomainEvent) and enable ArchUnit verification. */
export const JMOLECULES_VERSION = "1.10.0";

/** springdoc serves the OpenAPI document (`/openapi.json`) the
 *  cross-backend conformance harness diffs. */
export const SPRINGDOC_VERSION = "3.0.3";

/** Nimbus JOSE+JWT — the JWKS/JWT library the generated OIDC verifier uses
 *  (D-AUTH-OIDC).  Pinned explicitly: unlike Flyway / Spring Security, the
 *  Spring Boot BOM does NOT manage `nimbus-jose-jwt` on its own (only when
 *  spring-security-oauth2-jose is on the classpath, which the generated
 *  backend doesn't pull), so a version-less coordinate fails to resolve. */
export const NIMBUS_JOSE_JWT_VERSION = "10.3";

export function renderGradleBuild(
  options: { flyway?: boolean; oidc?: boolean; extraDeps?: Record<string, string> } = {},
): string {
  return lines(
    `plugins {`,
    `    java`,
    `    id("org.springframework.boot") version "${SPRING_BOOT_VERSION}"`,
    `    id("io.spring.dependency-management") version "${DEPENDENCY_MANAGEMENT_VERSION}"`,
    `}`,
    ``,
    `group = "com.loom"`,
    `version = "0.1.0"`,
    `description = "Generated by Loom - do not edit by hand."`,
    ``,
    `java {`,
    `    toolchain {`,
    `        languageVersion = JavaLanguageVersion.of(${JAVA_VERSION})`,
    `    }`,
    `}`,
    ``,
    `repositories {`,
    `    mavenCentral()`,
    `}`,
    ``,
    `dependencies {`,
    `    implementation("org.springframework.boot:spring-boot-starter-web")`,
    `    implementation("org.springframework.boot:spring-boot-starter-data-jpa")`,
    `    runtimeOnly("org.postgresql:postgresql")`,
    `    implementation("org.jmolecules:jmolecules-ddd:${JMOLECULES_VERSION}")`,
    `    implementation("org.jmolecules:jmolecules-events:${JMOLECULES_VERSION}")`,
    `    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:${SPRINGDOC_VERSION}")`,
    // Flyway runs the emitted db/migration/V*.sql on boot.  Spring Boot 4.x
    // no longer auto-configures Flyway from `flyway-core` alone — the
    // `spring-boot-starter-flyway` starter is what wires the
    // FlywayAutoConfiguration, so migrations would silently skip without it.
    // (versions managed by the imported BOM).  Only shipped when the
    // deployable owns migrations.
    options.flyway
      ? `    implementation("org.springframework.boot:spring-boot-starter-flyway")`
      : null,
    options.flyway ? `    implementation("org.flywaydb:flyway-database-postgresql")` : null,
    // OIDC turnkey auth (D-AUTH-OIDC): Nimbus JOSE+JWT — the lightweight
    // JWKS/JWT library Spring Security itself uses, for the generated
    // OidcUserVerifier.  Version pinned (NOT BOM-managed — see the const).
    // Shipped only when an `auth { oidc }` block targets this deployable.
    options.oidc
      ? `    implementation("com.nimbusds:nimbus-jose-jwt:${NIMBUS_JOSE_JWT_VERSION}")`
      : null,
    // Resource-client deps (objectStore / queue adapters) — empty for
    // deployables wiring no consumable resources.
    ...Object.entries(options.extraDeps ?? {})
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([coord, version]) => `    implementation("${coord}:${version}")`),
    `    testImplementation("org.springframework.boot:spring-boot-starter-test")`,
    `    testRuntimeOnly("org.junit.platform:junit-platform-launcher")`,
    `}`,
    ``,
    `tasks.withType<Test> {`,
    `    useJUnitPlatform()`,
    `}`,
    ``,
  );
}

export function renderGradleSettings(artifactId: string): string {
  return lines(`rootProject.name = "${artifactId}"`, ``);
}

export function renderApplication(basePkg: string): string {
  return lines(
    `package ${basePkg};`,
    ``,
    `import org.springframework.boot.SpringApplication;`,
    `import org.springframework.boot.autoconfigure.SpringBootApplication;`,
    ``,
    `import ${basePkg}.config.CatalogLog;`,
    ``,
    `@SpringBootApplication`,
    `public class Application {`,
    `    public static void main(String[] args) {`,
    `        CatalogLog.event("server_starting", "info");`,
    `        SpringApplication.run(Application.class, args);`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderApplicationYml(slug: string): string {
  return lines(
    `server:`,
    `  port: 8080`,
    `spring:`,
    `  application:`,
    `    name: ${slug}`,
    `  datasource:`,
    `    url: \${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${slug}}`,
    `    username: \${SPRING_DATASOURCE_USERNAME:postgres}`,
    `    password: \${SPRING_DATASOURCE_PASSWORD:postgres}`,
    `  jpa:`,
    `    hibernate:`,
    `      ddl-auto: none`,
    `    open-in-view: false`,
    `springdoc:`,
    `  api-docs:`,
    `    path: /openapi.json`,
    `  swagger-ui:`,
    // Interactive Swagger UI (/swagger-ui.html) is gated OFF in production via
    // LOOM_OPENAPI_UI=false (the k8s chart sets it); the /openapi.json spec
    // (api-docs) stays available.  Default on for dev / compose / conformance.
    // biome-ignore lint/suspicious/noTemplateCurlyInString: literal Spring property placeholder emitted into application.yml, not a JS template literal
    "    enabled: ${LOOM_OPENAPI_UI:true}",
    ``,
  );
}

/** Liveness (`/health`, static) + readiness (`/ready`, DB-aware) probes.
 *  Compose health-checks point at `/ready` so dependents never race the
 *  schema bootstrap; `/health` stays cheap for liveness probing.
 *  Mirrors the dotnet backend's pair. */
export function renderHealthController(basePkg: string): string {
  return lines(
    `package ${basePkg}.api;`,
    ``,
    `import java.util.Map;`,
    `import javax.sql.DataSource;`,
    `import org.springframework.http.ResponseEntity;`,
    `import org.springframework.web.bind.annotation.GetMapping;`,
    `import org.springframework.web.bind.annotation.RestController;`,
    ``,
    `@RestController`,
    `public class HealthController {`,
    `    private final DataSource dataSource;`,
    ``,
    `    public HealthController(DataSource dataSource) {`,
    `        this.dataSource = dataSource;`,
    `    }`,
    ``,
    `    @GetMapping("/health")`,
    `    public Map<String, String> health() {`,
    `        return Map.of("status", "ok");`,
    `    }`,
    ``,
    `    @GetMapping("/ready")`,
    `    public ResponseEntity<Map<String, String>> ready() {`,
    `        try (var connection = dataSource.getConnection()) {`,
    `            if (connection.isValid(2)) {`,
    `                return ResponseEntity.ok(Map.of("status", "ready"));`,
    `            }`,
    `        } catch (Exception ignored) {`,
    `            // fall through to 503`,
    `        }`,
    `        return ResponseEntity.status(503).body(Map.of("status", "unavailable"));`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderDockerfile(
  options: { embeddedSpa?: boolean; spaOutDir?: string } = {},
): string {
  // Fullstack: a node stage builds the embedded React SPA (ClientApp/)
  // and the runtime image serves the bundle from /app/ui on the same
  // origin as the /api/* controllers (SpaWebConfig).
  const spaStage = options.embeddedSpa
    ? [
        `FROM node:22-alpine AS spa-build`,
        `WORKDIR /spa`,
        `COPY ClientApp/package.json ClientApp/package-lock.json* ./`,
        `RUN npm ci --prefer-offline --no-audit --no-fund || npm install`,
        `COPY ClientApp/ ./`,
        `RUN npm run build`,
        ``,
      ]
    : [];
  return lines(
    ...spaStage,
    `FROM gradle:8-jdk${JAVA_VERSION} AS build`,
    `WORKDIR /src`,
    // Optional proxy CAs — drop *.crt files into ./certs/ to make the build
    // trust a TLS-intercepting proxy (the same escape hatch the other
    // backends' Dockerfiles carry).  The JVM reads its OWN truststore, not
    // the OS bundle, so each cert in each bundle is keytool-imported into
    // the JDK cacerts.  The directory always exists (with a .gitkeep), so
    // this is a no-op when no CAs are configured.
    `COPY certs/ /tmp/loom-certs/`,
    `RUN if ls /tmp/loom-certs/*.crt >/dev/null 2>&1; then \\`,
    `      mkdir -p /tmp/loom-certs/split && \\`,
    `      cat /tmp/loom-certs/*.crt | awk 'BEGIN{n=0} /-----BEGIN CERTIFICATE-----/{n++} {print > ("/tmp/loom-certs/split/c" n ".pem")}' && \\`,
    `      for c in /tmp/loom-certs/split/c*.pem; do keytool -importcert -noprompt -cacerts -storepass changeit -alias "loom-$(basename "$c" .pem)" -file "$c" >/dev/null 2>&1 || true; done; \\`,
    `    fi`,
    `COPY build.gradle.kts settings.gradle.kts ./`,
    // Resolve the dependency graph in its own layer so source edits
    // don't re-download the world.
    `RUN gradle --no-daemon dependencies > /dev/null || true`,
    `COPY src ./src`,
    `RUN gradle --no-daemon -q bootJar`,
    ``,
    `FROM eclipse-temurin:${JAVA_VERSION}-jre`,
    `WORKDIR /app`,
    `COPY --from=build /src/build/libs/*.jar app.jar`,
    options.embeddedSpa
      ? `COPY --from=spa-build /spa/${options.spaOutDir ?? "dist"} /app/ui`
      : null,
    `EXPOSE 8080`,
    `ENTRYPOINT ["java", "-jar", "app.jar"]`,
    ``,
  );
}

export function renderDockerignore(
  options: { embeddedSpa?: boolean; spaOutDir?: string } = {},
): string {
  return lines(
    `build/`,
    `.gradle/`,
    `.idea/`,
    `*.iml`,
    options.embeddedSpa ? `ClientApp/node_modules/` : null,
    options.embeddedSpa ? `ClientApp/${options.spaOutDir ?? "dist"}/` : null,
    options.embeddedSpa && options.spaOutDir === "build" ? `ClientApp/.svelte-kit/` : null,
    ``,
  );
}

/** `shape(embedded)` — Hibernate's default Jackson FormatMapper only
 *  sees getters; the generated part classes carry package-private
 *  fields with record-style accessors, so the JSON columns ride a
 *  field-visibility mapper installed via HibernatePropertiesCustomizer.
 *  Emitted once per project when any embedded aggregate exists. */
export function renderJsonFormatMapperConfig(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import com.fasterxml.jackson.annotation.JsonAutoDetect;`,
    `import com.fasterxml.jackson.annotation.PropertyAccessor;`,
    `import tools.jackson.databind.MapperFeature;`,
    `import tools.jackson.databind.json.JsonMapper;`,
    `import org.hibernate.cfg.AvailableSettings;`,
    `import org.hibernate.type.format.jackson.Jackson3JsonFormatMapper;`,
    `import org.springframework.boot.hibernate.autoconfigure.HibernatePropertiesCustomizer;`,
    `import org.springframework.context.annotation.Bean;`,
    `import org.springframework.context.annotation.Configuration;`,
    ``,
    `@Configuration`,
    `public class LoomJsonFormatMapperConfig {`,
    `    @Bean`,
    `    public HibernatePropertiesCustomizer loomJsonFormatMapper() {`,
    `        var mapper = JsonMapper.builder()`,
    `            .findAndAddModules()`,
    `            .configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true)`,
    `            .changeDefaultVisibility(vc -> vc`,
    `                .withVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)`,
    `                .withVisibility(PropertyAccessor.GETTER, JsonAutoDetect.Visibility.NONE)`,
    `                .withVisibility(PropertyAccessor.IS_GETTER, JsonAutoDetect.Visibility.NONE)`,
    `                .withVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.ANY))`,
    `            .build();`,
    `        return props -> props.put(AvailableSettings.JSON_FORMAT_MAPPER, new Jackson3JsonFormatMapper(mapper));`,
    `    }`,
    `}`,
    ``,
  );
}

/** Fullstack mode — serve the embedded SPA bundle (UI_DIR, default
 *  /app/ui) on the same origin as the /api/* controllers, with the
 *  index.html fallback client-side routers need.  Controller mappings
 *  take precedence over resource handlers, so /api, /health, /ready
 *  and /openapi.json are unaffected. */
export function renderSpaWebConfig(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.io.IOException;`,
    ``,
    `import org.springframework.context.annotation.Configuration;`,
    `import org.springframework.core.io.Resource;`,
    `import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;`,
    `import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;`,
    `import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;`,
    `import org.springframework.web.servlet.resource.PathResourceResolver;`,
    ``,
    `@Configuration`,
    `public class SpaWebConfig implements WebMvcConfigurer {`,
    `    @Override`,
    `    public void addViewControllers(ViewControllerRegistry registry) {`,
    `        // "/" never reaches the resource resolver (empty path) — forward it.`,
    `        registry.addViewController("/").setViewName("forward:/index.html");`,
    `    }`,
    ``,
    `    @Override`,
    `    public void addResourceHandlers(ResourceHandlerRegistry registry) {`,
    `        var uiDir = System.getenv().getOrDefault("UI_DIR", "/app/ui");`,
    `        registry.addResourceHandler("/**")`,
    `            .addResourceLocations("file:" + uiDir + "/")`,
    `            .resourceChain(true)`,
    `            .addResolver(new PathResourceResolver() {`,
    `                @Override`,
    `                protected Resource getResource(String resourcePath, Resource location) throws IOException {`,
    `                    if (!resourcePath.isEmpty()) {`,
    `                        var requested = location.createRelative(resourcePath);`,
    `                        if (requested.isFile() && requested.exists() && requested.isReadable()) {`,
    `                            return requested;`,
    `                        }`,
    `                    }`,
    `                    // "/" and client-side routes → the SPA entry point.`,
    `                    return location.createRelative("index.html");`,
    `                }`,
    `            });`,
    `    }`,
    `}`,
    ``,
  );
}
