// ---------------------------------------------------------------------------
// Project-shell emitters for the Java backend: build.gradle.kts +
// settings.gradle.kts, Application.java, application.yml, the /health +
// /ready endpoints, Dockerfile.
//
// Gradle (Kotlin DSL) is the build — the right default for the Java
// ecosystem and for future multi-module emission (composite builds).
// The Spring Boot plugin's dependency management pins every version we
// don't set explicitly (Hibernate, Jackson, the Postgres driver, Flyway),
// so the generated build file stays small and upgrade-friendly.  No
// gradle-wrapper.jar is committed: the generator emits text files only,
// and every environment the toolchain controls provides Gradle itself
// (the Dockerfile's `gradle` base image, CI's runner toolchain, local
// dev with Gradle ≥ 8 — or run `gradle wrapper` once to add one).
// ---------------------------------------------------------------------------

import { lines } from "../../../util/code-builder.js";

/** Spring Boot release the generated projects build against.  Bumping it
 *  is a single-constant change validated by `LOOM_JAVA_BUILD=1`. */
export const SPRING_BOOT_VERSION = "3.5.14";

/** Spring's Gradle dependency-management plugin (BOM import). */
export const DEPENDENCY_MANAGEMENT_VERSION = "1.1.7";

/** Java language level for the generated projects. */
export const JAVA_VERSION = "21";

/** jMolecules DDD/event annotation libraries — metadata-only deps that
 *  make the generated domain idiomatically DDD (@AggregateRoot /
 *  @ValueObject / @DomainEvent) and enable ArchUnit verification. */
export const JMOLECULES_VERSION = "1.10.0";

/** springdoc serves the OpenAPI document (`/openapi.json`) the
 *  cross-backend conformance harness diffs. */
export const SPRINGDOC_VERSION = "2.8.17";

export function renderGradleBuild(options: { flyway?: boolean } = {}): string {
  return lines(
    `plugins {`,
    `    java`,
    `    id("org.springframework.boot") version "${SPRING_BOOT_VERSION}"`,
    `    id("io.spring.dependency-management") version "${DEPENDENCY_MANAGEMENT_VERSION}"`,
    `}`,
    ``,
    `group = "com.loom"`,
    `version = "0.1.0"`,
    `description = "Generated by Loom - do not edit by hand."`,
    ``,
    `java {`,
    `    toolchain {`,
    `        languageVersion = JavaLanguageVersion.of(${JAVA_VERSION})`,
    `    }`,
    `}`,
    ``,
    `repositories {`,
    `    mavenCentral()`,
    `}`,
    ``,
    `dependencies {`,
    `    implementation("org.springframework.boot:spring-boot-starter-web")`,
    `    implementation("org.springframework.boot:spring-boot-starter-data-jpa")`,
    `    runtimeOnly("org.postgresql:postgresql")`,
    `    implementation("org.jmolecules:jmolecules-ddd:${JMOLECULES_VERSION}")`,
    `    implementation("org.jmolecules:jmolecules-events:${JMOLECULES_VERSION}")`,
    `    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:${SPRINGDOC_VERSION}")`,
    // Flyway runs the emitted db/migration/V*.sql on boot (Boot
    // auto-configures it from the classpath; versions managed by the
    // imported BOM).  Only shipped when the deployable owns migrations.
    options.flyway ? `    implementation("org.flywaydb:flyway-core")` : null,
    options.flyway ? `    implementation("org.flywaydb:flyway-database-postgresql")` : null,
    `    testImplementation("org.springframework.boot:spring-boot-starter-test")`,
    `    testRuntimeOnly("org.junit.platform:junit-platform-launcher")`,
    `}`,
    ``,
    `tasks.withType<Test> {`,
    `    useJUnitPlatform()`,
    `}`,
    ``,
  );
}

export function renderGradleSettings(artifactId: string): string {
  return lines(`rootProject.name = "${artifactId}"`, ``);
}

export function renderApplication(basePkg: string): string {
  return lines(
    `package ${basePkg};`,
    ``,
    `import org.springframework.boot.SpringApplication;`,
    `import org.springframework.boot.autoconfigure.SpringBootApplication;`,
    ``,
    `import ${basePkg}.config.CatalogLog;`,
    ``,
    `@SpringBootApplication`,
    `public class Application {`,
    `    public static void main(String[] args) {`,
    `        CatalogLog.event("server_starting");`,
    `        SpringApplication.run(Application.class, args);`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderApplicationYml(slug: string): string {
  return lines(
    `server:`,
    `  port: 8080`,
    `spring:`,
    `  application:`,
    `    name: ${slug}`,
    `  datasource:`,
    `    url: \${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${slug}}`,
    `    username: \${SPRING_DATASOURCE_USERNAME:postgres}`,
    `    password: \${SPRING_DATASOURCE_PASSWORD:postgres}`,
    `  jpa:`,
    `    hibernate:`,
    `      ddl-auto: none`,
    `    open-in-view: false`,
    `springdoc:`,
    `  api-docs:`,
    `    path: /openapi.json`,
    ``,
  );
}

/** Liveness (`/health`, static) + readiness (`/ready`, DB-aware) probes.
 *  Compose health-checks point at `/ready` so dependents never race the
 *  schema bootstrap; `/health` stays cheap for liveness probing.
 *  Mirrors the dotnet backend's pair. */
export function renderHealthController(basePkg: string): string {
  return lines(
    `package ${basePkg}.api;`,
    ``,
    `import java.util.Map;`,
    `import javax.sql.DataSource;`,
    `import org.springframework.http.ResponseEntity;`,
    `import org.springframework.web.bind.annotation.GetMapping;`,
    `import org.springframework.web.bind.annotation.RestController;`,
    ``,
    `@RestController`,
    `public class HealthController {`,
    `    private final DataSource dataSource;`,
    ``,
    `    public HealthController(DataSource dataSource) {`,
    `        this.dataSource = dataSource;`,
    `    }`,
    ``,
    `    @GetMapping("/health")`,
    `    public Map<String, String> health() {`,
    `        return Map.of("status", "ok");`,
    `    }`,
    ``,
    `    @GetMapping("/ready")`,
    `    public ResponseEntity<Map<String, String>> ready() {`,
    `        try (var connection = dataSource.getConnection()) {`,
    `            if (connection.isValid(2)) {`,
    `                return ResponseEntity.ok(Map.of("status", "ready"));`,
    `            }`,
    `        } catch (Exception ignored) {`,
    `            // fall through to 503`,
    `        }`,
    `        return ResponseEntity.status(503).body(Map.of("status", "unavailable"));`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderDockerfile(): string {
  return lines(
    `FROM gradle:8-jdk${JAVA_VERSION} AS build`,
    `WORKDIR /src`,
    `COPY build.gradle.kts settings.gradle.kts ./`,
    // Resolve the dependency graph in its own layer so source edits
    // don't re-download the world.
    `RUN gradle --no-daemon dependencies > /dev/null || true`,
    `COPY src ./src`,
    `RUN gradle --no-daemon -q bootJar`,
    ``,
    `FROM eclipse-temurin:${JAVA_VERSION}-jre`,
    `WORKDIR /app`,
    `COPY --from=build /src/build/libs/*.jar app.jar`,
    `EXPOSE 8080`,
    `ENTRYPOINT ["java", "-jar", "app.jar"]`,
    ``,
  );
}

export function renderDockerignore(): string {
  return lines(`build/`, `.gradle/`, `.idea/`, `*.iml`, ``);
}
