// ---------------------------------------------------------------------------
// Project-shell emitters for the Java backend: pom.xml, Application.java,
// application.yml, the /health + /ready endpoints, Dockerfile.
// The Spring Boot parent POM manages every dependency version we don't
// pin explicitly (Hibernate, Jackson, the Postgres driver, Flyway), so the
// generated pom stays small and upgrade-friendly.
// ---------------------------------------------------------------------------

import { lines } from "../../../util/code-builder.js";

/** Spring Boot release the generated projects build against.  Bumping it
 *  is a single-constant change validated by `LOOM_JAVA_BUILD=1`. */
export const SPRING_BOOT_VERSION = "3.5.14";

/** Java language level for the generated projects. */
export const JAVA_VERSION = "21";

export function renderPom(ns: string, artifactId: string): string {
  return lines(
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<project xmlns="http://maven.apache.org/POM/4.0.0"`,
    `         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`,
    `         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">`,
    `  <modelVersion>4.0.0</modelVersion>`,
    ``,
    `  <parent>`,
    `    <groupId>org.springframework.boot</groupId>`,
    `    <artifactId>spring-boot-starter-parent</artifactId>`,
    `    <version>${SPRING_BOOT_VERSION}</version>`,
    `    <relativePath/>`,
    `  </parent>`,
    ``,
    `  <groupId>com.loom</groupId>`,
    `  <artifactId>${artifactId}</artifactId>`,
    `  <version>0.1.0</version>`,
    `  <name>${ns}</name>`,
    `  <description>Generated by Loom — do not edit by hand.</description>`,
    ``,
    `  <properties>`,
    `    <java.version>${JAVA_VERSION}</java.version>`,
    `  </properties>`,
    ``,
    `  <dependencies>`,
    `    <dependency>`,
    `      <groupId>org.springframework.boot</groupId>`,
    `      <artifactId>spring-boot-starter-web</artifactId>`,
    `    </dependency>`,
    `    <dependency>`,
    `      <groupId>org.springframework.boot</groupId>`,
    `      <artifactId>spring-boot-starter-data-jpa</artifactId>`,
    `    </dependency>`,
    `    <dependency>`,
    `      <groupId>org.postgresql</groupId>`,
    `      <artifactId>postgresql</artifactId>`,
    `      <scope>runtime</scope>`,
    `    </dependency>`,
    `    <dependency>`,
    `      <groupId>org.springframework.boot</groupId>`,
    `      <artifactId>spring-boot-starter-test</artifactId>`,
    `      <scope>test</scope>`,
    `    </dependency>`,
    `  </dependencies>`,
    ``,
    `  <build>`,
    `    <plugins>`,
    `      <plugin>`,
    `        <groupId>org.springframework.boot</groupId>`,
    `        <artifactId>spring-boot-maven-plugin</artifactId>`,
    `      </plugin>`,
    `    </plugins>`,
    `  </build>`,
    `</project>`,
    ``,
  );
}

export function renderApplication(basePkg: string): string {
  return lines(
    `package ${basePkg};`,
    ``,
    `import org.springframework.boot.SpringApplication;`,
    `import org.springframework.boot.autoconfigure.SpringBootApplication;`,
    ``,
    `@SpringBootApplication`,
    `public class Application {`,
    `    public static void main(String[] args) {`,
    `        SpringApplication.run(Application.class, args);`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderApplicationYml(slug: string): string {
  return lines(
    `server:`,
    `  port: 8080`,
    `spring:`,
    `  application:`,
    `    name: ${slug}`,
    `  datasource:`,
    `    url: \${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${slug}}`,
    `    username: \${SPRING_DATASOURCE_USERNAME:postgres}`,
    `    password: \${SPRING_DATASOURCE_PASSWORD:postgres}`,
    `  jpa:`,
    `    hibernate:`,
    `      ddl-auto: none`,
    `    open-in-view: false`,
    ``,
  );
}

/** Liveness (`/health`, static) + readiness (`/ready`, DB-aware) probes.
 *  Compose health-checks point at `/ready` so dependents never race the
 *  schema bootstrap; `/health` stays cheap for liveness probing.
 *  Mirrors the dotnet backend's pair. */
export function renderHealthController(basePkg: string): string {
  return lines(
    `package ${basePkg}.api;`,
    ``,
    `import java.util.Map;`,
    `import javax.sql.DataSource;`,
    `import org.springframework.http.ResponseEntity;`,
    `import org.springframework.web.bind.annotation.GetMapping;`,
    `import org.springframework.web.bind.annotation.RestController;`,
    ``,
    `@RestController`,
    `public class HealthController {`,
    `    private final DataSource dataSource;`,
    ``,
    `    public HealthController(DataSource dataSource) {`,
    `        this.dataSource = dataSource;`,
    `    }`,
    ``,
    `    @GetMapping("/health")`,
    `    public Map<String, String> health() {`,
    `        return Map.of("status", "ok");`,
    `    }`,
    ``,
    `    @GetMapping("/ready")`,
    `    public ResponseEntity<Map<String, String>> ready() {`,
    `        try (var connection = dataSource.getConnection()) {`,
    `            if (connection.isValid(2)) {`,
    `                return ResponseEntity.ok(Map.of("status", "ready"));`,
    `            }`,
    `        } catch (Exception ignored) {`,
    `            // fall through to 503`,
    `        }`,
    `        return ResponseEntity.status(503).body(Map.of("status", "unavailable"));`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderDockerfile(): string {
  return lines(
    `FROM maven:3.9-eclipse-temurin-${JAVA_VERSION} AS build`,
    `WORKDIR /src`,
    `COPY pom.xml .`,
    `RUN mvn -q -B dependency:go-offline`,
    `COPY src ./src`,
    `RUN mvn -q -B -DskipTests package`,
    ``,
    `FROM eclipse-temurin:${JAVA_VERSION}-jre`,
    `WORKDIR /app`,
    `COPY --from=build /src/target/*.jar app.jar`,
    `EXPOSE 8080`,
    `ENTRYPOINT ["java", "-jar", "app.jar"]`,
    ``,
  );
}

export function renderDockerignore(): string {
  return lines(`target/`, `.idea/`, `*.iml`, ``);
}
