import { lines } from "../../../util/code-builder.js";
import {
  HttpSpanAttr,
  OTEL_ENDPOINT_ENV,
  OTEL_SERVICE_NAME_ENV,
  SpanAttr,
} from "../../_obs/tracing.js";

// ---------------------------------------------------------------------------
// Ambient execution-context carrier (docs/architecture/request-context.md) —
// the Spring/MVC realisation, mirroring the Phoenix Logger.metadata carrier
// and the .NET AsyncLocal<RequestContext>.
//
// MVC has no AsyncLocal; the idiomatic ambient slot is SLF4J **MDC** (a
// ThreadLocal-backed map, always on the classpath via spring-boot-starter-
// logging).  An ExecutionContextFilter at the HTTP edge stamps the request-stable
// tier (correlation_id, locale, started_at) + the root frame's scope_id, echoes
// X-Correlation-Id, and clears MDC on the way out (pooled-thread hygiene).  The
// principal's actor_id is stamped post-auth by UserFilter (auth.ts) — only the
// id rides MDC; the full principal stays on CurrentUserAccessor.
//
// Per-dispatch child frames (parent_id chaining) and surfacing the ids onto the
// catalog log lines are deferred — see request-context.md.
// ---------------------------------------------------------------------------

export function renderRequestContext(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.util.UUID;`,
    ``,
    `import org.slf4j.MDC;`,
    ``,
    `/** Ambient per-request execution context, carried in SLF4J MDC.`,
    ` *  Established at the HTTP edge by ExecutionContextFilter; read elsewhere`,
    ` *  via the static accessors (no request handle needed). */`,
    `public final class RequestContext {`,
    `    public static final String CORRELATION_ID = "correlation_id";`,
    `    public static final String SCOPE_ID = "scope_id";`,
    `    public static final String PARENT_ID = "parent_id";`,
    `    public static final String ACTOR_ID = "actor_id";`,
    `    public static final String LOCALE = "locale";`,
    `    public static final String STARTED_AT = "started_at";`,
    `    /** OTel span/trace ids (hex) — the log<->trace join keys, whitelisted`,
    `     *  in config/logback.xml so every request-scoped line carries them. */`,
    `    public static final String TRACE_ID = "trace_id";`,
    `    public static final String SPAN_ID = "span_id";`,
    ``,
    `    /** OTel SERVER-span attribute keys — the execution-context ids`,
    `     *  projected onto the span, plus the HTTP semantic-convention keys. */`,
    `    public static final String CORRELATION_ID_ATTR = "${SpanAttr.correlationId}";`,
    `    public static final String SCOPE_ID_ATTR = "${SpanAttr.scopeId}";`,
    `    public static final String ACTOR_ID_ATTR = "${SpanAttr.actorId}";`,
    `    public static final String HTTP_METHOD_ATTR = "${HttpSpanAttr.method}";`,
    `    public static final String HTTP_ROUTE_ATTR = "${HttpSpanAttr.route}";`,
    `    public static final String URL_PATH_ATTR = "${HttpSpanAttr.path}";`,
    `    public static final String HTTP_STATUS_ATTR = "${HttpSpanAttr.statusCode}";`,
    ``,
    `    private RequestContext() {`,
    `    }`,
    ``,
    `    /** The correlation id for the current request, or null outside a request. */`,
    `    public static String correlationId() {`,
    `        return MDC.get(CORRELATION_ID);`,
    `    }`,
    ``,
    `    /** The id of the current execution frame (the root frame for a request). */`,
    `    public static String scopeId() {`,
    `        return MDC.get(SCOPE_ID);`,
    `    }`,
    ``,
    `    /** The parent frame's id, or null at the root frame. */`,
    `    public static String parentId() {`,
    `        return MDC.get(PARENT_ID);`,
    `    }`,
    ``,
    `    /** The principal's id, or null before auth has run / when the deployable carries no auth. */`,
    `    public static String actorId() {`,
    `        return MDC.get(ACTOR_ID);`,
    `    }`,
    ``,
    `    /** The request locale from Accept-Language, defaulting to "en". */`,
    `    public static String locale() {`,
    `        var value = MDC.get(LOCALE);`,
    `        return value != null ? value : "en";`,
    `    }`,
    ``,
    `    /** Epoch milliseconds at request start, or 0 outside a request. */`,
    `    public static long startedAt() {`,
    `        var value = MDC.get(STARTED_AT);`,
    `        return value != null ? Long.parseLong(value) : 0L;`,
    `    }`,
    ``,
    `    /** Mint a fresh id (correlation / scope). */`,
    `    public static String newId() {`,
    `        return UUID.randomUUID().toString();`,
    `    }`,
    ``,
    `    /** Stamp the actor id after auth resolves the principal — only the id`,
    `     *  rides MDC; the full principal stays on CurrentUserAccessor. */`,
    `    public static void putActorId(String id) {`,
    `        MDC.put(ACTOR_ID, id);`,
    `    }`,
    ``,
    `    /** Open a CHILD execution frame under the current one for the duration`,
    `     *  of a try-with-resources block: a fresh scope_id whose parent_id chains`,
    `     *  to the caller's scope_id, restored on close.  A per-dispatch boundary`,
    `     *  (a workflow, an event reactor) opens one so its audit / provenance rows`,
    `     *  record their call-structure position.  Outside a request (no current`,
    `     *  frame) it is a no-op. */`,
    `    public static Frame openChild() {`,
    `        var parentScope = MDC.get(SCOPE_ID);`,
    `        if (parentScope == null) {`,
    `            return new Frame(null, null);`,
    `        }`,
    `        var prevParent = MDC.get(PARENT_ID);`,
    `        MDC.put(SCOPE_ID, newId());`,
    `        MDC.put(PARENT_ID, parentScope);`,
    `        return new Frame(parentScope, prevParent);`,
    `    }`,
    ``,
    `    /** The restore handle from {@link #openChild()}; closing it pops back to`,
    `     *  the parent frame.  {@code close()} declares no checked exception so a`,
    `     *  try-with-resources block over it stays exception-transparent. */`,
    `    public static final class Frame implements AutoCloseable {`,
    `        private final String parentScope;`,
    `        private final String prevParent;`,
    ``,
    `        private Frame(String parentScope, String prevParent) {`,
    `            this.parentScope = parentScope;`,
    `            this.prevParent = prevParent;`,
    `        }`,
    ``,
    `        @Override`,
    `        public void close() {`,
    `            if (parentScope == null) {`,
    `                return;`,
    `            }`,
    `            MDC.put(SCOPE_ID, parentScope);`,
    `            if (prevParent != null) {`,
    `                MDC.put(PARENT_ID, prevParent);`,
    `            } else {`,
    `                MDC.remove(PARENT_ID);`,
    `            }`,
    `        }`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderExecutionContextFilter(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.io.IOException;`,
    ``,
    `import org.slf4j.MDC;`,
    `import org.springframework.core.Ordered;`,
    `import org.springframework.core.annotation.Order;`,
    `import org.springframework.stereotype.Component;`,
    `import org.springframework.web.filter.OncePerRequestFilter;`,
    `import org.springframework.web.servlet.HandlerMapping;`,
    ``,
    `import io.opentelemetry.api.trace.SpanKind;`,
    `import io.opentelemetry.api.trace.StatusCode;`,
    `import io.opentelemetry.context.Scope;`,
    ``,
    `import jakarta.servlet.FilterChain;`,
    `import jakarta.servlet.ServletException;`,
    `import jakarta.servlet.http.HttpServletRequest;`,
    `import jakarta.servlet.http.HttpServletResponse;`,
    ``,
    `/** Opens the ambient RequestContext at the HTTP edge.  Outermost filter`,
    ` *  (HIGHEST_PRECEDENCE) so the request-stable tier + root scope are set`,
    ` *  before any inner filter (auth, catalog) runs, and MDC is cleared once`,
    ` *  on the way out so a pooled thread never leaks context to the next request.`,
    ` *  Named ExecutionContextFilter (not RequestContextFilter) to avoid colliding`,
    ` *  with Spring's auto-configured \`requestContextFilter\` bean. */`,
    `@Component`,
    `@Order(Ordered.HIGHEST_PRECEDENCE)`,
    `public class ExecutionContextFilter extends OncePerRequestFilter {`,
    `    private static final String CORRELATION_HEADER = "X-Correlation-Id";`,
    `    private static final String REQUEST_ID_HEADER = "X-Request-Id";`,
    ``,
    `    @Override`,
    `    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)`,
    `            throws ServletException, IOException {`,
    `        var correlationId = resolveCorrelationId(request);`,
    `        var scopeId = RequestContext.newId();`,
    `        MDC.put(RequestContext.CORRELATION_ID, correlationId);`,
    `        MDC.put(RequestContext.SCOPE_ID, scopeId);`,
    `        MDC.put(RequestContext.LOCALE, resolveLocale(request));`,
    `        MDC.put(RequestContext.STARTED_AT, String.valueOf(System.currentTimeMillis()));`,
    `        response.setHeader(CORRELATION_HEADER, correlationId);`,
    `        // Open the request's OTel SERVER span.  Created on every`,
    `        // request so its trace_id / span_id ride the logs (whitelisted in`,
    `        // logback.xml); exported only when a collector endpoint is set.`,
    `        var span = Tracing.TRACER.spanBuilder(request.getMethod() + " " + request.getRequestURI())`,
    `                .setSpanKind(SpanKind.SERVER)`,
    `                .setAttribute(RequestContext.CORRELATION_ID_ATTR, correlationId)`,
    `                .setAttribute(RequestContext.SCOPE_ID_ATTR, scopeId)`,
    `                .setAttribute(RequestContext.HTTP_METHOD_ATTR, request.getMethod())`,
    `                .setAttribute(RequestContext.URL_PATH_ATTR, request.getRequestURI())`,
    `                .startSpan();`,
    `        var spanContext = span.getSpanContext();`,
    `        MDC.put(RequestContext.TRACE_ID, spanContext.getTraceId());`,
    `        MDC.put(RequestContext.SPAN_ID, spanContext.getSpanId());`,
    `        try (Scope ignored = span.makeCurrent()) {`,
    `            chain.doFilter(request, response);`,
    `        } finally {`,
    `            // Close the span at the same seam: rename to the resolved route`,
    `            // template, stamp status + the actor id (attached by auth`,
    `            // mid-request), and mark 5xx as span errors.`,
    `            var patternAttr = request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE);`,
    `            var route = patternAttr instanceof String s ? s : request.getRequestURI();`,
    `            span.updateName(request.getMethod() + " " + route);`,
    `            span.setAttribute(RequestContext.HTTP_ROUTE_ATTR, route);`,
    `            span.setAttribute(RequestContext.HTTP_STATUS_ATTR, (long) response.getStatus());`,
    `            var actorId = RequestContext.actorId();`,
    `            if (actorId != null) {`,
    `                span.setAttribute(RequestContext.ACTOR_ID_ATTR, actorId);`,
    `            }`,
    `            if (response.getStatus() >= 500) {`,
    `                span.setStatus(StatusCode.ERROR);`,
    `            }`,
    `            span.end();`,
    `            MDC.clear();`,
    `        }`,
    `    }`,
    ``,
    `    // Prefer the cross-backend X-Correlation-Id, then X-Request-Id, else mint.`,
    `    private static String resolveCorrelationId(HttpServletRequest request) {`,
    `        var correlation = request.getHeader(CORRELATION_HEADER);`,
    `        if (correlation != null && !correlation.isEmpty()) {`,
    `            return correlation;`,
    `        }`,
    `        var requestId = request.getHeader(REQUEST_ID_HEADER);`,
    `        if (requestId != null && !requestId.isEmpty()) {`,
    `            return requestId;`,
    `        }`,
    `        return RequestContext.newId();`,
    `    }`,
    ``,
    `    private static String resolveLocale(HttpServletRequest request) {`,
    `        var header = request.getHeader("Accept-Language");`,
    `        return header != null && !header.isEmpty() ? header : "en";`,
    `    }`,
    `}`,
    ``,
  );
}

/** Render `config/Tracing.java` — the process-wide OpenTelemetry holder
 *  (M-T7.1).  Builds an `OpenTelemetrySdk` with the `service.name` resource;
 *  wires the OTLP/HTTP exporter (via a batch processor) only when a collector
 *  endpoint is set — a span is still created on every request (so its
 *  trace_id rides the logs), but exported only when a collector is
 *  configured.  A JVM shutdown hook flushes buffered spans on drain. */
export function renderTracing(basePkg: string, serviceName: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import io.opentelemetry.api.OpenTelemetry;`,
    `import io.opentelemetry.api.common.AttributeKey;`,
    `import io.opentelemetry.api.common.Attributes;`,
    `import io.opentelemetry.api.trace.Tracer;`,
    `import io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter;`,
    `import io.opentelemetry.sdk.OpenTelemetrySdk;`,
    `import io.opentelemetry.sdk.resources.Resource;`,
    `import io.opentelemetry.sdk.trace.SdkTracerProvider;`,
    `import io.opentelemetry.sdk.trace.export.BatchSpanProcessor;`,
    ``,
    `/** Process-wide OpenTelemetry.  A SERVER span opens on every`,
    ` *  request (ExecutionContextFilter) so its trace_id / span_id ride the log`,
    ` *  envelope; spans are EXPORTED via OTLP/HTTP only when`,
    ` *  ${OTEL_ENDPOINT_ENV} is set. */`,
    `public final class Tracing {`,
    `    private static final OpenTelemetry OTEL = build();`,
    `    public static final Tracer TRACER = OTEL.getTracer("loom");`,
    ``,
    `    private Tracing() {`,
    `    }`,
    ``,
    `    private static OpenTelemetry build() {`,
    `        var serviceName = System.getenv().getOrDefault("${OTEL_SERVICE_NAME_ENV}", ${JSON.stringify(serviceName)});`,
    `        var resource = Resource.getDefault().merge(`,
    `                Resource.create(Attributes.of(AttributeKey.stringKey("service.name"), serviceName)));`,
    `        var providerBuilder = SdkTracerProvider.builder().setResource(resource);`,
    `        var endpoint = System.getenv("${OTEL_ENDPOINT_ENV}");`,
    `        if (endpoint != null && !endpoint.isBlank()) {`,
    `            var url = endpoint.replaceAll("/$", "") + "/v1/traces";`,
    `            providerBuilder.addSpanProcessor(`,
    `                    BatchSpanProcessor.builder(OtlpHttpSpanExporter.builder().setEndpoint(url).build()).build());`,
    `        }`,
    `        var sdk = OpenTelemetrySdk.builder().setTracerProvider(providerBuilder.build()).build();`,
    `        // Flush buffered spans to the collector before the JVM exits.`,
    `        Runtime.getRuntime().addShutdownHook(new Thread(sdk::close));`,
    `        return sdk;`,
    `    }`,
    `}`,
    ``,
  );
}
