import { lines } from "../../../util/code-builder.js";

// ---------------------------------------------------------------------------
// Ambient execution-context carrier (docs/architecture/request-context.md) —
// the Spring/MVC realisation, mirroring the Phoenix Logger.metadata carrier
// and the .NET AsyncLocal<RequestContext>.
//
// MVC has no AsyncLocal; the idiomatic ambient slot is SLF4J **MDC** (a
// ThreadLocal-backed map, always on the classpath via spring-boot-starter-
// logging).  An ExecutionContextFilter at the HTTP edge stamps the request-stable
// tier (correlation_id, locale, started_at) + the root frame's scope_id, echoes
// X-Correlation-Id, and clears MDC on the way out (pooled-thread hygiene).  The
// principal's actor_id is stamped post-auth by UserFilter (auth.ts) — only the
// id rides MDC; the full principal stays on CurrentUserAccessor.
//
// Per-dispatch child frames (parent_id chaining) and surfacing the ids onto the
// catalog log lines are deferred — see request-context.md.
// ---------------------------------------------------------------------------

export function renderRequestContext(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.util.UUID;`,
    ``,
    `import org.slf4j.MDC;`,
    ``,
    `/** Ambient per-request execution context, carried in SLF4J MDC.`,
    ` *  Established at the HTTP edge by ExecutionContextFilter; read elsewhere`,
    ` *  via the static accessors (no request handle needed). */`,
    `public final class RequestContext {`,
    `    public static final String CORRELATION_ID = "correlation_id";`,
    `    public static final String SCOPE_ID = "scope_id";`,
    `    public static final String PARENT_ID = "parent_id";`,
    `    public static final String ACTOR_ID = "actor_id";`,
    `    public static final String LOCALE = "locale";`,
    `    public static final String STARTED_AT = "started_at";`,
    ``,
    `    private RequestContext() {`,
    `    }`,
    ``,
    `    /** The correlation id for the current request, or null outside a request. */`,
    `    public static String correlationId() {`,
    `        return MDC.get(CORRELATION_ID);`,
    `    }`,
    ``,
    `    /** The id of the current execution frame (the root frame for a request). */`,
    `    public static String scopeId() {`,
    `        return MDC.get(SCOPE_ID);`,
    `    }`,
    ``,
    `    /** The parent frame's id, or null at the root frame (no per-dispatch nesting yet). */`,
    `    public static String parentId() {`,
    `        return MDC.get(PARENT_ID);`,
    `    }`,
    ``,
    `    /** The principal's id, or null before auth has run / when the deployable carries no auth. */`,
    `    public static String actorId() {`,
    `        return MDC.get(ACTOR_ID);`,
    `    }`,
    ``,
    `    /** The request locale from Accept-Language, defaulting to "en". */`,
    `    public static String locale() {`,
    `        var value = MDC.get(LOCALE);`,
    `        return value != null ? value : "en";`,
    `    }`,
    ``,
    `    /** Epoch milliseconds at request start, or 0 outside a request. */`,
    `    public static long startedAt() {`,
    `        var value = MDC.get(STARTED_AT);`,
    `        return value != null ? Long.parseLong(value) : 0L;`,
    `    }`,
    ``,
    `    /** Mint a fresh id (correlation / scope). */`,
    `    public static String newId() {`,
    `        return UUID.randomUUID().toString();`,
    `    }`,
    ``,
    `    /** Stamp the actor id after auth resolves the principal — only the id`,
    `     *  rides MDC; the full principal stays on CurrentUserAccessor. */`,
    `    public static void putActorId(String id) {`,
    `        MDC.put(ACTOR_ID, id);`,
    `    }`,
    `}`,
    ``,
  );
}

export function renderExecutionContextFilter(basePkg: string): string {
  return lines(
    `package ${basePkg}.config;`,
    ``,
    `import java.io.IOException;`,
    ``,
    `import org.slf4j.MDC;`,
    `import org.springframework.core.Ordered;`,
    `import org.springframework.core.annotation.Order;`,
    `import org.springframework.stereotype.Component;`,
    `import org.springframework.web.filter.OncePerRequestFilter;`,
    ``,
    `import jakarta.servlet.FilterChain;`,
    `import jakarta.servlet.ServletException;`,
    `import jakarta.servlet.http.HttpServletRequest;`,
    `import jakarta.servlet.http.HttpServletResponse;`,
    ``,
    `/** Opens the ambient RequestContext at the HTTP edge.  Outermost filter`,
    ` *  (HIGHEST_PRECEDENCE) so the request-stable tier + root scope are set`,
    ` *  before any inner filter (auth, catalog) runs, and MDC is cleared once`,
    ` *  on the way out so a pooled thread never leaks context to the next request.`,
    ` *  Named ExecutionContextFilter (not RequestContextFilter) to avoid colliding`,
    ` *  with Spring's auto-configured \`requestContextFilter\` bean. */`,
    `@Component`,
    `@Order(Ordered.HIGHEST_PRECEDENCE)`,
    `public class ExecutionContextFilter extends OncePerRequestFilter {`,
    `    private static final String CORRELATION_HEADER = "X-Correlation-Id";`,
    `    private static final String REQUEST_ID_HEADER = "X-Request-Id";`,
    ``,
    `    @Override`,
    `    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)`,
    `            throws ServletException, IOException {`,
    `        var correlationId = resolveCorrelationId(request);`,
    `        MDC.put(RequestContext.CORRELATION_ID, correlationId);`,
    `        MDC.put(RequestContext.SCOPE_ID, RequestContext.newId());`,
    `        MDC.put(RequestContext.LOCALE, resolveLocale(request));`,
    `        MDC.put(RequestContext.STARTED_AT, String.valueOf(System.currentTimeMillis()));`,
    `        response.setHeader(CORRELATION_HEADER, correlationId);`,
    `        try {`,
    `            chain.doFilter(request, response);`,
    `        } finally {`,
    `            MDC.clear();`,
    `        }`,
    `    }`,
    ``,
    `    // Prefer the cross-backend X-Correlation-Id, then X-Request-Id, else mint.`,
    `    private static String resolveCorrelationId(HttpServletRequest request) {`,
    `        var correlation = request.getHeader(CORRELATION_HEADER);`,
    `        if (correlation != null && !correlation.isEmpty()) {`,
    `            return correlation;`,
    `        }`,
    `        var requestId = request.getHeader(REQUEST_ID_HEADER);`,
    `        if (requestId != null && !requestId.isEmpty()) {`,
    `            return requestId;`,
    `        }`,
    `        return RequestContext.newId();`,
    `    }`,
    ``,
    `    private static String resolveLocale(HttpServletRequest request) {`,
    `        var header = request.getHeader("Accept-Language");`,
    `        return header != null && !header.isEmpty() ? header : "en";`,
    `    }`,
    `}`,
    ``,
  );
}
