// Virtual modules that replace Node-only imports in the generated
// Hono backend.  These are wired into esbuild via the bundler's
// alias plugin: a generated `import "drizzle-orm/node-postgres"`
// resolves here instead of the real npm package, so we can route
// the runtime to PGlite without touching the Loom generator.
//
// Drizzle's query-builder surface is identical between drivers,
// which is what makes the type-only re-aliasing safe.

export const DRIZZLE_PGLITE_SHIM = `// Auto-generated by the bundler.
// Re-routes drizzle-orm/node-postgres → drizzle-orm/pglite so the
// generated repositories run against PGlite in the browser.
export { drizzle } from "drizzle-orm/pglite";
import type { PgliteDatabase } from "drizzle-orm/pglite";
export type NodePgDatabase<T = Record<string, unknown>> = PgliteDatabase<T>;
`;

// The generator-emitted root \`index.ts\` calls
// \`@hono/node-server.serve(...)\` to start a real HTTP server.
// In the browser we never invoke that file (the runtime imports
// \`http/index.ts\` and the SW dispatches Requests through
// \`app.fetch\` directly), but a stub keeps the dep graph honest if
// any other generator path picks it up.
export const HONO_NODE_SERVER_STUB = `// Auto-generated stub.
export function serve(): never {
  throw new Error("@hono/node-server is not available in the browser runtime.");
}
`;

// Same story as @hono/node-server: only \`index.ts\` reaches \`pg\`,
// and we don't bundle that file.
export const PG_STUB = `// Auto-generated stub.
export class Pool {
  constructor() {
    throw new Error("pg.Pool is not available in the browser runtime.");
  }
}
export default { Pool };
`;

// Generated id helpers (\`domain/ids.ts\`) call
// \`randomUUID\` from \`node:crypto\`.  Browsers have an equivalent
// on \`globalThis.crypto\`; this thin shim re-exports it under the
// Node import name so the generated code compiles unchanged.
export const NODE_CRYPTO_SHIM = `// Auto-generated shim for node:crypto.
const g = globalThis;
export function randomUUID(): string {
  if (!g.crypto || typeof g.crypto.randomUUID !== "function") {
    throw new Error("globalThis.crypto.randomUUID is not available");
  }
  return g.crypto.randomUUID();
}
`;

export interface VirtualShim {
  /** Module specifier the source uses, e.g. "drizzle-orm/node-postgres". */
  specifier: string;
  /** Replacement module body (TS or JS). */
  source: string;
  /** Loader esbuild should use. */
  loader: "ts" | "js";
}

export const VIRTUAL_SHIMS: VirtualShim[] = [
  { specifier: "drizzle-orm/node-postgres", source: DRIZZLE_PGLITE_SHIM, loader: "ts" },
  { specifier: "@hono/node-server", source: HONO_NODE_SERVER_STUB, loader: "ts" },
  { specifier: "pg", source: PG_STUB, loader: "ts" },
  { specifier: "node:crypto", source: NODE_CRYPTO_SHIM, loader: "ts" },
];
