// The scaffold gradient in the Builder tab (M-T8.21, audit H6) + the
// accessible-name ratchet over the three visual panes (M13).  Pure
// client-side — no network.
//
// The Sales System's pages come from `ui WebApp with scaffold(...)`, which the
// builder's raw parse never sees: the tab used to open on "No page … found.
// Add a ui { page { … } } block".  Now it lists the scaffolded pages with a
// badge, and **Unfold** ejects one into real source the canvas mounts.
//
// The accessible-name check is a DOM walk rather than `@axe-core/playwright`:
// the rule wanted is exactly `button-name`, the walk is twenty lines, and it
// adds no dependency that would have to download at install time in the
// no-network lane.

import { expect, test, type Page } from "@playwright/test";
import { readEditorSource, selectExample, waitForPlaygroundReady } from "./_helpers";

/** Every `<button>` under `root` that has no accessible name — by the
 *  `button-name` rule's sources: `aria-label`, `aria-labelledby`, text
 *  content (visually-hidden text counts), `title`, an `<img alt>` or an
 *  `<svg><title>` inside.  Returns a short description of each offender so the
 *  failure names the control. */
async function unnamedButtons(page: Page, rootSelector: string): Promise<string[]> {
  return page.evaluate((sel) => {
    const root = document.querySelector(sel);
    if (!root) return [`root not found: ${sel}`];
    const out: string[] = [];
    for (const b of Array.from(root.querySelectorAll("button"))) {
      const label = b.getAttribute("aria-label")?.trim();
      if (label) continue;
      const by = b.getAttribute("aria-labelledby");
      if (by && by.split(/\s+/).some((id) => (document.getElementById(id)?.textContent ?? "").trim())) continue;
      if ((b.textContent ?? "").trim()) continue;
      if (b.getAttribute("title")?.trim()) continue;
      if (b.querySelector("img[alt]:not([alt=''])")) continue;
      if ((b.querySelector("svg title")?.textContent ?? "").trim()) continue;
      out.push(`${b.outerHTML.slice(0, 160)}`);
    }
    return out;
  }, rootSelector);
}

test("Builder lists the Sales System's scaffolded pages; Unfold makes one real and mounts it", async ({ page }) => {
  await page.goto("/");
  await waitForPlaygroundReady(page);
  await selectExample(page, /Sales System \(Hono/);

  await page.getByTestId("doc-tab-builder").click();
  // The scaffolded list comes from an async build of the source.
  const scaffolded = page.getByTestId("c4builder-scaffolded");
  await expect(scaffolded).toBeVisible({ timeout: 30_000 });
  await expect(scaffolded).toContainText("generated by scaffold");
  // The old dead-end copy is gone.
  await expect(page.getByTestId("c4builder-empty")).not.toContainText("Add a ui");

  const row = page.getByTestId("c4builder-scaffold-row-Orders-List");
  await expect(row).toBeVisible();
  await expect(row).toContainText("Orders / List");
  await expect(row).toContainText("scaffolded");
  // Every aggregate gets its three pages; the singleton Home is there too.
  await expect(page.getByTestId("c4builder-scaffold-row-Orders-Detail")).toBeVisible();
  await expect(page.getByTestId("c4builder-scaffold-row-Home")).toBeVisible();

  // Unfold → a real `page List` inside `area Orders` lands in Source …
  await page.getByTestId("c4builder-unfold-Orders-List").click();
  await expect.poll(() => readEditorSource(page), { timeout: 15_000 }).toMatch(/area Orders \{[\s\S]*page List \{/);
  const source = await readEditorSource(page);
  // … while the macro call stays, so the siblings are still generated.
  expect(source).toContain("with scaffold(subdomains: [Sales])");

  // … and the canvas mounts it, selected.
  await expect(page.getByTestId("c4builder-canvas")).toBeVisible({ timeout: 15_000 });
  await expect(page.getByTestId("c4builder-page-select")).toHaveValue("List");
  // The remaining scaffolded pages are still one click away.
  await expect(page.getByTestId("c4builder-scaffold-list")).toBeVisible();
  await expect(page.getByTestId("c4builder-scaffold-list")).not.toContainText("(0)");

  // The write is on the editor's undo stack like any pane edit.
  await page.getByTestId("c4builder-undo").click();
  await expect.poll(() => readEditorSource(page)).not.toContain("page List");
});

test("Add a page: a system with no page at all gets one editable page from the empty state", async ({ page }) => {
  await page.goto("/");
  await waitForPlaygroundReady(page);
  await page.getByTestId("doc-tab-source").click();
  await page.waitForFunction(() => typeof (window as unknown as { __loomSetSource?: unknown }).__loomSetSource === "function");
  await page.evaluate(
    (t) => (window as unknown as { __loomSetSource: (s: string) => void }).__loomSetSource(t),
    "system Bare {\n  subdomain Core {\n    context Things {\n      aggregate Thing {\n        name: string\n      }\n    }\n  }\n}\n",
  );
  await page.getByTestId("doc-tab-builder").click();
  const empty = page.getByTestId("c4builder-no-pages");
  await expect(empty).toBeVisible({ timeout: 15_000 });
  await expect(empty).toContainText("No pages yet");
  await page.getByTestId("c4builder-add-page").click();
  await expect(page.getByTestId("c4builder-canvas")).toBeVisible({ timeout: 15_000 });
  await expect(page.getByTestId("c4builder-page-select")).toHaveValue("Home");
  const source = await readEditorSource(page);
  expect(source).toMatch(/ui \w+ \{[\s\S]*page Home \{/);
});

test("no button in the Builder, Model or Requirements panes lacks an accessible name", async ({ page }) => {
  await page.goto("/");
  await waitForPlaygroundReady(page);
  await selectExample(page, /Sales System \(Hono/);

  // Builder — over the unfolded page, so the chrome, the palette, the
  // settings rail (with a selected node) and the scaffolded-pages popover all
  // render.
  await page.getByTestId("doc-tab-builder").click();
  await expect(page.getByTestId("c4builder-scaffolded")).toBeVisible({ timeout: 30_000 });
  await page.getByTestId("c4builder-unfold-Orders-List").click();
  await expect(page.getByTestId("c4builder-canvas")).toBeVisible({ timeout: 15_000 });
  await page.getByTestId("c4builder-scaffold-list").click();
  await expect(page.getByTestId("c4builder-scaffold-row-Orders-Detail")).toBeVisible();
  await page.keyboard.press("Escape");
  // Select a node so the settings rail renders its Delete / + arm controls.
  await page.locator('[data-testid^="c4node-"]').first().click();
  expect(await unnamedButtons(page, '[data-testid="c4builder-pane"]'), "Builder pane").toEqual([]);
  // The State popover's field rows carry the icon delete buttons.
  const stateToggle = page.getByTestId("c4state-toggle");
  if (await stateToggle.count()) {
    await stateToggle.click();
    expect(await unnamedButtons(page, "body"), "State popover").toEqual([]);
    await page.keyboard.press("Escape");
  }

  // Model — drilled to an aggregate so the per-node rename / delete / ƒx
  // controls and the statement rows are on the canvas.
  await page.getByTestId("doc-tab-model").click();
  await expect(page.getByTestId("c4system-v2-pane")).toBeVisible({ timeout: 10_000 });
  await page.locator('.react-flow__node[data-id^="system:"]').first().click();
  await page.locator('.react-flow__node[data-id^="subdomain:"]').first().click();
  await page.locator('.react-flow__node[data-id^="context:"]').first().click();
  await page.locator('.react-flow__node[data-id="aggregate:Order"]').click();
  await expect(page.locator('.react-flow__node[data-id^="operation:"]').first()).toBeVisible();
  const modelRoot = '[data-testid="c4system-v2-undo-redo"]';
  await expect(page.locator(modelRoot)).toBeVisible();
  expect(
    await page.evaluate((sel) => {
      const pane = document.querySelector(sel)?.closest('[tabindex="-1"]');
      if (!pane) return ["model pane root not found"];
      pane.setAttribute("data-a11y-root", "model");
      return [];
    }, modelRoot),
  ).toEqual([]);
  expect(await unnamedButtons(page, '[data-a11y-root="model"]'), "Model pane (aggregate view)").toEqual([]);
  // The operation flow view has the statement rows (↑ ↓ ×).
  await page.locator('.react-flow__node[data-id^="operation:"]').first().click();
  await expect(page.locator(".react-flow__node[data-stmt-subkind]").first()).toBeVisible({ timeout: 10_000 });
  expect(await unnamedButtons(page, '[data-a11y-root="model"]'), "Model pane (operation view)").toEqual([]);

  // Requirements — the master list and a selected requirement's detail.
  await page.getByTestId("doc-tab-requirements").click();
  await expect(page.getByTestId("req-row-US-001")).toBeVisible({ timeout: 10_000 });
  await page.getByTestId("req-row-US-001").click();
  const reqRoot = '[data-testid="requirements-undo-redo"]';
  expect(
    await page.evaluate((sel) => {
      const pane = document.querySelector(sel)?.closest('[tabindex="-1"]');
      if (!pane) return ["requirements pane root not found"];
      pane.setAttribute("data-a11y-root", "requirements");
      return [];
    }, reqRoot),
  ).toEqual([]);
  expect(await unnamedButtons(page, '[data-a11y-root="requirements"]'), "Requirements pane").toEqual([]);
});
