// ---------------------------------------------------------------------------
// Flutter UI authorization gate (D-AUTH-OIDC) — the Dart/Riverpod sibling of
// `feliz/auth-gate.ts` and of the JS frontends' `useSession()` guard.
//
// Under an `auth: ui` frontend whose target backend is `auth: required`, the
// generated app:
//
//   * probes `GET <api>/auth/me` through a `sessionProvider`
//     (`FutureProvider<CurrentUser?>`), decoding the verified claims into a
//     typed `CurrentUser`;
//   * wraps the whole `MaterialApp` in an `AuthGate` — a spinner while the probe
//     is in flight, a sign-in prompt when there is no session, the real routes
//     once authenticated.  Every page therefore builds with a session in hand,
//     which is why a page shell can bind `…value!`;
//   * renders `ForbiddenView` in place of a gated page's body when its
//     `requires <expr>` predicate fails against those claims (the client mirror
//     of the backend 403), and hides an `Action` button whose operation carries
//     a currentUser-only `requires`.
//
// Sign-in / sign-out are REDIRECTS to the backend's own handshake — Loom owns no
// auth runtime.  Dart's core SDK cannot navigate to an external URL, so this is
// the one place the generated app pulls `url_launcher`; it is pulled ONLY under
// `auth: ui`, exactly as `file_picker` is pulled only by a File field.  On the
// web `webOnlyWindowName: '_self'` makes it a same-tab navigation (what the JS
// frontends do with `window.location.href`); on a native surface it opens the
// system browser, which is where an OIDC code flow belongs — the callback
// returning INTO a native app needs a deep link the generated project does not
// register yet, so native sign-in completes in the browser session.
//
// The gate-expression renderer below is the Dart twin of
// `_frontend/gate-expr.ts` (JS) and `feliz/auth-gate.ts` (F#): the SAME closed
// subset the `requires` validator admits — `currentUser`, constants, boolean /
// comparison operators, `.contains` membership — and anything outside it throws
// rather than degrading silently.  Dart's operators happen to coincide with
// Loom's, so only `.contains` and the enum-member spelling diverge.
// ---------------------------------------------------------------------------

import type { ExprIR, OperationIR, UserIR } from "../../ir/types/loom-ir.js";
import { lines } from "../../util/code-builder.js";
import { type DartRecord, renderDartModel } from "./dart-model-emit.js";

/** The `CurrentUser` claims record, built through the SAME `renderDartModel`
 *  every wire model rides — so a claim's Dart spelling and its `fromJson` are
 *  derived exactly like an aggregate field's, with no second type mapper to
 *  drift. */
function renderCurrentUserClass(user: UserIR): string {
  const record: DartRecord = {
    className: "CurrentUser",
    fields: user.fields.map((f) => ({
      name: f.name,
      type: f.type,
      optional: f.type.kind === "optional",
    })),
  };
  return renderDartModel(record);
}

/** `lib/auth.dart` — the claims record, the session probe, the sign-in/out
 *  redirects, the `AuthGate` wrapper and the `ForbiddenView` fallback. */
export function renderFlutterAuthModule(user: UserIR): string {
  const currentUser = renderCurrentUserClass(user);
  // A claim typed as a value object / entity decodes through a class that lives
  // in `models.dart`.  Detect it the way the rest of this generator decides an
  // import — a content scan over what was actually rendered — so the import can
  // neither dangle nor be missing.  `CurrentUser.fromJson` is its own factory
  // and does not count.
  const needsModels = /\b(?!CurrentUser\b)[A-Z]\w*\.fromJson\(/.test(currentUser);
  return `${lines(
    "// UI authorization gate (D-AUTH-OIDC) — the verified session, the sign-in /",
    "// sign-out handshake with the backend, and the two fallback views a gated app",
    "// renders.  Generated by the Loom Flutter target; do not edit.",
    "",
    "import 'dart:convert';",
    "",
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "import 'package:http/http.dart' as http;",
    "import 'package:url_launcher/url_launcher.dart';",
    "",
    "import 'config.dart';",
    needsModels ? "import 'models.dart';" : undefined,
    "",
    "/// The verified session claims, as declared by the system's `user { … }`",
    "/// block and served by the backend's `/auth/me`.",
    currentUser,
    "",
    "/// The session probe.  `null` means NOT authenticated (a 401, or a body that",
    "/// does not decode) — never an exception, so `AuthGate` always has an answer.",
    "final sessionProvider = FutureProvider<CurrentUser?>((ref) async {",
    "  final res = await http.get(apiUri('/auth/me'));",
    "  if (res.statusCode != 200) return null;",
    "  try {",
    "    return CurrentUser.fromJson(jsonDecode(res.body) as Map<String, dynamic>);",
    "  } catch (_) {",
    "    return null;",
    "  }",
    "});",
    "",
    "/// Loom owns no auth runtime: sign-in and sign-out are REDIRECTS to the",
    "/// backend's own handshake.  `_self` makes it a same-tab navigation on the",
    "/// web; on a native surface it opens the system browser.",
    "Future<void> signIn() => _authRedirect('/auth/login');",
    "",
    "Future<void> signOut() => _authRedirect('/auth/logout');",
    "",
    "Future<void> _authRedirect(String path) async {",
    "  await launchUrl(apiUri(path), webOnlyWindowName: '_self');",
    "}",
    "",
    "/// Gates the whole app on a session: a spinner while the probe is in flight,",
    "/// a sign-in prompt with no session, the real routes once authenticated.  Every",
    "/// page therefore builds with a session in hand.",
    "class AuthGate extends ConsumerWidget {",
    "  const AuthGate({super.key, required this.child});",
    "",
    "  final Widget child;",
    "",
    "  @override",
    "  Widget build(BuildContext context, WidgetRef ref) {",
    "    final session = ref.watch(sessionProvider);",
    "    return session.when(",
    "      loading: () => const Scaffold(body: Center(child: CircularProgressIndicator())),",
    "      error: (error, stack) => const Scaffold(body: Center(child: SignInPrompt())),",
    "      data: (user) =>",
    "          user == null ? const Scaffold(body: Center(child: SignInPrompt())) : child,",
    "    );",
    "  }",
    "}",
    "",
    "/// The unauthenticated prompt — the only affordance an anonymous visitor gets.",
    "class SignInPrompt extends StatelessWidget {",
    "  const SignInPrompt({super.key});",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Column(",
    "      mainAxisSize: MainAxisSize.min,",
    "      children: <Widget>[",
    "        const Text('You are not signed in.'),",
    "        const SizedBox(height: 12),",
    "        ElevatedButton(onPressed: signIn, child: const Text('Sign in')),",
    "      ],",
    "    );",
    "  }",
    "}",
    "",
    "/// The client mirror of the backend's 403 — what a page whose `requires` gate",
    "/// fails renders instead of its body.",
    "class ForbiddenView extends StatelessWidget {",
    "  const ForbiddenView({super.key});",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Card(",
    "      child: Padding(",
    "        padding: const EdgeInsets.all(16),",
    "        child: Column(",
    "          mainAxisSize: MainAxisSize.min,",
    "          crossAxisAlignment: CrossAxisAlignment.start,",
    "          children: <Widget>[",
    "            Text('Forbidden', style: Theme.of(context).textTheme.titleMedium),",
    "            const Text('You do not have access to this page.'),",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
  )}\n`;
}

/** Render a currentUser-only gate `ExprIR` to a Dart boolean expression, with
 *  `userVar` the bound session-user local (`currentUser`).  Throws on any node
 *  outside the gate subset — the Dart sibling of `renderFelizGate` /
 *  `renderGateExpr`.  A gate the UI cannot evaluate is a generation-time error,
 *  never silent degradation. */
export function renderFlutterGate(e: ExprIR, userVar: string): string {
  switch (e.kind) {
    case "ref":
      if (e.refKind === "current-user") return userVar;
      // An enum-typed claim compares against the member's wire value — the bare
      // member name string (`role == Admin` → `currentUser.role == 'Admin'`).
      if (e.refKind === "enum-value") return dartGateString(e.name);
      throw new Error(
        `flutter UI gate: reference '${e.name}' (${e.refKind}) is not evaluable client-side — ` +
          `a gate may only touch currentUser and constants.`,
      );
    case "literal":
      return renderGateLiteral(e.lit, e.value);
    case "member":
      // Claim access — a Dart record keeps the source spelling, so this is the
      // one place the F# sibling diverges (it pascal-cases each hop).
      return `${renderFlutterGate(e.receiver, userVar)}.${e.member}`;
    case "method-call":
      // The only method the gate grammar admits is collection membership.
      if (e.isCollectionOp && e.member === "contains" && e.args.length === 1) {
        return `${renderFlutterGate(e.receiver, userVar)}.contains(${renderFlutterGate(
          e.args[0]!,
          userVar,
        )})`;
      }
      throw new Error(`flutter UI gate: method '.${e.member}' is not supported in a UI gate.`);
    case "binary":
      // Every operator the gate subset admits (`&&`/`||`/`==`/`!=`/comparisons)
      // is spelled identically in Dart.
      return `${renderFlutterGate(e.left, userVar)} ${e.op} ${renderFlutterGate(e.right, userVar)}`;
    case "unary":
      return e.op === "!"
        ? `!(${renderFlutterGate(e.operand, userVar)})`
        : `${e.op}${renderFlutterGate(e.operand, userVar)}`;
    case "paren":
      return `(${renderFlutterGate(e.inner, userVar)})`;
    case "ternary":
      return `(${renderFlutterGate(e.cond, userVar)} ? ${renderFlutterGate(
        e.then,
        userVar,
      )} : ${renderFlutterGate(e.otherwise, userVar)})`;
    default:
      throw new Error(
        `flutter UI gate: expression kind '${e.kind}' is not supported in a UI gate.`,
      );
  }
}

/** The combined Dart gate for an operation's currentUser-only `requires`
 *  guards, or null when the op has no `requires` OR any predicate isn't
 *  client-evaluable (touches `this.<field>` / params — `renderFlutterGate`
 *  throws).  Drives `Action` button gating: a non-null gate hides the button
 *  when the claims fail; null leaves it always shown (the backend 403 still
 *  enforces the guard — defence-in-depth). */
export function opActionGate(op: OperationIR): string | null {
  const gates = op.statements.filter((s) => s.kind === "requires").map((s) => s.expr);
  if (gates.length === 0) return null;
  try {
    return gates.map((g) => `(${renderFlutterGate(g, "currentUser")})`).join(" && ");
  } catch {
    return null;
  }
}

/** A Dart single-quoted string literal for a gate leaf. */
function dartGateString(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$")}'`;
}

function renderGateLiteral(lit: string, value: string): string {
  switch (lit) {
    case "string":
      return dartGateString(value);
    case "bool":
      // Dart bool literals are lowercase `true`/`false` — same spelling.
      return value;
    case "int":
    case "long":
    case "decimal":
      return value;
    default:
      // money / now / null have no meaningful client-side gate form.
      throw new Error(`flutter UI gate: ${lit} literal is not supported in a UI gate.`);
  }
}
