// The Flutter WalkerTarget — Dart/Flutter seam implementations consumed by the
// shared `walkBody` engine.  Flutter is structurally a Feliz clone: a non-JSX,
// function-call-tree target (`Column(children: [ … ])` ≈ Feliz's
// `Html.div [ prop.children [ … ] ]`), so it rides the shared walker core through
// this seam object rather than adding a WALKER_PRIMITIVE.  The primary model is
// `src/generator/feliz/feliz-target.ts`; only the syntax below is Dart, not F#.
//
// WALKING-SKELETON SCOPE (this file): the read/display path — List / Detail
// pages.  Every REQUIRED seam emits real Dart; the expression leaves forward to
// `DART_LEAVES` (`./dart-expr.ts`).  State follows the Riverpod convention: reads
// dereference the projected state record (`state.<field>`), writes call the
// Notifier's generated `set<Field>` method (`notifier.set<Field>(…)`) — emitted
// per state cell by `riverpod-emit.ts`, so the top-level write resolves (a nested
// `a.b.c := v` write still carries a TODO in `renderNestedStateWrite`).  The
// standalone controlled inputs (Field / MultilineField / PasswordField / Toggle /
// SelectField) write through the same setters, bound as a page-shell tear-off.
//
// FORMS (Track B): the three whole-primitive form overrides ship —
// `renderCreateForm` / `renderOperationForm` / `renderDestroyForm` each emit a
// reference to a self-contained `StatefulWidget` (generated by `forms-emit.ts`
// into `lib/forms.dart`) that POSTs/DELETEs over package:http and pops on
// success.  `renderAction` (one-click op button), `renderModal` (a trigger
// button that opens an op-form `AlertDialog`), and `renderWorkflowForm` (a
// `WorkflowForm(runs:)` posting to `/workflows/<wf>`) also ship.  Still DEFERRED
// success.  `renderUserComponent` ships too (a `Foo(...)` call → a Dart widget
// constructor; the component widget is emitted by `component-emit.ts`).
//
// The interactive-table seams (sort header / pager / client filter) and the
// store seams (`renderStoreFieldRead` / `renderStoreActionCall`, over the
// Riverpod store modules `store-builder.ts` emits) now ship too.  What a store
// still does NOT carry here is the lifetime ladder — `persist: local|session|url`
// emits an in-memory store under a visible TODO in `lib/stores.dart`.

import { isConstructible } from "../../ir/enrich/wire-projection.js";
import type { AggregateIR, ExprIR, LiteralKind, TypeIR } from "../../ir/types/loom-ir.js";
import { humanize, lowerFirst, plural, snake, upperFirst } from "../../util/naming.js";
import { localizedNamedValue } from "../_walker/i18n-emit.js";
import type { ApiCallSite, RenderPosition, StateRef, WalkerTarget } from "../_walker/target.js";
import { emitExpr, testidAttr, walk } from "../_walker/walker-core.js";
import {
  DART_LEAVES,
  dartString,
  dartTemporalBinary,
  dartZeroValue,
  FLUTTER_CHILD_PARAM,
  renderDartIntrinsic,
} from "./dart-expr.js";
import {
  createFormWidgetName,
  destroyFormWidgetName,
  operationFormWidgetName,
  workflowFormWidgetName,
} from "./forms-emit.js";
import { dartStringLit } from "./i18n.js";
import { storeProviderName } from "./store-names.js";

/** True when a value is provably a `string` already, so a `Text(…)` child can
 *  take it without the `.toString()` coercion. */
function isStringType(type: TypeIR | undefined): boolean {
  return type?.kind === "primitive" && type.name === "string";
}

/** A dotted attribute / route name → a safe camelCase Dart identifier
 *  (`data-testid` → `dataTestid`).  Keeps a dynamic named-arg binding legal Dart
 *  even when the source name carries hyphens. */
function dartIdent(name: string): string {
  const camel = name.replace(/[^a-zA-Z0-9]+([a-zA-Z0-9])?/g, (_m, c: string | undefined) =>
    c ? c.toUpperCase() : "",
  );
  return lowerFirst(camel);
}

/** A Notifier setter method name for a state field (`step` → `setStep`). */
function setterName(field: string): string {
  return `set${upperFirst(field)}`;
}

/** The named-arg value of a call expression, or undefined. */
function namedArg(call: ExprIR, name: string): ExprIR | undefined {
  if (call.kind !== "call") return undefined;
  const names = call.argNames ?? [];
  const idx = names.indexOf(name);
  return idx >= 0 ? call.args[idx] : undefined;
}

/** The aggregate a form primitive's `of:` arg refers to (a bare aggregate ref),
 *  resolved through the walker's `aggregatesByName`, or undefined. */
function formOfAggregate(
  call: ExprIR,
  ctx: { aggregatesByName: ReadonlyMap<string, AggregateIR> },
): AggregateIR | undefined {
  const ofArg = namedArg(call, "of");
  return ofArg?.kind === "ref" ? ctx.aggregatesByName.get(ofArg.name) : undefined;
}

/** A route template (`/products/:id`) → a Dart string with `:param` segments
 *  interpolated as `${value}` (Dart string interpolation).  Literal segments
 *  pass through verbatim; a `:param` uses the matching named arg's value, else
 *  its bare name. */
function dartRoute(
  routeTemplate: string,
  args: ReadonlyArray<{ name: string; value: string }>,
): string {
  const byName = new Map(args.map((a) => [a.name, a.value]));
  const segs = routeTemplate.split("/").filter((s) => s.length > 0);
  const rendered = segs.map((s) => {
    if (!s.startsWith(":")) return s;
    const name = s.slice(1);
    return `\${${byName.get(name) ?? name}}`;
  });
  return `'/${rendered.join("/")}'`;
}

/** The provider-local var a detected api call resolves to (`Customer` + `all` →
 *  `customerAll`).  Track D wires the matching Riverpod provider; the view only
 *  names the local it reads. */
function apiVarName(aggregateName: string, operation: string): string {
  return `${lowerFirst(aggregateName)}${upperFirst(operation)}`;
}

/** Assemble a guarded Dart-3 `switch` EXPRESSION from predicate arms — the
 *  Flutter analogue of Feliz's `if/elif/else` chain (Dart has no
 *  predicate-arm-without-subject match, so `switch (0) { _ when p => v, … }`
 *  carries the predicates as wildcard guards).  Both value and markup-child
 *  position use it (arm values are already rendered).  With no `else` arm the
 *  terminal is `const SizedBox.shrink()` (renders nothing). */
function dartPredicateSwitch(
  arms: ReadonlyArray<{ predicate: string; value: string }>,
  elseArm: string | undefined,
): string {
  const terminal = `_ => ${elseArm ?? "const SizedBox.shrink()"}`;
  const clauses = arms.map((a) => `_ when ${a.predicate} => ${a.value}`);
  return `switch (0) { ${[...clauses, terminal].join(", ")} }`;
}

export const flutterTarget: WalkerTarget = {
  framework: "flutter",

  // Dart `<Widget>[ … ]` list literals are comma-separated — the shared walker
  // joins container children with `\n<indent>` and no token, so without this the
  // emitted `Column(children: […])` would be a syntax error.
  interChildSeparator: ",",

  // --- State seam — Riverpod projected-state reads + Notifier writes --------
  // Reads dereference the projected immutable state record the view holds
  // (`state.<field>`); the field keeps its source (camelCase) name.
  renderStateRead: (ref: StateRef, _pos: RenderPosition) => `state.${ref.name}`,
  // A `state.<field> := <value>` write inside an event handler calls the
  // Notifier's generated `set<Field>` setter (emitted per state cell by
  // `riverpod-emit.ts`; the page shell binds `notifier`).
  renderStateWrite: (ref: StateRef, value: string) => `notifier.${setterName(ref.name)}(${value})`,
  // A multi-segment write (`order.shipping.zip := v`) → a Notifier update on the
  // root field; the projector fills the immutable rebuild.
  renderNestedStateWrite: (segments: readonly string[], valueJs: string) => {
    const [root, ...rest] = segments;
    const path = rest.length ? `${root}.${rest.join(".")}` : (root ?? "");
    return `notifier.${setterName(root ?? "")}(${valueJs}) /* TODO(flutter): nested write ${path} */`;
  },

  // --- Store seam — a store is its own Riverpod provider (Stage 5) ---------
  // A `store Cart { … }` projects onto the same triad a stateful page does —
  // `CartState` / `CartNotifier` / `cartProvider` in `lib/stores.dart`
  // (`store-builder.ts`).  As on React, the page SHELL hoists one local per used
  // member and the body references the bare name; these seams supply the
  // expression the shell binds and the call form the body emits.
  //
  // Without them `walkBody` THREW on any store reference, so a model that
  // validated clean failed codegen outright — flutter was the last frontend
  // with neither seam.

  /** The selector a field read binds to: a granular `.select` watch, so a page
   *  reading `Cart.count` rebuilds on that cell rather than on any store write
   *  (the Riverpod analogue of React's `useCart((s) => s.count)`). */
  renderStoreFieldRead: (ref: { storeName: string; field: string }) =>
    `ref.watch(${storeProviderName(ref.storeName)}.select((s) => s.${ref.field}))`,
  /** `<Store>.<action>(args)` → the shell-bound tear-off call.  `local` is the
   *  collision-resolved local name walker-core also gave the use site, so the
   *  binding and the call always agree. */
  renderStoreActionCall: (
    ref: { storeName: string; action: string; local: string },
    renderedArgs: string,
  ) => `${ref.local}(${renderedArgs})`,

  // --- API seam — thin Riverpod projection ---------------------------------
  // A detected api call resolves to a provider-local (`customerAll`); the args
  // render through the walker context so param/state refs propagate.
  buildHookUse: (detected, renderArg) => {
    const varName = apiVarName(detected.aggregateName, detected.operation);
    return {
      varName,
      hookName: varName,
      importFrom: `../providers/${lowerFirst(detected.aggregateName)}`,
      argsRendered: detected.args.map(renderArg),
    };
  },
  // The IR call site emits the provider local (the FutureBuilder / `ref.watch`
  // reads it — hoisted below); chained `.data` / `.value` come from the walk.
  renderApiCall: (call: ApiCallSite) =>
    call.varName ?? apiVarName(call.aggregateName, call.operation),
  // The magic route `id` (`Order.byId(id)`) resolves to the local `id` the page
  // shell binds from its route arguments.
  renderRouteId: () => "id",
  // Per-page hoist: one `ref.watch(<var>Provider)` per distinct read, yielding
  // an `AsyncValue<…>` the QueryView widget dispatches on via `.when`.  A
  // parameterised (byId) read watches the matching `.family` provider with its
  // rendered args (`ref.watch(orderByIdProvider(id))`); a paramless list read
  // watches the bare provider.  The provider itself (fetch + `fromJson`) is
  // emitted by `reads-emit.ts`.
  renderApiHoisting: (uses: ApiCallSite[]) => {
    const seen = new Set<string>();
    const lines: string[] = [];
    for (const u of uses) {
      const v = u.varName ?? apiVarName(u.aggregateName, u.operation);
      if (seen.has(v)) continue;
      seen.add(v);
      const args = (u.argsRendered ?? []).join(", ");
      const watch = args ? `${v}Provider(${args})` : `${v}Provider`;
      lines.push(`    final ${v} = ref.watch(${watch});`);
    }
    return lines;
  },
  // A QueryView `data:` lambda param binds to the LOADED value the `.when(data:
  // …)` callback yields — the `AsyncValue`'s var name (`orderAll` / `orderById`)
  // shadowed inside the callback as the unwrapped value.
  //
  // An UNPAGED list provider yields a bare `List<T>`, so the handle is the
  // binding itself.  A PAGED one yields a `LoomPage<T>` (rows + page count), so
  // an auto-paged body — one that binds `rows` and maps over it — takes
  // `.items`; a body that keeps the envelope (the scaffold, which also reads
  // `rows.totalPages` for its pager) keeps the whole page.
  renderQueryDataAccess: (handle: string, _single, _paged, autoPaged) =>
    autoPaged ? `${lowerFirst(handle)}.items` : lowerFirst(handle),
  // A paged read's provider yields `LoomPage<T>`, and the `.when(data: …)`
  // callback always binds that carrier — so EVERY member of the envelope,
  // `items` included, is a field of it.  Named off the read's HANDLE rather
  // than off `binding`: an auto-paged body has already narrowed `binding` to
  // `.items` (see `renderQueryDataAccess` above), and appending `.total` to the
  // row list is exactly the bug this seam exists to avoid.  (The seam only
  // fires on a paged read, so the handle always names the carrier here.)
  renderPagedEnvelopeMember: ({ member, handle }) => `${lowerFirst(handle)}.${member}`,

  /** Dart NAMED RECORD for a find's query bag — `(page: 1, pageSize: 10, …)`.
   *  The shared default is a JavaScript object literal, whose bare `page:` keys
   *  are not Dart identifiers; emitting it verbatim is what made every
   *  server-paged scaffold list fail to compile.  A record is also exactly what
   *  the `.family` provider wants as a key (structural `==`). */
  renderQueryArgsBag: (pairs) => `(${pairs.map((p) => `${p.name}: ${p.value}`).join(", ")})`,

  // --- Table control seams (M-T1.1) — SERVER-DRIVEN ------------------------
  //
  // Flutter's list reads are Riverpod `.family` providers keyed by the query
  // record (`reads-emit.ts`), so sort and page are just STATE WRITES: the key
  // changes, Riverpod refetches, the server does the ordering and windowing.
  // That is the same rationale as the Phoenix/LiveView leg — the topology
  // already hands the work to the server, so re-deriving it client-side would
  // be strictly worse — and unlike the JSX targets there is no client fallback
  // to keep byte-identical, because Flutter never had these controls at all.
  //
  // Every write goes through the Notifier (`renderStateWrite`'s setter), and
  // every read through the projected `state.<field>`, so the page shell's
  // existing bindings are all these need.

  /** Tappable column header driving `sortKey`/`sortDir`.  Re-tapping the ACTIVE
   *  column flips the direction; tapping a new one selects it and resets to
   *  ascending.  The arrow mirrors the JSX targets' `↑`/`↓` indicator, and
   *  `Semantics(sortKey:)` is what makes the affordance announceable — a bare
   *  `InkWell` around text reads as undifferentiated tappable content. */
  renderSortableHeader(spec) {
    const { header, field } = spec;
    const k = `state.${spec.sortKey.name}`;
    const d = `state.${spec.sortDir.name}`;
    const setK = setterName(spec.sortKey.name);
    const setD = setterName(spec.sortDir.name);
    const q = dartString(field);
    const onTap =
      `() { if (${k} == ${q}) { notifier.${setD}(${d} == 'asc' ? 'desc' : 'asc'); } ` +
      `else { notifier.${setK}(${q}); notifier.${setD}('asc'); } }`;
    const arrow =
      `${k} == ${q} ? Icon(${d} == 'asc' ? Icons.arrow_upward : Icons.arrow_downward, size: 16) ` +
      `: const SizedBox.shrink()`;
    return (
      `InkWell(onTap: ${onTap}, child: Semantics(button: true, ` +
      `label: ${spec.sortByLabel ?? dartString(`Sort by ${header}`)}, child: Row(mainAxisSize: MainAxisSize.min, ` +
      `children: <Widget>[Text(${dartString(header)}), ${arrow}])))`
    );
  },

  /** Prev / "Page N of M" / Next, wired to the `page` state field.  Prev
   *  disables on page 1, Next on the last page — a disabled `TextButton` takes
   *  `onPressed: null`, which is also what greys it out. */
  renderPager(spec) {
    const p = `state.${spec.page.name}`;
    const setP = setterName(spec.page.name);
    const total = spec.totalPagesExpr;
    // `const Text('Prev')` only stays const while the label is a literal — a
    // `t(...)` call is not, and Dart rejects `const` over it.  So constness
    // follows the label, which keeps the i18n-off output byte-identical.
    const label = (text: string) =>
      text.startsWith("'") ? `const Text(${text})` : `Text(${text})`;
    // The counter under i18n is one `t()` call whose locale may reorder the two
    // numbers; off, it is the Dart interpolation this target has always emitted.
    const counter = spec.chrome.pageOfValue(p, total) ?? `'Page \${${p}} of \${${total}}'`;
    return (
      `Row(mainAxisAlignment: MainAxisAlignment.end, children: <Widget>[` +
      `TextButton(onPressed: ${p} <= 1 ? null : () => notifier.${setP}(${p} - 1), ` +
      `child: ${label(spec.chrome.prevValue)}), ` +
      `Semantics(liveRegion: true, child: Text(${counter})), ` +
      `TextButton(onPressed: ${p} >= ${total} ? null : () => notifier.${setP}(${p} + 1), ` +
      `child: ${label(spec.chrome.nextValue)})])`
    );
  },

  /** CLIENT-side sort, for a `Table` bound to rows the server did NOT page.
   *
   *  Dart is statically typed, so there is no `row[sortKey]` — the comparator
   *  switches on the key with one arm per `sortable:` column and compares the
   *  typed field.  (This is exactly why `SortedRowsSpec` carries `columns`; the
   *  four JSX targets index at runtime and ignore it.)  `Comparable` covers
   *  String / num / DateTime, which is every sortable scalar the wire carries.
   *  Unknown key → the rows unchanged, matching the JS targets' `if (!key)`. */
  renderSortedRows(spec) {
    const k = `state.${spec.sortKey.name}`;
    const d = `state.${spec.sortDir.name}`;
    if (spec.columns.length === 0) return spec.rowsExpr;
    const arms = spec.columns
      .map((f) => `${dartString(f)} => (a.${f} as Comparable).compareTo(b.${f} as Comparable)`)
      .join(", ");
    return (
      `(List.of(${spec.rowsExpr})..sort((a, b) { final c = switch (${k}) { ${arms}, ` +
      `_ => 0 }; return ${d} == 'desc' ? -c : c; }))`
    );
  },

  /** A `Chart`'s plotted rows.  The shared default is literal JavaScript
   *  (`?? []`, `.map`, an object literal, `Number(...)`), none of which is
   *  Dart; and the per-row projection it builds for the JS chart libraries
   *  buys nothing here, because the pack maps straight into `LoomChartPoint`.
   *  What this seam owns is unwrapping the read: `of:` renders to the Riverpod
   *  `AsyncValue` the page watches, so the chart takes its loaded rows and
   *  paints empty until they arrive — the same "no loading arm" contract the
   *  tsx leg gets from `?? []`. */
  renderChartData({ queryExpr }) {
    return `(${queryExpr}.asData?.value ?? const [])`;
  },

  /** CLIENT-side page window.  The shared default is literal JavaScript
   *  (`.slice(…)`, `Math.max`, `Math.ceil`), which is not Dart — emitting it
   *  produced `Math.max(1, Math.ceil((rows).length / 3))` in a `.dart` file.
   *  `skip`/`take` is the Dart idiom and needs no clamping: both tolerate
   *  running past the end. */
  renderClientPaging(spec) {
    const src = spec.rowsTransformed ? spec.rowsExpr : `(${spec.boundRowsExpr})`;
    const size = spec.pageSize;
    return {
      rowsExpr: `${src}.skip((${spec.pageRead} - 1) * ${size}).take(${size}).toList()`,
      totalPagesExpr: `(((${src}.length - 1) ~/ ${size}) + 1).clamp(1, 1 << 30)`,
    };
  },

  /** The search box above a filterable `Table`.  UNCONTROLLED on purpose: a
   *  `TextEditingController` rebuilt from `state.<field>` on every keystroke is
   *  what makes a Flutter text field jump the caret to position 0, and the
   *  filter never needs to push a value back INTO the box.  So the widget owns
   *  its text and `onChanged` mirrors it into the Notifier, which is what the
   *  rows expression below reads.  Emitting `notifier.` here is also the signal
   *  the page shell greps for to bind that local (`index.ts`). */
  renderFilterInput(filter) {
    const set = setterName(filter.name);
    return (
      `TextField(decoration: const InputDecoration(isDense: true, ` +
      `prefixIcon: Icon(Icons.search), labelText: 'Filter table', hintText: 'Filter…'), ` +
      `onChanged: (value) => notifier.${set}(value))`
    );
  },

  /** Case-insensitive substring filter over the columns the table DISPLAYS.
   *  Dart records have no runtime value enumeration, so — exactly like Feliz's
   *  leg and unlike the four JSX targets' `Object.values(row)` — the searchable
   *  set is `spec.columns` (every column whose accessor resolves to a plain
   *  member).  A table whose columns are all computed has nothing to search, so
   *  the rows pass through untouched rather than filtering to nothing. */
  renderFilteredRows({ rowsExpr, filter, columns }) {
    if (columns.length === 0) return rowsExpr;
    const q = `state.${filter.name}`;
    const vals = columns.map((f) => `row.${f}`).join(", ");
    return (
      `(${rowsExpr}).where((row) { final __q = ${q}.trim().toLowerCase(); ` +
      `return __q.isEmpty || <Object?>[${vals}].any((v) => v != null && ` +
      `v.toString().toLowerCase().contains(__q)); }).toList()`
    );
  },

  /** A `Table` that emitted a filter box and/or a pager alongside the table is
   *  MULTI-ROOT, and every slot the walker puts it in takes exactly one Widget.
   *  Wrap the parts in a `Column` — Dart has no fragment, and adjacent widgets
   *  with no separator are a parse error, not a layout quirk. */
  joinRoots: (parts: readonly string[]) =>
    `Column(crossAxisAlignment: CrossAxisAlignment.start, children: <Widget>[${parts.join(", ")}])`,

  /** The server's page COUNT.  `LoomPage.fromJson` already clamps it to at
   *  least 1, so unlike the JS default (`Math.max(1, …)`) no extra guard is
   *  needed — the clamp lives where the value is decoded, once. */
  renderServerTotalPages: (totalPagesExpr: string) => totalPagesExpr,

  // --- Match expression seam — Dart-3 guarded switch -----------------------
  renderMatch: (arms, elseArm) => dartPredicateSwitch(arms, elseArm),
  renderMatchChild: (arms, elseArm, _depth) => dartPredicateSwitch(arms, elseArm),

  // --- List-comprehension seam — `.map` spread into a widget children list --
  // `For { each: coll, x => <markup> }` → `...coll.map((x) => <widget>)`, spliced
  // into the enclosing children list (Dart's collection spread).  An `empty:` arm
  // folds into a collection-`if`; the index binding is emitted only when used.
  renderForEach: (coll, itemVar, indexVar, _keyExpr, body, _depth, emptyBody) => {
    // Word-boundary match — a substring test would false-positive on a
    // single-letter index (`i`) inside any identifier (`x.id`).  Flutter's
    // `.map` spread emits NO list key (unlike React's keyed Fragment), so the
    // index binding is materialised ONLY when the item BODY reads it — the
    // caller passes `indexVar` itself as `keyExpr`, so testing that would force
    // the indexed form (and an unused `<item>Idx` local) on every `For`.
    const idxRe = new RegExp(`\\b${indexVar}\\b`);
    const usesIndex = idxRe.test(body);
    const mapped = usesIndex
      ? `...${coll}.asMap().entries.map((entry) { final ${indexVar} = entry.key; final ${itemVar} = entry.value; return ${body}; })`
      : `...${coll}.map((${itemVar}) => ${body})`;
    if (emptyBody === undefined) return mapped;
    return `if (${coll}.isEmpty) ${emptyBody} else ${mapped}`;
  },

  // --- Navigation seam — Navigator.pushNamed -------------------------------
  renderNavigate: (routeTemplate, args, stateExpr) => {
    const path = dartRoute(routeTemplate, args);
    if (stateExpr !== undefined) {
      return `Navigator.pushNamed(context, ${path}, arguments: ${stateExpr})`;
    }
    // Args consumed by a `:param` segment are already interpolated into the
    // route; only the LEFTOVER args ride along as a Navigator arguments map.
    const routeParams = new Set(
      routeTemplate
        .split("/")
        .filter((s) => s.startsWith(":"))
        .map((s) => s.slice(1)),
    );
    const extra = args.filter((a) => !routeParams.has(a.name));
    const argMap =
      extra.length > 0
        ? `, arguments: {${extra.map((a) => `${dartString(a.name)}: ${a.value}`).join(", ")}}`
        : "";
    return `Navigator.pushNamed(context, ${path}${argMap})`;
  },
  // `Button(to: "/products")` → the bare navigate call (bound as a statement by
  // `renderEventHandler`).  The dest arg is already rendered.
  renderNavigateExpr: (toArg: string) => `Navigator.pushNamed(context, ${toArg})`,

  // --- Form seams — whole-primitive Dart form widgets (Track B) -------------
  // Each form primitive renders as a reference to a generated `StatefulWidget`
  // (emitted into `lib/forms.dart` by `forms-emit.ts`); the widget owns its own
  // controllers + submit (POST/DELETE over package:http).  The seam only NAMES
  // the widget — the class-name helpers are the single source both sides share,
  // so the reference always resolves.  An unresolvable / non-constructible form
  // returns null → the shared fallback emits a diagnostic comment (never broken
  // Dart), matching how Feliz's seams bail.

  // `CreateForm(of: <Agg>)` → `const CreateAggForm()` (a create form takes no
  // route id, so the widget reference is const-constructible).
  renderCreateForm: (call, ctx) => {
    const agg = formOfAggregate(call, ctx);
    if (!agg || !isConstructible(agg)) return null;
    return `const ${createFormWidgetName(agg.name)}()`;
  },
  // `OperationForm(of: <Agg>, op: <op>)` → `OpAggForm(id: id)` (the op is
  // instance-qualified — it POSTs to `/<coll>/$id/<op>`, so it carries the
  // route id the page shell binds).
  renderOperationForm: (call, ctx) => {
    if (call.kind !== "call") return null;
    const ofArg = namedArg(call, "of");
    const opArg = namedArg(call, "op");
    if (ofArg?.kind !== "ref" || opArg?.kind !== "ref") return null;
    const agg = ctx.aggregatesByName.get(ofArg.name);
    const op = agg?.operations.find((o) => o.name === opArg.name && o.visibility === "public");
    if (!agg || !op) return null;
    ctx.usesRouteId = true;
    return `${operationFormWidgetName(agg.name, op.name)}(id: id)`;
  },
  // `DestroyForm(of: <Agg>)` → `DeleteAggForm(id: id)` (a confirm→DELETE button).
  renderDestroyForm: (call, ctx) => {
    const agg = formOfAggregate(call, ctx);
    if (!agg) return null;
    ctx.usesRouteId = true;
    return `${destroyFormWidgetName(agg.name)}(id: id)`;
  },
  // `Action(<instance>.<op>)` → a one-click `ElevatedButton` that POSTs the
  // instance-qualified op (`/<coll>/${instance.id}/<op>`) — the parameter-less
  // sibling of `OperationForm`.  `instance` is an aggregate-typed var in scope
  // (a QueryView row `p`, a byId record); its `.id` addresses the row.  The
  // page's http/config imports are added by index.ts when the body references
  // `apiUri(` (an Action-only signal).  A parameterised op → a diagnostic
  // comment steering to OperationForm (never broken Dart).  Auth gating
  // (currentUser `requires`) is deferred to the auth-ui slice.
  renderAction: (call, ctx) => {
    if (call.kind !== "call") return null;
    const argNames = call.argNames ?? [];
    const opRef = (call.args ?? []).find((_, i) => !argNames[i]);
    if (opRef?.kind !== "member" || opRef.receiver.kind !== "ref") {
      return flutterTarget.renderComment("Action: first argument must be <instance>.<operation>");
    }
    const aggName = ctx.paramTypes?.get(opRef.receiver.name);
    const agg = aggName ? ctx.aggregatesByName.get(aggName) : undefined;
    const op = agg?.operations.find(
      (o) => o.name === opRef.member && o.visibility === "public" && o.params.length === 0,
    );
    if (!agg || !op) {
      return flutterTarget.renderComment(
        `Action(${opRef.receiver.name}.${opRef.member}): no parameter-less public operation in scope (use OperationForm for an op with parameters)`,
      );
    }
    const coll = snake(plural(agg.name));
    const opPath = snake(op.routeSlug ?? op.name);
    // Address the row by the page's route `id` — on a byId detail page (the only
    // place `paramTypes` resolves the instance) it IS the loaded record's id, and
    // it's always in scope (the shell binds it under `usesRouteId`).  This mirrors
    // Feliz, and sidesteps the QueryView data-param rename (`p` → the provider var).
    ctx.usesRouteId = true;
    const label = humanize(op.name);
    return (
      `ElevatedButton(onPressed: () async { ` +
      `final res = await http.post(apiUri('/${coll}/\${id}/${opPath}')); ` +
      `if (res.statusCode >= 200 && res.statusCode < 300 && context.mounted) { ` +
      `ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(${dartString(`${label} done`)}))); ` +
      `} }, child: Text(${dartString(label)}))`
    );
  },

  // `Modal { trigger: Button("Label"), OperationForm(of: <Agg>, op: <op>) }` →
  // an `ElevatedButton` whose `onPressed` opens an `AlertDialog` wrapping the
  // generated op-form widget (`OpAggForm(id: id)`).  The op-form pops its own
  // route on submit success, which dismisses the dialog — so no extra close
  // wiring is needed.  Only the trigger + `OperationForm(of:, op:)` shape is
  // emitted (the same flat shape `scaffoldOperations(of:)` builds); the
  // state-controlled `open:` shape falls through to the shared `emitModal`,
  // which routes it to this pack's `primitive-modal-controlled` renderer.  The
  // nested op-form widget is emitted into `lib/forms.dart` by
  // `collectFlutterForms` scanning the page body independently of this render.
  renderModal: (call, ctx) => {
    if (call.kind !== "call") return null;
    const argNames = call.argNames ?? [];
    const positionals = (call.args ?? []).filter((_, i) => !argNames[i]);
    const formChild = positionals.find(
      (a): a is Extract<ExprIR, { kind: "call" }> =>
        a.kind === "call" && a.name === "OperationForm",
    );
    const trigger = namedArg(call, "trigger");
    // Not the op-dialog shape → return null so the shared `emitModal` can try
    // the STATE-CONTROLLED one (`Modal { …, open: <state bool> }`), which
    // Flutter now renders through `LoomModalHost`.  Claiming the primitive with
    // a comment here is what made a controlled Modal degrade to `/* … */`,
    // silently dropping the dialog AND its content — and the comment described a
    // shape the author hadn't written.  `emitModal` still emits its own
    // explanatory comment when neither shape matches.
    if (!formChild || trigger?.kind !== "call") return null;
    const ofArg = namedArg(formChild, "of");
    const opArg = namedArg(formChild, "op");
    const agg = ofArg?.kind === "ref" ? ctx.aggregatesByName.get(ofArg.name) : undefined;
    const op =
      opArg?.kind === "ref"
        ? agg?.operations.find((o) => o.name === opArg.name && o.visibility === "public")
        : undefined;
    if (!agg || !op) {
      return flutterTarget.renderComment(
        "Modal: OperationForm child must name of: <Agg> and op: <public op>",
      );
    }
    ctx.usesRouteId = true;
    const widget = operationFormWidgetName(agg.name, op.name);
    // Trigger label — the Button's first positional string literal, else the op.
    const triggerNames = trigger.argNames ?? [];
    const firstPositional = (trigger.args ?? []).find((_, i) => !triggerNames[i]);
    const label =
      firstPositional?.kind === "literal" && firstPositional.lit === "string"
        ? firstPositional.value
        : humanize(op.name);
    // The dialog title: the authored `Modal { title: … }` (already translated —
    // the `modalTitle` catalog slot, D-I18N-ATTR), else the humanized op name,
    // which is what this renderer hardcoded.  `localizedNamedValue` yields a
    // Dart EXPRESSION either way, so it drops straight into `Text(…)`.
    const title =
      localizedNamedValue(call, ctx, "modalTitle", "title") ?? dartString(humanize(op.name));
    return (
      `ElevatedButton(onPressed: () => showDialog(context: context, ` +
      `builder: (dialogContext) => AlertDialog(title: Text(${title}), ` +
      `content: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: ${widget}(id: id))))), ` +
      `child: Text(${dartString(label)}))`
    );
  },

  // `FileLink(<file-ref>)` → a null-guarded, selectable file reference.  The
  // shared primitive hand-builds an HTML `<a href download>` through the markup
  // seams; Dart is not markup, so emitting that put a literal `<a href: …>` in
  // `lib/pages/*.dart` and `flutter analyze` could not even parse the file.
  //
  // A `File` wire field decodes to `FileRef?` (always nullable — `dart-types.ts`),
  // and a property read off a model class is NOT type-promotable in Dart, so the
  // guard has to BIND: a null-check pattern (`final __f?`) does that without
  // naming `FileRef`, which the page files do not import (`models.dart` is
  // reached only transitively, through `reads.dart`).
  //
  // The label is the storage `key` with the download `url` on the tooltip, and
  // it is SELECTABLE rather than tappable: opening a URL from Dart needs
  // `url_launcher`, and a new pub dependency on every generated app — plus a
  // plugin registration on each native surface — is a heavier change than this
  // primitive earns.  A tappable affordance that opens nothing would be worse
  // than one that lets the user copy the link.
  renderFileLink: (call, ctx) => {
    if (call.kind !== "call") return null;
    const argNames = call.argNames ?? [];
    const named = argNames.indexOf("value");
    const arg = named >= 0 ? call.args[named] : (call.args ?? []).find((_, i) => !argNames[i]);
    if (!arg) return null;
    const recv = emitExpr(arg, ctx);
    const link =
      `Tooltip(message: __f.url, child: Row(mainAxisSize: MainAxisSize.min, children: <Widget>[` +
      `const Icon(Icons.attach_file, size: 16), Flexible(child: SelectableText(__f.key))]))`;
    return `(switch (${recv}) { final __f? => ${link}, _ => const Text(${dartString("—")}) })`;
  },

  // `Timeline(of: <entries>)` — the entity audit trail (docs/audit.md), the
  // whole-primitive Dart fork of the shared JSX renderers
  // (`_walker/primitives/timeline.ts`).  `entries` is the surrounding
  // QueryView's `data:` binding for the `history(id)` read — inside the
  // `.when(data: …)` callback it is a NON-nullable `List<AuditEntry>`, so
  // unlike the JSX targets no `?? []` in-flight guard is emitted (against a
  // non-nullable Dart list it would be a `dead_null_aware_expression` analyzer
  // warning, and `flutter analyze` runs with fatal warnings).
  //
  // Semantics mirror the react renderer, entry for entry: a vertical list
  // ordered as served (oldest first); each entry keeps its header even when
  // `changes` is empty ("someone ran `recalc` at 14:02" is information); the
  // timestamp formats through `DateFormat` (`at` decodes to a Dart `DateTime`,
  // and the page's intl import rides the shared `usesIntl` content scan); the
  // actor renders only when recorded (a collection-`if`, the Dart spelling of
  // the JSX `!= null` guard); and each change is one "field: before → after"
  // row with `—` standing in for the null side (a create has no before, a
  // destroy no after).  Entries key by `auditId` and rows need no key (a plain
  // `.map` spread) — the same identity the JSX targets use.  The lambda params
  // are `e`/`c` rather than the JSX targets' `__e`/`__c`: Dart's
  // `no_leading_underscores_for_local_identifiers` lint (in flutter_lints)
  // flags the underscore form, and `flutter analyze` runs with fatal infos.
  renderTimeline: (call, ctx) => {
    if (call.kind !== "call") return null;
    const argNames = call.argNames ?? [];
    const ofIdx = argNames.indexOf("of");
    const entriesArg =
      (ofIdx >= 0 ? call.args[ofIdx] : undefined) ?? (call.args ?? []).find((_, i) => !argNames[i]);
    if (!entriesArg) return null; // → the shared "Timeline: missing entries" comment
    const entries = emitExpr(entriesArg, ctx);
    // The `testid:` slot → a widget `Key`, the same translation the pack's
    // `testidKey` applies (the walker hands the static form ` data-testid="x"`).
    const tid = testidAttr(call, ctx)
      .trim()
      .match(/^data-testid="(.*)"$/);
    const key = tid ? `key: const Key('${tid[1]}'), ` : "";
    const changeRow = "Text('${c.field}: ${c.before ?? '—'} → ${c.after ?? '—'}')";
    const entry =
      `Padding(key: ValueKey(e.auditId), padding: const EdgeInsets.symmetric(vertical: 8), ` +
      `child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: <Widget>[` +
      `Text(e.action, style: const TextStyle(fontWeight: FontWeight.bold)), ` +
      `Text(DateFormat.yMMMd().add_jm().format(e.at), style: Theme.of(context).textTheme.bodySmall), ` +
      "if (e.actor != null) Text('${e.actor}'), " +
      `...e.changes.map((c) => ${changeRow})]))`;
    return (
      `Column(${key}crossAxisAlignment: CrossAxisAlignment.start, ` +
      `children: <Widget>[...${entries}.map((e) => ${entry})])`
    );
  },

  // `WorkflowForm(runs: <wf>)` → `const <Wf>WorkflowForm()` — a self-contained
  // form that POSTs the workflow params to `/workflows/<wf>` (a create form over
  // the command route).  The widget class is emitted into `lib/forms.dart` by
  // `collectFlutterWorkflowForms`; the seam only names it.  Falls to null (→
  // shared diagnostic comment) when `runs:` isn't a ref to a reachable workflow.
  renderWorkflowForm: (call, ctx) => {
    const runsArg = namedArg(call, "runs");
    const wf = runsArg?.kind === "ref" ? ctx.workflowsByName.get(runsArg.name) : undefined;
    if (!wf) return null;
    return `const ${workflowFormWidgetName(wf.name)}()`;
  },

  // A user-component invocation (`InfoBox(label: "hi", count: 3)`) → a Dart
  // widget constructor call `InfoBox(label: 'hi', count: 3)`.  Positional args
  // map to the component's declared params by position; named args by name (the
  // Angular precedent).  The component widget class is emitted by index.ts from
  // `ctx.userComponents`; the seam only NAMES it (returns null → the shared
  // "unknown component" comment when the name isn't a threaded component, e.g. a
  // stateful / extern one this slice defers).
  renderUserComponent: (call, ctx) => {
    if (call.kind !== "call") return null;
    const params = ctx.userComponents.get(call.name);
    if (!params) return null;
    ctx.usedUserComponents.add(call.name);
    const argNames = call.argNames ?? [];
    const filledByName = new Set(argNames.filter((n): n is string => n !== undefined));
    const entries: string[] = [];
    const children: ExprIR[] = [];
    let cursor = 0;
    for (let i = 0; i < call.args.length; i++) {
      const arg = call.args[i]!;
      const named = argNames[i];
      let paramName: string | undefined;
      if (named !== undefined) {
        paramName = named;
      } else {
        while (cursor < params.length && filledByName.has(params[cursor]!.name)) cursor += 1;
        paramName = params[cursor]?.name;
        if (paramName !== undefined) cursor += 1;
      }
      if (paramName === undefined) {
        // Past the declared params — a positional arg here is a CHILD, exactly
        // as it is on the JSX path (`emitUserComponent` wraps the extras between
        // the tags).  These were silently DROPPED: the widget rendered its
        // `Slot { }` and the caller's markup never arrived.
        children.push(arg);
        continue;
      }
      entries.push(`${paramName}: ${emitExpr(arg, ctx)}`);
    }
    if (children.length > 0) {
      // Children are MARKUP, so they walk (not `emitExpr`), in the CALLER's
      // scope.  The constructor takes ONE `Widget? child`, so several children
      // fold into a min-height Column — the same container the walker gives a
      // `Stack`, sized to its contents so it can sit anywhere the single child
      // could.
      const walked = children.map((c) => walk(c, ctx, 0).trim());
      const value =
        walked.length === 1
          ? walked[0]!
          : `Column(mainAxisSize: MainAxisSize.min, children: <Widget>[${walked.join(", ")}])`;
      entries.push(`${FLUTTER_CHILD_PARAM}: ${value}`);
    }
    return `${call.name}(${entries.join(", ")})`;
  },

  /** A component body's `Slot { }` → the widget's optional `child` constructor
   *  param (`component-emit.ts` declares it when the walk reports
   *  `usesChildren`), with a zero-size fallback for a call site that passed
   *  none.  The JSX `{children}` default is a Dart SET literal over an unbound
   *  name — it does not compile, and inside a `<Widget>[…]` list it is not even
   *  the right type. */
  renderChildrenSlot: () => `(${FLUTTER_CHILD_PARAM} ?? const SizedBox.shrink())`,

  // --- Type-default seam ---------------------------------------------------
  defaultInitFor: (type) => dartZeroValue(type),

  // --- Markup seams — Dart/Flutter flavoured -------------------------------
  // A diagnostic sentinel has to be a valid Dart EXPRESSION, not a bare
  // comment: every place the walker emits one is a child slot, and Flutter's
  // children are COMMA-SEPARATED list elements (`interChildSeparator`), so
  // `<Widget>[ /* … */, ]` is a parse error — "Expected an identifier".  A
  // zero-size widget carries the same diagnostic while keeping the file
  // compilable, which is the whole point of a sentinel: it must survive to be
  // read.  (A scaffolded detail page hit exactly this and would not build.)
  renderComment: (text: string) => `const SizedBox.shrink() /* ${text} */`,
  // A VISIBLE degradation notice.  `renderComment` above renders NOTHING on the
  // page (a zero-size widget), which is right for a missing widget and wrong
  // for a missing SECTION: the scaffolded History card keeps its frame and its
  // heading, so the reader gets a labelled empty panel.  `Text(…)` is the same
  // widget every other text node in this target emits.
  renderNotice: (text: string) => `Text(${dartString(text)})`,
  // Child-position interpolation → a `Text(…)` widget.  A provably-string value
  // is passed straight; anything else is coerced via Dart string interpolation
  // (`Text('${expr}')`), which stringifies any type.
  renderInterpolation: (jsExpr: string, exprType?: TypeIR) =>
    isStringType(exprType) ? `Text(${jsExpr})` : `Text('\${${jsExpr}}')`,
  // A dynamic attribute → a named widget argument (leading space, camelCased
  // name so a hyphenated source attr stays a legal Dart identifier).
  renderAttrBinding: (name: string, jsExpr: string) => ` ${dartIdent(name)}: ${jsExpr}`,
  // A Dart string literal — how a user-visible string reaching the pack as a
  // VALUE (`localizedNamedValue`, D-I18N-ATTR) is spelled with i18n off.
  // The same single-quoted escaping the translation runtime uses for its keys.
  renderStringLiteral: dartStringLit,
  // A holed message as ONE Dart string with `${…}` interpolation, not a `+`
  // chain — that is how Dart spells this, and how the sortable header's
  // `'Sort by $header'` was already written.
  renderStringConcat: (parts) =>
    `'${parts
      .map((p) =>
        "expr" in p
          ? `\${${p.expr}}`
          : p.text.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$"),
      )
      .join("")}'`,

  // A call into the generated Dart translation runtime (M-T1.11).  The JS
  // frontends' `t(key, default, { name: expr })` is close but not Dart — the
  // values bag is a typed map literal, and the strings are single-quoted with
  // Dart's escapes.  The key, the source default and the hole values are shared
  // verbatim, so the catalog entry is identical on every frontend.
  renderTranslate: ({ key, message, values }) => {
    const args = [dartStringLit(key), dartStringLit(message)];
    if (values && values.length > 0) {
      const pairs = values.map((v) => `${dartStringLit(v.name)}: ${v.expr}`).join(", ");
      args.push(`<String, Object>{${pairs}}`);
    }
    return `t(${args.join(", ")})`;
  },
  // A conditional child → a ternary over two widgets (a single child expression,
  // valid anywhere a widget is expected).
  renderConditionalChild: (cond, thenS, elseS, _depth) => `(${cond} ? ${thenS} : ${elseS})`,
  // Flutter has no CSS `style` attribute — styling is per-widget.  Empty, like
  // Feliz.
  renderStyleAttr: () => "",
  // Raw text for a Dart single-quoted string body (the pack wraps it in
  // `Text('…')`): escape the backslash, the quote, `$`, and the newline.
  escapeText: (text: string) =>
    text.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$").replace(/\n/g, "\\n"),

  // --- Handler seams — Dart closures ---------------------------------------
  // A button's `onPressed:` binds a `VoidCallback`.  The expression form is an
  // arrow; the block form a brace body (each stmt already `;`-terminated).
  renderEventHandler: (stmts, expr) => {
    if (expr !== undefined) return `() => ${expr}`;
    const body = (stmts ?? []).join(" ");
    return `() { ${body} }`;
  },
  // A named `action` → a local closure at the widget-build top; the body reuses
  // the shared `:=`/`+=` statement lowering (Notifier writes).
  renderNamedHandler: (name, param, bodyStmts) => {
    const body = bodyStmts.join(" ");
    const sig = param ? `void ${name}(dynamic ${param})` : `void ${name}()`;
    return `    ${sig} { ${body} }`;
  },

  // --- Expression-syntax leaves (Dart) — forwarded to the shared table ------
  exprLiteral: (lit: LiteralKind, value: string) => DART_LEAVES.literal(lit, value),
  exprBinary: (left, right, op) => DART_LEAVES.binary(left, right, op),
  exprUnary: (op, operand) => DART_LEAVES.unary(op, operand),
  exprTernary: (cond, then, otherwise) => DART_LEAVES.ternary(cond, then, otherwise),
  exprConvert: (value, target, from) => DART_LEAVES.convert(value, target, from),
  exprList: (elements) => DART_LEAVES.list(elements),
  exprObject: (fields) => DART_LEAVES.object(fields),
  // A duration is a Dart `Duration`, not the JS frontends' millisecond number —
  // and Dart's `DateTime` has no arithmetic operators, so `until + days(7)` is
  // `.add(...)`.  Both are the same shared table `riverpod-emit.ts`'s Notifier
  // bodies reach, since Flutter has ONE dispatcher (the shared `emitExpr`).
  exprDuration: (unit, amount) => DART_LEAVES.duration(unit, amount),
  exprTemporalBinary: (left, right, e) => dartTemporalBinary(left, right, e),

  // Scalar intrinsics — the ONE table both the page-view walk and the
  // Notifier/action-body walk consume (both route through the shared
  // `emitExpr`), so `s.replace(a, b)` cannot mean one thing in a page body
  // and another in an action.  Before this seam was supplied, EITHER path
  // fell through to `emitExpr`'s verbatim `recv.member(args)` — Loom's own
  // spelling, which is not Dart.
  renderIntrinsic: (receiverType, member, recv, args) =>
    renderDartIntrinsic(receiverType, member, recv, args),
};
