// The Flutter WalkerTarget — Dart/Flutter seam implementations consumed by the
// shared `walkBody` engine.  Flutter is structurally a Feliz clone: a non-JSX,
// function-call-tree target (`Column(children: [ … ])` ≈ Feliz's
// `Html.div [ prop.children [ … ] ]`), so it rides the shared walker core through
// this seam object rather than adding a WALKER_PRIMITIVE.  The primary model is
// `src/generator/feliz/feliz-target.ts`; only the syntax below is Dart, not F#.
//
// WALKING-SKELETON SCOPE (this file): the read/display path — List / Detail
// pages.  Every REQUIRED seam emits real Dart; the expression leaves forward to
// `DART_LEAVES` (`./dart-expr.ts`).  State follows the Riverpod convention: reads
// dereference the projected state record (`state.<field>`), writes call a
// Notifier method (`notifier.set<Field>(…)`) — the Riverpod projector (Track D)
// binds the actual notifier, so the intent is emitted consistently with a
// `TODO(flutter): notifier` marker where the binding lands.
//
// FORMS (Track B): the three whole-primitive form overrides ship —
// `renderCreateForm` / `renderOperationForm` / `renderDestroyForm` each emit a
// reference to a self-contained `StatefulWidget` (generated by `forms-emit.ts`
// into `lib/forms.dart`) that POSTs/DELETEs over package:http and pops on
// success.  `renderAction` (one-click op button) and `renderModal` (a trigger
// button that opens an op-form `AlertDialog`) also ship.  Still DEFERRED to full
// parity (omitted → they fall back to the shared diagnostic-comment path):
// `renderWorkflowForm` / `renderUserComponent` and the interactive-table / store
// seams.

import { isConstructible } from "../../ir/enrich/wire-projection.js";
import type { AggregateIR, ExprIR, LiteralKind, TypeIR } from "../../ir/types/loom-ir.js";
import { humanize, lowerFirst, plural, snake, upperFirst } from "../../util/naming.js";
import type { ApiCallSite, RenderPosition, StateRef, WalkerTarget } from "../_walker/target.js";
import { DART_LEAVES, dartString, dartZeroValue } from "./dart-expr.js";
import {
  createFormWidgetName,
  destroyFormWidgetName,
  operationFormWidgetName,
} from "./forms-emit.js";

/** True when a value is provably a `string` already, so a `Text(…)` child can
 *  take it without the `.toString()` coercion. */
function isStringType(type: TypeIR | undefined): boolean {
  return type?.kind === "primitive" && type.name === "string";
}

/** A dotted attribute / route name → a safe camelCase Dart identifier
 *  (`data-testid` → `dataTestid`).  Keeps a dynamic named-arg binding legal Dart
 *  even when the source name carries hyphens. */
function dartIdent(name: string): string {
  const camel = name.replace(/[^a-zA-Z0-9]+([a-zA-Z0-9])?/g, (_m, c: string | undefined) =>
    c ? c.toUpperCase() : "",
  );
  return lowerFirst(camel);
}

/** A Notifier setter method name for a state field (`step` → `setStep`). */
function setterName(field: string): string {
  return `set${upperFirst(field)}`;
}

/** The named-arg value of a call expression, or undefined. */
function namedArg(call: ExprIR, name: string): ExprIR | undefined {
  if (call.kind !== "call") return undefined;
  const names = call.argNames ?? [];
  const idx = names.indexOf(name);
  return idx >= 0 ? call.args[idx] : undefined;
}

/** The aggregate a form primitive's `of:` arg refers to (a bare aggregate ref),
 *  resolved through the walker's `aggregatesByName`, or undefined. */
function formOfAggregate(
  call: ExprIR,
  ctx: { aggregatesByName: ReadonlyMap<string, AggregateIR> },
): AggregateIR | undefined {
  const ofArg = namedArg(call, "of");
  return ofArg?.kind === "ref" ? ctx.aggregatesByName.get(ofArg.name) : undefined;
}

/** A route template (`/products/:id`) → a Dart string with `:param` segments
 *  interpolated as `${value}` (Dart string interpolation).  Literal segments
 *  pass through verbatim; a `:param` uses the matching named arg's value, else
 *  its bare name. */
function dartRoute(
  routeTemplate: string,
  args: ReadonlyArray<{ name: string; value: string }>,
): string {
  const byName = new Map(args.map((a) => [a.name, a.value]));
  const segs = routeTemplate.split("/").filter((s) => s.length > 0);
  const rendered = segs.map((s) => {
    if (!s.startsWith(":")) return s;
    const name = s.slice(1);
    return `\${${byName.get(name) ?? name}}`;
  });
  return `'/${rendered.join("/")}'`;
}

/** The provider-local var a detected api call resolves to (`Customer` + `all` →
 *  `customerAll`).  Track D wires the matching Riverpod provider; the view only
 *  names the local it reads. */
function apiVarName(aggregateName: string, operation: string): string {
  return `${lowerFirst(aggregateName)}${upperFirst(operation)}`;
}

/** Assemble a guarded Dart-3 `switch` EXPRESSION from predicate arms — the
 *  Flutter analogue of Feliz's `if/elif/else` chain (Dart has no
 *  predicate-arm-without-subject match, so `switch (0) { _ when p => v, … }`
 *  carries the predicates as wildcard guards).  Both value and markup-child
 *  position use it (arm values are already rendered).  With no `else` arm the
 *  terminal is `const SizedBox.shrink()` (renders nothing). */
function dartPredicateSwitch(
  arms: ReadonlyArray<{ predicate: string; value: string }>,
  elseArm: string | undefined,
): string {
  const terminal = `_ => ${elseArm ?? "const SizedBox.shrink()"}`;
  const clauses = arms.map((a) => `_ when ${a.predicate} => ${a.value}`);
  return `switch (0) { ${[...clauses, terminal].join(", ")} }`;
}

export const flutterTarget: WalkerTarget = {
  framework: "flutter",

  // Dart `<Widget>[ … ]` list literals are comma-separated — the shared walker
  // joins container children with `\n<indent>` and no token, so without this the
  // emitted `Column(children: […])` would be a syntax error.
  interChildSeparator: ",",

  // --- State seam — Riverpod projected-state reads + Notifier writes --------
  // Reads dereference the projected immutable state record the view holds
  // (`state.<field>`); the field keeps its source (camelCase) name.
  renderStateRead: (ref: StateRef, _pos: RenderPosition) => `state.${ref.name}`,
  // A `state.<field> := <value>` write inside an event handler calls the
  // Notifier's generated setter.  The projector (Track D) binds `notifier`; the
  // TODO marks where that binding lands.
  renderStateWrite: (ref: StateRef, value: string) =>
    `notifier.${setterName(ref.name)}(${value}) /* TODO(flutter): notifier */`,
  // A multi-segment write (`order.shipping.zip := v`) → a Notifier update on the
  // root field; the projector fills the immutable rebuild.
  renderNestedStateWrite: (segments: readonly string[], valueJs: string) => {
    const [root, ...rest] = segments;
    const path = rest.length ? `${root}.${rest.join(".")}` : (root ?? "");
    return `notifier.${setterName(root ?? "")}(${valueJs}) /* TODO(flutter): nested write ${path} */`;
  },

  // --- API seam — thin Riverpod projection ---------------------------------
  // A detected api call resolves to a provider-local (`customerAll`); the args
  // render through the walker context so param/state refs propagate.
  buildHookUse: (detected, renderArg) => {
    const varName = apiVarName(detected.aggregateName, detected.operation);
    return {
      varName,
      hookName: varName,
      importFrom: `../providers/${lowerFirst(detected.aggregateName)}`,
      argsRendered: detected.args.map(renderArg),
    };
  },
  // The IR call site emits the provider local (the FutureBuilder / `ref.watch`
  // reads it — hoisted below); chained `.data` / `.value` come from the walk.
  renderApiCall: (call: ApiCallSite) =>
    call.varName ?? apiVarName(call.aggregateName, call.operation),
  // The magic route `id` (`Order.byId(id)`) resolves to the local `id` the page
  // shell binds from its route arguments.
  renderRouteId: () => "id",
  // Per-page hoist: one `ref.watch(<var>Provider)` per distinct read, yielding
  // an `AsyncValue<…>` the QueryView widget dispatches on via `.when`.  A
  // parameterised (byId) read watches the matching `.family` provider with its
  // rendered args (`ref.watch(orderByIdProvider(id))`); a paramless list read
  // watches the bare provider.  The provider itself (fetch + `fromJson`) is
  // emitted by `reads-emit.ts`.
  renderApiHoisting: (uses: ApiCallSite[]) => {
    const seen = new Set<string>();
    const lines: string[] = [];
    for (const u of uses) {
      const v = u.varName ?? apiVarName(u.aggregateName, u.operation);
      if (seen.has(v)) continue;
      seen.add(v);
      const args = (u.argsRendered ?? []).join(", ");
      const watch = args ? `${v}Provider(${args})` : `${v}Provider`;
      lines.push(`    final ${v} = ref.watch(${watch});`);
    }
    return lines;
  },
  // A QueryView `data:` lambda param binds to the LOADED value the `.when(data:
  // …)` callback yields — the `AsyncValue`'s var name (`orderAll` / `orderById`)
  // shadowed inside the callback as the unwrapped `List<T>` / `T?`.  So the
  // handle dereferences to that bare binding (no `.data` envelope), mirroring
  // Feliz's match-arm binding.  The list provider already unwraps the paged
  // `{items,…}` envelope to a `List<T>` (see `pagedDataIsList`), so `paged` /
  // `autoPaged` are no-ops here.
  renderQueryDataAccess: (handle: string) => lowerFirst(handle),
  // The Flutter read provider decodes the paged `.all` envelope straight to a
  // `List<T>` (pulls `items` out), so the binding IS the array — the scaffold's
  // `rows.items` unwrap is a no-op the shared member walk strips (as on Feliz).
  pagedDataIsList: true,

  // --- Match expression seam — Dart-3 guarded switch -----------------------
  renderMatch: (arms, elseArm) => dartPredicateSwitch(arms, elseArm),
  renderMatchChild: (arms, elseArm, _depth) => dartPredicateSwitch(arms, elseArm),

  // --- List-comprehension seam — `.map` spread into a widget children list --
  // `For { each: coll, x => <markup> }` → `...coll.map((x) => <widget>)`, spliced
  // into the enclosing children list (Dart's collection spread).  An `empty:` arm
  // folds into a collection-`if`; the index binding is emitted only when used.
  renderForEach: (coll, itemVar, indexVar, _keyExpr, body, _depth, emptyBody) => {
    // Word-boundary match — a substring test would false-positive on a
    // single-letter index (`i`) inside any identifier (`x.id`).  Flutter's
    // `.map` spread emits NO list key (unlike React's keyed Fragment), so the
    // index binding is materialised ONLY when the item BODY reads it — the
    // caller passes `indexVar` itself as `keyExpr`, so testing that would force
    // the indexed form (and an unused `<item>Idx` local) on every `For`.
    const idxRe = new RegExp(`\\b${indexVar}\\b`);
    const usesIndex = idxRe.test(body);
    const mapped = usesIndex
      ? `...${coll}.asMap().entries.map((entry) { final ${indexVar} = entry.key; final ${itemVar} = entry.value; return ${body}; })`
      : `...${coll}.map((${itemVar}) => ${body})`;
    if (emptyBody === undefined) return mapped;
    return `if (${coll}.isEmpty) ${emptyBody} else ${mapped}`;
  },

  // --- Navigation seam — Navigator.pushNamed -------------------------------
  renderNavigate: (routeTemplate, args, stateExpr) => {
    const path = dartRoute(routeTemplate, args);
    if (stateExpr !== undefined) {
      return `Navigator.pushNamed(context, ${path}, arguments: ${stateExpr})`;
    }
    // Args consumed by a `:param` segment are already interpolated into the
    // route; only the LEFTOVER args ride along as a Navigator arguments map.
    const routeParams = new Set(
      routeTemplate
        .split("/")
        .filter((s) => s.startsWith(":"))
        .map((s) => s.slice(1)),
    );
    const extra = args.filter((a) => !routeParams.has(a.name));
    const argMap =
      extra.length > 0
        ? `, arguments: {${extra.map((a) => `${dartString(a.name)}: ${a.value}`).join(", ")}}`
        : "";
    return `Navigator.pushNamed(context, ${path}${argMap})`;
  },
  // `Button(to: "/products")` → the bare navigate call (bound as a statement by
  // `renderEventHandler`).  The dest arg is already rendered.
  renderNavigateExpr: (toArg: string) => `Navigator.pushNamed(context, ${toArg})`,

  // --- Form seams — whole-primitive Dart form widgets (Track B) -------------
  // Each form primitive renders as a reference to a generated `StatefulWidget`
  // (emitted into `lib/forms.dart` by `forms-emit.ts`); the widget owns its own
  // controllers + submit (POST/DELETE over package:http).  The seam only NAMES
  // the widget — the class-name helpers are the single source both sides share,
  // so the reference always resolves.  An unresolvable / non-constructible form
  // returns null → the shared fallback emits a diagnostic comment (never broken
  // Dart), matching how Feliz's seams bail.

  // `CreateForm(of: <Agg>)` → `const CreateAggForm()` (a create form takes no
  // route id, so the widget reference is const-constructible).
  renderCreateForm: (call, ctx) => {
    const agg = formOfAggregate(call, ctx);
    if (!agg || !isConstructible(agg)) return null;
    return `const ${createFormWidgetName(agg.name)}()`;
  },
  // `OperationForm(of: <Agg>, op: <op>)` → `OpAggForm(id: id)` (the op is
  // instance-qualified — it POSTs to `/<coll>/$id/<op>`, so it carries the
  // route id the page shell binds).
  renderOperationForm: (call, ctx) => {
    if (call.kind !== "call") return null;
    const ofArg = namedArg(call, "of");
    const opArg = namedArg(call, "op");
    if (ofArg?.kind !== "ref" || opArg?.kind !== "ref") return null;
    const agg = ctx.aggregatesByName.get(ofArg.name);
    const op = agg?.operations.find((o) => o.name === opArg.name && o.visibility === "public");
    if (!agg || !op) return null;
    ctx.usesRouteId = true;
    return `${operationFormWidgetName(agg.name, op.name)}(id: id)`;
  },
  // `DestroyForm(of: <Agg>)` → `DeleteAggForm(id: id)` (a confirm→DELETE button).
  renderDestroyForm: (call, ctx) => {
    const agg = formOfAggregate(call, ctx);
    if (!agg) return null;
    ctx.usesRouteId = true;
    return `${destroyFormWidgetName(agg.name)}(id: id)`;
  },
  // `Action(<instance>.<op>)` → a one-click `ElevatedButton` that POSTs the
  // instance-qualified op (`/<coll>/${instance.id}/<op>`) — the parameter-less
  // sibling of `OperationForm`.  `instance` is an aggregate-typed var in scope
  // (a QueryView row `p`, a byId record); its `.id` addresses the row.  The
  // page's http/config imports are added by index.ts when the body references
  // `apiUri(` (an Action-only signal).  A parameterised op → a diagnostic
  // comment steering to OperationForm (never broken Dart).  Auth gating
  // (currentUser `requires`) is deferred to the auth-ui slice.
  renderAction: (call, ctx) => {
    if (call.kind !== "call") return null;
    const argNames = call.argNames ?? [];
    const opRef = (call.args ?? []).find((_, i) => !argNames[i]);
    if (opRef?.kind !== "member" || opRef.receiver.kind !== "ref") {
      return flutterTarget.renderComment("Action: first argument must be <instance>.<operation>");
    }
    const aggName = ctx.paramTypes?.get(opRef.receiver.name);
    const agg = aggName ? ctx.aggregatesByName.get(aggName) : undefined;
    const op = agg?.operations.find(
      (o) => o.name === opRef.member && o.visibility === "public" && o.params.length === 0,
    );
    if (!agg || !op) {
      return flutterTarget.renderComment(
        `Action(${opRef.receiver.name}.${opRef.member}): no parameter-less public operation in scope (use OperationForm for an op with parameters)`,
      );
    }
    const coll = snake(plural(agg.name));
    const opPath = snake(op.routeSlug ?? op.name);
    // Address the row by the page's route `id` — on a byId detail page (the only
    // place `paramTypes` resolves the instance) it IS the loaded record's id, and
    // it's always in scope (the shell binds it under `usesRouteId`).  This mirrors
    // Feliz, and sidesteps the QueryView data-param rename (`p` → the provider var).
    ctx.usesRouteId = true;
    const label = humanize(op.name);
    return (
      `ElevatedButton(onPressed: () async { ` +
      `final res = await http.post(apiUri('/${coll}/\${id}/${opPath}')); ` +
      `if (res.statusCode >= 200 && res.statusCode < 300 && context.mounted) { ` +
      `ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(${dartString(`${label} done`)}))); ` +
      `} }, child: Text(${dartString(label)}))`
    );
  },

  // `Modal { trigger: Button("Label"), OperationForm(of: <Agg>, op: <op>) }` →
  // an `ElevatedButton` whose `onPressed` opens an `AlertDialog` wrapping the
  // generated op-form widget (`OpAggForm(id: id)`).  The op-form pops its own
  // route on submit success, which dismisses the dialog — so no extra close
  // wiring is needed.  Only the trigger + `OperationForm(of:, op:)` shape is
  // emitted (the same flat shape `scaffoldOperations(of:)` builds); the
  // state-controlled `open:` shape falls to a diagnostic comment (never broken
  // Dart).  The nested op-form widget is emitted into `lib/forms.dart` by
  // `collectFlutterForms` scanning the page body independently of this render.
  renderModal: (call, ctx) => {
    if (call.kind !== "call") return null;
    const argNames = call.argNames ?? [];
    const positionals = (call.args ?? []).filter((_, i) => !argNames[i]);
    const formChild = positionals.find(
      (a): a is Extract<ExprIR, { kind: "call" }> =>
        a.kind === "call" && a.name === "OperationForm",
    );
    const trigger = namedArg(call, "trigger");
    if (!formChild || trigger?.kind !== "call") {
      return flutterTarget.renderComment(
        "Modal: expects trigger: Button(...) and an OperationForm(of:, op:) child",
      );
    }
    const ofArg = namedArg(formChild, "of");
    const opArg = namedArg(formChild, "op");
    const agg = ofArg?.kind === "ref" ? ctx.aggregatesByName.get(ofArg.name) : undefined;
    const op =
      opArg?.kind === "ref"
        ? agg?.operations.find((o) => o.name === opArg.name && o.visibility === "public")
        : undefined;
    if (!agg || !op) {
      return flutterTarget.renderComment(
        "Modal: OperationForm child must name of: <Agg> and op: <public op>",
      );
    }
    ctx.usesRouteId = true;
    const widget = operationFormWidgetName(agg.name, op.name);
    // Trigger label — the Button's first positional string literal, else the op.
    const triggerNames = trigger.argNames ?? [];
    const firstPositional = (trigger.args ?? []).find((_, i) => !triggerNames[i]);
    const label =
      firstPositional?.kind === "literal" && firstPositional.lit === "string"
        ? firstPositional.value
        : humanize(op.name);
    return (
      `ElevatedButton(onPressed: () => showDialog(context: context, ` +
      `builder: (dialogContext) => AlertDialog(title: Text(${dartString(humanize(op.name))}), ` +
      `content: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: ${widget}(id: id))))), ` +
      `child: Text(${dartString(label)}))`
    );
  },

  // --- Type-default seam ---------------------------------------------------
  defaultInitFor: (type) => dartZeroValue(type),

  // --- Markup seams — Dart/Flutter flavoured -------------------------------
  renderComment: (text: string) => `/* ${text} */`,
  // Child-position interpolation → a `Text(…)` widget.  A provably-string value
  // is passed straight; anything else is coerced via Dart string interpolation
  // (`Text('${expr}')`), which stringifies any type.
  renderInterpolation: (jsExpr: string, exprType?: TypeIR) =>
    isStringType(exprType) ? `Text(${jsExpr})` : `Text('\${${jsExpr}}')`,
  // A dynamic attribute → a named widget argument (leading space, camelCased
  // name so a hyphenated source attr stays a legal Dart identifier).
  renderAttrBinding: (name: string, jsExpr: string) => ` ${dartIdent(name)}: ${jsExpr}`,
  // A conditional child → a ternary over two widgets (a single child expression,
  // valid anywhere a widget is expected).
  renderConditionalChild: (cond, thenS, elseS, _depth) => `(${cond} ? ${thenS} : ${elseS})`,
  // Flutter has no CSS `style` attribute — styling is per-widget.  Empty, like
  // Feliz.
  renderStyleAttr: () => "",
  // Raw text for a Dart single-quoted string body (the pack wraps it in
  // `Text('…')`): escape the backslash, the quote, `$`, and the newline.
  escapeText: (text: string) =>
    text.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$").replace(/\n/g, "\\n"),

  // --- Handler seams — Dart closures ---------------------------------------
  // A button's `onPressed:` binds a `VoidCallback`.  The expression form is an
  // arrow; the block form a brace body (each stmt already `;`-terminated).
  renderEventHandler: (stmts, expr) => {
    if (expr !== undefined) return `() => ${expr}`;
    const body = (stmts ?? []).join(" ");
    return `() { ${body} }`;
  },
  // A named `action` → a local closure at the widget-build top; the body reuses
  // the shared `:=`/`+=` statement lowering (Notifier writes).
  renderNamedHandler: (name, param, bodyStmts) => {
    const body = bodyStmts.join(" ");
    const sig = param ? `void ${name}(dynamic ${param})` : `void ${name}()`;
    return `    ${sig} { ${body} }`;
  },

  // --- Expression-syntax leaves (Dart) — forwarded to the shared table ------
  exprLiteral: (lit: LiteralKind, value: string) => DART_LEAVES.literal(lit, value),
  exprBinary: (left, right, op) => DART_LEAVES.binary(left, right, op),
  exprUnary: (op, operand) => DART_LEAVES.unary(op, operand),
  exprTernary: (cond, then, otherwise) => DART_LEAVES.ternary(cond, then, otherwise),
  exprConvert: (value, target, from) => DART_LEAVES.convert(value, target, from),
  exprList: (elements) => DART_LEAVES.list(elements),
  exprObject: (fields) => DART_LEAVES.object(fields),
};
