// ---------------------------------------------------------------------------
// Realtime SSE consumption — Flutter (Dart/Riverpod) flavour (channels.md
// Part I), the Dart sibling of `feliz/realtime.ts` and of React's
// `realtime-handlers-builder.ts`.
//
// `on <channelParam>.<Event>(e) { toast(…) refetch(<Agg>) }` ui members render
// into `lib/realtime.dart`: ONE subscription against `<api>/realtime/events`,
// dispatched per carried event type into a transient `SnackBar` plus a
// `ref.invalidate(<var>Provider)` of the affected aggregate's list read.
//
// Invalidation is the whole re-fetch story here, and it is strictly better than
// re-issuing the call by hand: a Riverpod `.family` provider invalidates every
// live instance, so a SERVER-PAGED table refetches THE PAGE THE USER IS ON —
// the exact case Feliz has to route through a `Refetch<Field>` Msg to avoid
// snapping back to page 1.  Broadcast is at-most-once and untrusted, so the
// handler always re-reads through the provider rather than trusting the frame.
//
// THE TRANSPORT.  Dart has no `EventSource`, and the two surfaces need
// different ones, so `lib/realtime_source.dart` is a conditional import over
// two implementations behind one `loomEventSource(uri, types)` signature:
//
//   web    → `package:web`'s real `EventSource` (the browser's own SSE client:
//             chunked delivery, automatic reconnect).  `package:http` cannot do
//             it — its browser client is XHR-backed and buffers the whole body,
//             so a stream that never ends never yields a frame.
//   native → a hand-rolled line parser over `package:http`'s streamed response,
//             which on the VM does stream.
//
// `package:web` is the one new dependency, pulled only when a ui declares a
// live-event handler — the same use-driven rule `file_picker` / `url_launcher`
// follow.
//
// The toast message is the validator-bounded v1 subset
// (`loom.ui-handler-statement-unknown` admits only `toast(<expr>)`): literals,
// the event binding, single-level member access off it, and operators.
// Anything deeper fails loud here rather than emitting broken Dart.
// ---------------------------------------------------------------------------

import type { ExprIR, UiIR, UiNotificationIR } from "../../ir/types/loom-ir.js";
import { lines } from "../../util/code-builder.js";
import { dartString } from "./dart-expr.js";
import type { FlutterRead } from "./reads-emit.js";

/** True when the ui has at least one live-event handler — the emit gate the
 *  caller combines with the backend actually serving the SSE wire. */
export function flutterHasRealtimeHandlers(ui: UiIR | undefined): boolean {
  return (ui?.notifications?.length ?? 0) > 0;
}

/** The LIST read a `refetch(<Agg>)` invalidates — the ui's own paramless
 *  collection read for that aggregate.  Undefined when the ui never reads the
 *  aggregate, in which case there is nothing to invalidate and the handler says
 *  so in a comment instead of naming a provider that doesn't exist. */
function refetchProvider(aggregate: string, reads: readonly FlutterRead[]): string | undefined {
  const hit = reads.find(
    (r) => r.aggregate === aggregate && !r.single && !r.projection && !r.params,
  );
  return hit ? `${hit.varName}Provider` : undefined;
}

/** `lib/realtime_source.dart` — the conditional-import façade + the event
 *  record both implementations produce. */
export const REALTIME_SOURCE_FACADE = `${lines(
  "// SSE transport façade.  One `loomEventSource(uri, types)` over two",
  "// implementations, picked at COMPILE time by the conditional import below:",
  "// the browser's own `EventSource` on the web, a line parser over a streamed",
  "// `package:http` response everywhere else.  Generated by the Loom Flutter",
  "// target; do not edit.",
  "",
  "export 'realtime_source_io.dart'",
  "    if (dart.library.js_interop) 'realtime_source_web.dart';",
)}\n`;

/** The event record — declared once, in a library both implementations import
 *  (neither can import the other, and the façade only re-exports). */
export const REALTIME_EVENT_DART = `${lines(
  "// One server-sent event: its type tag and its raw JSON payload.  Generated by",
  "// the Loom Flutter target; do not edit.",
  "",
  "class LoomServerEvent {",
  "  final String type;",
  "  final String data;",
  "",
  "  const LoomServerEvent(this.type, this.data);",
  "}",
)}\n`;

/** `lib/realtime_source_web.dart` — the browser's own SSE client. */
export const REALTIME_SOURCE_WEB_DART = `${lines(
  "// Web SSE transport — the browser's `EventSource`, which owns chunked",
  "// delivery and automatic reconnect.  `package:http` cannot serve this role on",
  "// the web: its browser client is XHR-backed and buffers the whole body, so a",
  "// never-ending stream never yields a frame.  Generated by the Loom Flutter",
  "// target; do not edit.",
  "",
  "import 'dart:async';",
  "import 'dart:js_interop';",
  "",
  "import 'package:web/web.dart' as web;",
  "",
  "import 'realtime_event.dart';",
  "",
  "export 'realtime_event.dart';",
  "",
  "Stream<LoomServerEvent> loomEventSource(Uri uri, List<String> types) {",
  "  web.EventSource? source;",
  "  late StreamController<LoomServerEvent> controller;",
  "  controller = StreamController<LoomServerEvent>(",
  "    onListen: () {",
  "      final es = web.EventSource(uri.toString());",
  "      source = es;",
  "      for (final type in types) {",
  "        es.addEventListener(",
  "          type,",
  "          ((web.MessageEvent event) {",
  "            final data = event.data;",
  "            controller.add(",
  "              LoomServerEvent(type, data.isA<JSString>() ? (data as JSString).toDart : ''),",
  "            );",
  "          }).toJS,",
  "        );",
  "      }",
  "    },",
  "    onCancel: () {",
  "      source?.close();",
  "      source = null;",
  "    },",
  "  );",
  "  return controller.stream;",
  "}",
)}\n`;

/** `lib/realtime_source_io.dart` — the native line parser. */
export const REALTIME_SOURCE_IO_DART = `${lines(
  "// Native SSE transport — a line parser over a STREAMED `package:http`",
  "// response (on the VM the response body really does arrive incrementally).",
  "// `types` is unused here: an SSE frame carries its own `event:` field, so the",
  "// parser reports whatever the server sent and the dispatcher filters.",
  "// Generated by the Loom Flutter target; do not edit.",
  "",
  "import 'dart:convert';",
  "",
  "import 'package:http/http.dart' as http;",
  "",
  "import 'realtime_event.dart';",
  "",
  "export 'realtime_event.dart';",
  "",
  "Stream<LoomServerEvent> loomEventSource(Uri uri, List<String> types) async* {",
  "  final client = http.Client();",
  "  try {",
  "    final request = http.Request('GET', uri)",
  "      ..headers['Accept'] = 'text/event-stream';",
  "    final response = await client.send(request);",
  "    var type = 'message';",
  "    final data = StringBuffer();",
  "    final lines = response.stream.transform(utf8.decoder).transform(const LineSplitter());",
  "    await for (final line in lines) {",
  "      if (line.isEmpty) {",
  "        // A blank line terminates the frame.",
  "        if (data.isNotEmpty) yield LoomServerEvent(type, data.toString());",
  "        type = 'message';",
  "        data.clear();",
  "      } else if (line.startsWith('event:')) {",
  "        type = line.substring(6).trim();",
  "      } else if (line.startsWith('data:')) {",
  "        data.write(line.substring(5).trimLeft());",
  "      }",
  "      // `id:` / `retry:` / a `:` comment line are ignored.",
  "    }",
  "  } finally {",
  "    client.close();",
  "  }",
  "}",
)}\n`;

/** True when a v1 toast expression reads the event binding (bare or via a
 *  member) — gates the payload decode. */
function exprReadsBinding(e: ExprIR, bind: string): boolean {
  switch (e.kind) {
    case "ref":
      return e.name === bind;
    case "member":
      return exprReadsBinding(e.receiver, bind);
    case "paren":
      return exprReadsBinding(e.inner, bind);
    case "binary":
      return exprReadsBinding(e.left, bind) || exprReadsBinding(e.right, bind);
    default:
      return false;
  }
}

/** Render the v1 toast-message subset to a Dart String expression.  The event
 *  binding decodes to `payload` (a `Map<String, dynamic>`); member access reads
 *  a key off it, and every leaf is `String`-coerced so a binary `+` stays a
 *  string concatenation rather than a `dynamic` addition. */
function renderDartToastMessage(e: ExprIR, bind: string): string {
  switch (e.kind) {
    case "literal":
      return e.lit === "string" ? dartString(e.value) : `'${e.value}'`;
    case "ref":
      if (e.name === bind) return "payload.toString()";
      throw new Error(
        `Flutter realtime: unsupported name '${e.name}' in toast message (only the event binding '${bind}' is in scope).`,
      );
    case "member": {
      if (e.receiver.kind !== "ref" || e.receiver.name !== bind) {
        throw new Error(
          "Flutter realtime: toast messages support single-level member access off the event binding only.",
        );
      }
      return `'\${payload[${dartString(e.member)}]}'`;
    }
    case "paren":
      return `(${renderDartToastMessage(e.inner, bind)})`;
    case "binary":
      return `${renderDartToastMessage(e.left, bind)} ${e.op} ${renderDartToastMessage(e.right, bind)}`;
    default:
      throw new Error(
        `Flutter realtime: unsupported expression kind '${e.kind}' in toast message.`,
      );
  }
}

/** `lib/realtime.dart` — the subscription widget + the per-event dispatch. */
export function renderFlutterRealtime(ui: UiIR, reads: readonly FlutterRead[]): string {
  const notifications = ui.notifications ?? [];
  const byEvent = new Map<string, UiNotificationIR[]>();
  for (const n of notifications) {
    const list = byEvent.get(n.eventType) ?? [];
    list.push(n);
    byEvent.set(n.eventType, list);
  }
  const eventTypes = [...byEvent.keys()].sort((a, b) => a.localeCompare(b));

  const arms: string[] = [];
  let anyPayload = false;
  for (const eventType of eventTypes) {
    const handlers = byEvent.get(eventType)!;
    arms.push(`      case ${dartString(eventType)}:`);
    for (const h of handlers) {
      for (const toast of h.toasts) {
        if (exprReadsBinding(toast, h.bind)) anyPayload = true;
        arms.push(`        _toast(${renderDartToastMessage(toast, h.bind)});`);
      }
    }
    // One invalidation per distinct aggregate across this event's handlers.
    const seen = new Set<string>();
    for (const h of handlers) {
      for (const r of h.refetches ?? []) {
        if (seen.has(r.aggregate)) continue;
        seen.add(r.aggregate);
        const provider = refetchProvider(r.aggregate, reads);
        arms.push(
          provider
            ? `        ref.invalidate(${provider});`
            : `        // refetch(${r.aggregate}): this ui issues no list read for it, so there is nothing to invalidate.`,
        );
      }
    }
    arms.push("        break;");
  }

  const needsReads = arms.some((l) => l.includes("ref.invalidate("));
  return `${lines(
    "// Realtime SSE handlers (channels.md Part I) — ONE subscription against",
    "// /realtime/events, dispatched per carried event type into a transient",
    "// SnackBar plus an invalidation of the affected aggregate's list read.",
    "// Invalidating a Riverpod `.family` refetches EVERY live instance, so a",
    "// server-paged table reloads the page the user is actually on.  The",
    "// broadcast frame is untrusted (at-most-once); the authorized read stays the",
    "// gate, so the handler re-reads through the provider rather than trusting it.",
    "// Generated by the Loom Flutter target; do not edit.",
    "",
    "import 'dart:async';",
    anyPayload ? "import 'dart:convert';" : undefined,
    "",
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "",
    "import 'config.dart';",
    needsReads ? "import 'reads.dart';" : undefined,
    "import 'realtime_source.dart';",
    "",
    "/// The event types this ui actually handles — the web transport has to",
    "/// `addEventListener` per type, so the list is part of the contract.",
    `const List<String> loomRealtimeEvents = <String>[${eventTypes
      .map((t) => dartString(t))
      .join(", ")}];`,
    "",
    "/// Subscribes for as long as it is mounted.  Rides `MaterialApp.builder` so a",
    "/// toast has a `ScaffoldMessenger` ancestor to show in.",
    "class LoomRealtime extends ConsumerStatefulWidget {",
    "  const LoomRealtime({super.key, required this.child});",
    "",
    "  final Widget child;",
    "",
    "  @override",
    "  ConsumerState<LoomRealtime> createState() => _LoomRealtimeState();",
    "}",
    "",
    "class _LoomRealtimeState extends ConsumerState<LoomRealtime> {",
    "  StreamSubscription<LoomServerEvent>? _subscription;",
    "",
    "  @override",
    "  void initState() {",
    "    super.initState();",
    "    _subscription = loomEventSource(apiUri('/realtime/events'), loomRealtimeEvents)",
    "        .listen(_onEvent, onError: (Object _) {});",
    "  }",
    "",
    "  @override",
    "  void dispose() {",
    "    _subscription?.cancel();",
    "    super.dispose();",
    "  }",
    "",
    "  void _onEvent(LoomServerEvent event) {",
    ...(anyPayload
      ? [
          "    // The frame body is untrusted: a malformed payload degrades to an empty",
          "    // map rather than tearing down the subscription.",
          "    Map<String, dynamic> payload = const <String, dynamic>{};",
          "    try {",
          "      final decoded = jsonDecode(event.data);",
          "      if (decoded is Map<String, dynamic>) payload = decoded;",
          "    } catch (_) {}",
        ]
      : []),
    "    switch (event.type) {",
    arms,
    "      default:",
    "        break;",
    "    }",
    "  }",
    "",
    "  void _toast(String message) {",
    "    if (!mounted) return;",
    "    ScaffoldMessenger.maybeOf(context)?.showSnackBar(SnackBar(content: Text(message)));",
    "  }",
    "",
    "  @override",
    "  Widget build(BuildContext context) => widget.child;",
    "}",
  )}\n`;
}
