// ---------------------------------------------------------------------------
// Verification artifacts — Markdown report, JSON index, and a verdict-colored
// requirements graph.  Pure, procedural (`lines(...)`), matching the style of
// `src/system/traceability.ts`.  Consumed by `ddd verify`.
// ---------------------------------------------------------------------------

import { lines } from "../util/code-builder.js";
import type {
  LoomModel,
  RequirementIR,
  RequirementVerdict,
  VerificationIR,
} from "../ir/loom-ir.js";

const GLYPH: Record<RequirementVerdict, string> = {
  VERIFIED: "✅",
  FAILING: "❌",
  UNTESTED: "⚪",
  UNVERIFIED: "🟡",
};

const MMD_CLASS: Record<RequirementVerdict, string> = {
  VERIFIED: "verified",
  FAILING: "failing",
  UNTESTED: "untested",
  UNVERIFIED: "unverified",
};

function pct(n: number, total: number): string {
  if (total === 0) return "n/a";
  return `${Math.round((n / total) * 100)}%`;
}

function byId(loom: LoomModel): Map<string, RequirementIR> {
  return new Map(loom.requirements.map((r) => [r.id, r]));
}

export function renderVerificationJson(v: VerificationIR): string {
  return JSON.stringify(v, null, 2) + "\n";
}

export function renderVerificationMd(loom: LoomModel, v: VerificationIR): string {
  const reqs = byId(loom);
  const children = loom.traceability?.childrenOf ?? {};
  const roots = loom.requirements.filter((r) => !r.parentId);
  const s = v.summary;

  const renderReq = (id: string, depth: number): string[] => {
    const r = reqs.get(id);
    if (!r) return [];
    const verdict = v.requirements[id]?.verdict ?? "UNTESTED";
    const indent = "  ".repeat(depth);
    const failing = v.requirements[id]?.failingTestCaseIds ?? [];
    const note = failing.length ? ` — failing: ${failing.map((x) => `\`${x}\``).join(", ")}` : "";
    const head = `${indent}- ${GLYPH[verdict]} **${r.id}** (${verdict}) ${r.title}${note}`;
    const kids = (children[id] ?? []).flatMap((c) => renderReq(c, depth + 1));
    return [head, ...kids];
  };

  const tcRows = Object.keys(v.testCases)
    .sort()
    .map((id) => {
      const tc = v.testCases[id];
      const backing = tc.backing.map((b) => `${b.name} (${b.status})`).join("; ") || "_none_";
      return `| \`${id}\` | ${tc.status} | ${backing} |`;
    });

  const diag = v.diagnostics;
  return (
    lines(
      "# Verification",
      "",
      "_Generated by Loom. Derived view — do not edit._",
      "",
      `Verified **${pct(s.verified, s.total)}** of requirements — ${s.verified} verified, ${s.failing} failing, ${s.unverified} unverified, ${s.untested} untested (of ${s.total}).`,
      "",
      "## Requirements",
      "",
      roots.flatMap((r) => renderReq(r.id, 0)),
      "",
      "## Test cases",
      "",
      "| Test case | Status | Backing tests |",
      "| --- | --- | --- |",
      tcRows.length ? tcRows : "| _none_ |  |  |",
      "",
      "## Diagnostics",
      "",
      diag.unknownTests.length
        ? ["Results matching no declared test:", ...diag.unknownTests.map((t) => `- ${t.suite ? `${t.suite} › ` : ""}${t.name} (${t.status})`)]
        : "_No unknown results._",
    ) + "\n"
  );
}

/** Verdict-colored requirements graph (Mermaid).  A self-contained
 *  requirements-only view: nodes colored by verdict, parent→child edges. */
export function renderVerdictGraph(loom: LoomModel, v: VerificationIR): string {
  const children = loom.traceability?.childrenOf ?? {};
  const idOf = new Map<string, string>();
  loom.requirements.forEach((r, i) => idOf.set(r.id, `r${i}`));
  const esc = (s: string): string => s.replace(/"/g, "'");

  const body: string[] = [];
  for (const r of loom.requirements) {
    body.push(`  ${idOf.get(r.id)}["${esc(r.id)}: ${esc(r.title)}"]`);
  }
  for (const r of loom.requirements) {
    for (const c of children[r.id] ?? []) {
      if (idOf.has(c)) body.push(`  ${idOf.get(r.id)} --> ${idOf.get(c)}`);
    }
  }
  // Group node ids by verdict for `class` lines.
  const groups: Record<string, string[]> = {};
  for (const r of loom.requirements) {
    const verdict = v.requirements[r.id]?.verdict ?? "UNTESTED";
    (groups[MMD_CLASS[verdict]] ??= []).push(idOf.get(r.id)!);
  }
  const classLines = Object.keys(groups)
    .sort()
    .map((cls) => `  class ${groups[cls].join(",")} ${cls}`);

  return (
    lines(
      "flowchart LR",
      body,
      "  classDef verified fill:#16a34a,color:#fff;",
      "  classDef failing fill:#dc2626,color:#fff;",
      "  classDef untested fill:#9ca3af,color:#fff;",
      "  classDef unverified fill:#eab308,color:#000;",
      classLines,
    ) + "\n"
  );
}
