// Extern frontend components — Angular flavour
// (extern-component-escape-hatch.md).  For each `component <Name>(params)
// extern from "<path>"` ui member, Loom owns two machine-owned files and never
// writes the user's module:
//
//   ① `src/components/<Name>.props.ts` — the typed props interface
//      (`export interface <Name>Props { … }`), wire-DTO-typed so a domain
//      change regenerates the type and breaks a stale hand-written component.
//      The user types their standalone component's `@Input()`s against it.
//   ② `src/components/<Name>.ts` — the re-export shim: a stable import for
//      call sites AND the contract-enforcement point.  It re-exports the
//      component CLASS (named `<Name>`) from the `from` path; a missing module
//      or wrong export fails the shim's import — `tsc`/`ng build` is the
//      fail-fast (the Angular twin of the react/vue `default`-re-export shim,
//      differing only because an Angular component is a NAMED class, not a
//      default export).
//
// Call sites render the component through Angular's `NgComponentOutlet`
// (`angularTarget.renderUserComponent`); the page shell imports the class from
// this shim, re-exposes it as a member, and registers the directive.

import type { AggregateIR, ParamIR, TypeIR } from "../../ir/types/loom-ir.js";
import { lowerFirst } from "../../util/naming.js";

/** Map a Loom param type to its wire-side TS spelling for the props interface.
 *  Aggregates use the wire DTO (`<Agg>Response`, recorded into `dtoImports`);
 *  primitives / ids / enums map to their TS equivalents; a `slot` param has no
 *  `ngComponentOutlet` input analogue in v0, so it types as `unknown`; an
 *  `action` maps to a void callback.  Anything unrecognised falls back to
 *  `unknown` rather than throwing — the props file is a contract the user types
 *  against, so it must always emit. */
function wireType(t: TypeIR, dtoImports: Map<string, string>): string {
  switch (t.kind) {
    case "primitive":
      switch (t.name) {
        case "int":
        case "long":
        case "decimal":
          return "number";
        case "bool":
          return "boolean";
        case "string":
        case "datetime":
        case "guid":
          return "string";
        default:
          return "unknown";
      }
    case "entity":
      dtoImports.set(`${t.name}Response`, `../api/${lowerFirst(t.name)}`);
      return `${t.name}Response`;
    case "id":
      return "string";
    case "enum":
      return "string";
    case "array":
      return `${wireType(t.element, dtoImports)}[]`;
    case "optional":
      return `${wireType(t.inner, dtoImports)} | undefined`;
    case "action":
      return t.arg ? `(arg: ${wireType(t.arg, dtoImports)}) => void` : "() => void";
    default:
      return "unknown";
  }
}

/** ① The machine-owned typed props interface at
 *  `src/components/<Name>.props.ts`. */
export function renderAngularExternComponentProps(
  name: string,
  params: ParamIR[],
  _aggregatesByName: ReadonlyMap<string, AggregateIR> = new Map(),
): string {
  const dtoImports = new Map<string, string>();
  const propLines = params.map((p) => {
    // A `slot?` / `action?` param is optional so the caller may omit it.
    const optional =
      p.type.kind === "optional" &&
      (p.type.inner.kind === "slot" || p.type.inner.kind === "action");
    return `  ${p.name}${optional ? "?:" : ":"} ${wireType(p.type, dtoImports)};`;
  });
  const dtoImportLines = [...dtoImports.entries()]
    .map(([type, mod]) => `import type { ${type} } from "${mod}";\n`)
    .join("");
  const body =
    propLines.length > 0
      ? `export interface ${name}Props {\n${propLines.join("\n")}\n}\n`
      : `export type ${name}Props = Record<string, never>;\n`;
  return `// AUTO-GENERATED by Loom — typed props for the extern component '${name}'.
// Do not edit; overwritten on every generate.  Type your hand-written standalone
// component's @Input()s against this interface (declared via
// \`component ${name}(...) extern from\`).
${dtoImportLines}${dtoImportLines ? "\n" : ""}${body}`;
}

/** ② The machine-owned re-export shim at `src/components/<Name>.ts`. */
export function renderAngularExternComponentShim(name: string, externPath: string): string {
  const rel = externPath.replace(/^\.?\//, "");
  return `// AUTO-GENERATED extern component shim. Re-exports the hand-written
// standalone component declared via \`component ${name}(...) extern from "${externPath}"\`.
// Loom owns this shim and './${name}.props'; you own '../${rel}' (which must
// \`export class ${name}\`).
export { ${name} } from "../${rel}";
export type { ${name}Props } from "./${name}.props";
`;
}
