// The generated Angular app's code-point-counting length validators.
//
// Loom measures string length in CODE POINTS.  Every other target agrees:
// the zod schema the JS frontends and the Hono backend share emits
// `.refine((s) => [...s].length >= n)`, and the .NET / Java / Python / Elixir
// backends count characters, not UTF-16 units.  Angular's BUILT-IN
// `Validators.minLength` / `maxLength` are the one exception — they read
// `value.length`, which is UTF-16 CODE UNITS, so every astral character (an
// emoji, most CJK extension-B ideographs, a musical symbol) counts twice.
//
// The visible failure: `name: string  invariant "len" { name.length >= 3 }`
// accepts the two-code-point "👍👍" client-side (4 UTF-16 units ≥ 3) and the
// server then rejects it with a 422 the form has no field error for; the
// mirror case rejects a value the server would accept.  Angular was also the
// only frontend deriving NATIVE validators from a `SingleFieldPattern` with no
// zod schema behind them, so there was no second, correct gate to catch it.
//
// Emitted unconditionally at `src/lib/loom-validators.ts` (like
// `src/lib/table-sort.ts`); imported only by the components that use it.

import { lines } from "../../util/code-builder.js";

/** The `src/lib/loom-validators.ts` module of a generated Angular project. */
export function buildAngularValidatorsHelper(): string {
  return lines(
    "// Auto-generated by Loom.  Do not edit by hand.",
    "//",
    "// Loom measures string length in CODE POINTS; Angular's built-in",
    "// Validators.minLength/maxLength measure UTF-16 code units, so an astral",
    "// character (emoji, rarer CJK) would count twice and the client would",
    "// disagree with the server's 422.  These count the same way the shared zod",
    "// schema does: `[...s].length`.",
    'import type { AbstractControl, ValidationErrors, ValidatorFn } from "@angular/forms";',
    "",
    "/** Code-point length of a control value; null when it isn't a string. */",
    "function codePointLength(value: unknown): number | null {",
    '  return typeof value === "string" ? [...value].length : null;',
    "}",
    "",
    "/** Angular treats an empty value as 'no value' and leaves it to",
    " *  `Validators.required` — mirrored here so adding these validators does",
    " *  not make an untouched optional field invalid. */",
    "function isEmpty(value: unknown): boolean {",
    '  return value === null || value === undefined || value === "";',
    "}",
    "",
    "/** `Validators.minLength`, counted in code points.  Emits the same",
    " *  `minlength` error key, so existing error rendering is unchanged. */",
    "export function loomMinLength(n: number): ValidatorFn {",
    "  return (control: AbstractControl): ValidationErrors | null => {",
    "    if (isEmpty(control.value)) return null;",
    "    const actualLength = codePointLength(control.value);",
    "    if (actualLength === null || actualLength >= n) return null;",
    "    return { minlength: { requiredLength: n, actualLength } };",
    "  };",
    "}",
    "",
    "/** `Validators.maxLength`, counted in code points. */",
    "export function loomMaxLength(n: number): ValidatorFn {",
    "  return (control: AbstractControl): ValidationErrors | null => {",
    "    const actualLength = codePointLength(control.value);",
    "    if (actualLength === null || actualLength <= n) return null;",
    "    return { maxlength: { requiredLength: n, actualLength } };",
    "  };",
    "}",
    "",
  );
}

/** The helper names a generated component may reference — the scan list the
 *  page/component shell uses to decide whether to emit the import. */
export const ANGULAR_VALIDATOR_HELPERS = ["loomMinLength", "loomMaxLength"] as const;
