// ---------------------------------------------------------------------------
// The `README.md` the exported ZIP carries at its root (M-T8.23 slice 3).
//
// The ZIP is the bridge out of the browser: it is how a .NET / Phoenix / Java /
// Python backend, or a Vue / Svelte / Angular frontend, gets run at all, since
// the playground cannot bundle or boot those. Before this it shipped a tree of
// generated projects and a `docker-compose.yml` with nothing saying what to do
// with them — the one instruction the recipient needs ("`docker compose up`,
// then open this port") lived only in the docs they had not read.
//
// Pure and derived: the service list and its published ports come from the
// generated compose file itself, so the README cannot claim a service or a
// port the tree does not actually emit. Nothing is hard-coded per platform.
// ---------------------------------------------------------------------------

/** One service as the generated `docker-compose.yml` declares it. */
export interface ComposeService {
  name: string;
  /** Published host ports, in declaration order (`"3000:3000"` → `3000`). */
  hostPorts: string[];
}

/** Services and their published host ports, read out of a compose file.
 *
 *  A deliberately small reader rather than a YAML dependency: the file is
 *  emitted by `src/system/index.ts` in one fixed shape (two-space service keys
 *  under `services:`, `- "HOST:CONTAINER"` port entries), so the parse is
 *  exact for the input it will ever see, and a shape it does not recognise
 *  yields fewer rows rather than a wrong README. */
export function composeServices(compose: string): ComposeService[] {
  const out: ComposeService[] = [];
  let inServices = false;
  let current: ComposeService | null = null;
  let inPorts = false;
  for (const raw of compose.split("\n")) {
    const line = raw.replace(/\r$/, "");
    if (/^\S/.test(line)) {
      // A top-level key ends the services block (`volumes:` and friends).
      inServices = line.startsWith("services:");
      current = null;
      inPorts = false;
      continue;
    }
    if (!inServices) continue;
    const service = /^ {2}([A-Za-z0-9_.-]+):\s*$/.exec(line);
    if (service?.[1]) {
      current = { name: service[1], hostPorts: [] };
      out.push(current);
      inPorts = false;
      continue;
    }
    if (!current) continue;
    if (/^ {4}ports:\s*$/.test(line)) {
      inPorts = true;
      continue;
    }
    if (/^ {4}\S/.test(line)) {
      inPorts = false;
      continue;
    }
    if (!inPorts) continue;
    const port = /^\s*-\s*"?(\d+):\d+"?\s*$/.exec(line);
    if (port?.[1]) current.hostPorts.push(port[1]);
  }
  return out;
}

export interface ExportReadmeInput {
  /** The project name — the ZIP's own basename. */
  name: string;
  /** Every generated file's archive-relative path. */
  paths: readonly string[];
  /** The generated `docker-compose.yml`, or null when the tree has none
   *  (the legacy single-project generate modes). */
  compose: string | null;
}

/** Path of the README inside the archive. */
export const EXPORT_README_PATH = "README.md";

/** Build the README. */
export function buildExportReadme(input: ExportReadmeInput): string {
  const services = input.compose ? composeServices(input.compose) : [];
  const projects = topLevelProjects(input.paths);
  const lines: string[] = [];

  lines.push(`# ${input.name}`);
  lines.push("");
  lines.push(
    "Generated by [Loom](https://github.com/lemmit/Loc) from a `.ddd` model. " +
      "Everything here is emitted output: edit the model and regenerate rather " +
      "than editing these files, or take them over wholesale — both are supported.",
  );
  lines.push("");

  if (input.compose) {
    lines.push("## Run it");
    lines.push("");
    lines.push("```sh");
    lines.push("docker compose up --build");
    lines.push("```");
    lines.push("");
    lines.push(
      "The stack brings up Postgres first and waits on its healthcheck, so the " +
        "backends apply their schema against a database that is actually accepting " +
        "connections. First build compiles every project in the tree, so expect it " +
        "to take a few minutes; later runs are cached.",
    );
    lines.push("");
    if (services.length > 0) {
      lines.push("| Service | On |");
      lines.push("|---|---|");
      for (const s of services) {
        const where =
          s.hostPorts.length > 0
            ? s.hostPorts.map((p) => `http://localhost:${p}`).join(", ")
            : "internal to the stack";
        lines.push(`| \`${s.name}\` | ${where} |`);
      }
      lines.push("");
    }
    lines.push("Stop and discard the database with:");
    lines.push("");
    lines.push("```sh");
    lines.push("docker compose down -v");
    lines.push("```");
    lines.push("");
  } else {
    lines.push("## Run it");
    lines.push("");
    lines.push(
      "This export has no `docker-compose.yml` — it is a single generated " +
        "project. Follow that project's own README / package manifest to install " +
        "and run it.",
    );
    lines.push("");
  }

  if (projects.length > 0) {
    lines.push("## What is in here");
    lines.push("");
    for (const p of projects) lines.push(`- \`${p}/\``);
    lines.push("");
  }
  lines.push(
    "`.loom/` holds the model's derived views — the mermaid diagrams, the " +
      "LikeC4 model, the wire spec and the traceability graph. They are " +
      "artefacts, not inputs.",
  );
  lines.push("");
  return `${lines.join("\n")}`;
}

/** Top-level directories in the tree, sorted, minus the artefact dirs that
 *  are not projects. */
function topLevelProjects(paths: readonly string[]): string[] {
  const out = new Set<string>();
  for (const path of paths) {
    const slash = path.indexOf("/");
    if (slash <= 0) continue;
    const top = path.slice(0, slash);
    if (top.startsWith(".")) continue;
    out.add(top);
  }
  return [...out].sort();
}
