// Generated `http/channels.ts` — the broker transport module (M-T4.4
// slice 2, design §4–5).  Emitted only when the deployable wires at least
// one redis-bound `broadcast`/`ephemeral` channelSource; channel-less
// projects stay byte-identical.
//
// The module carries the `ChannelTransport` seam (the contract the
// in-process dispatcher, every broker driver, and M-T1.10's realtime relay
// share), the CloudEvents 1.0 envelope, the redis (Valkey) driver over
// ioredis pub/sub, the producer tee, and the consumer loop.  The
// delivery-uniformity rule (design §4) is enforced in the tee: an event
// carried by a broker-bound channel is published and NOT fanned out
// locally — co-located consumers receive it through their subscription,
// exactly like remote ones, so `broadcast` behaves identically regardless
// of process placement.

import { lines } from "../../../util/code-builder.js";
import type { BrokerBinding } from "../../_channels/bindings.js";

/** envVar → address per binding, deduped (two bindings on one deployable
 *  may share a channelSource only via duplicate list entries). */
function uniqueBindings(bindings: BrokerBinding[]): BrokerBinding[] {
  const seen = new Set<string>();
  return bindings.filter((b) => {
    if (seen.has(b.csName)) return false;
    seen.add(b.csName);
    return true;
  });
}

export function renderChannelsModule(bindings: BrokerBinding[]): string {
  const unique = uniqueBindings(bindings);
  // event type -> address of the (first) carrying broker-bound channel;
  // mirrors the in-process dispatcher's first-by-declaration routing rule.
  const routing = new Map<string, string>();
  for (const b of unique) {
    for (const ev of b.events) {
      if (!routing.has(ev)) routing.set(ev, b.address);
    }
  }
  return (
    lines(
      "// Auto-generated.",
      "// Broker transport for the deployable's wired channels (channels.md;",
      "// M-T4.4 design §4-5).  Redis/Valkey pub/sub carries CloudEvents 1.0",
      "// envelopes between deployables; the consumer loop feeds received",
      "// events into the same in-process dispatcher local reactors use.",
      'import { Redis } from "ioredis";',
      'import type { DomainEvent, DomainEventDispatcher } from "../domain/events";',
      'import { baseLogger } from "../obs/log";',
      "",
      "/** CloudEvents 1.0 JSON envelope — the cross-backend wire contract",
      " * (loom envelope pin, src/util/channels.ts).  `id` doubles as the",
      " * consumer-side idempotency key once durable tiers land (slice 3). */",
      "export interface LoomEventEnvelope {",
      '  specversion: "1.0";',
      "  id: string;",
      "  type: string;",
      "  source: string;",
      "  time: string;",
      '  datacontenttype: "application/json";',
      "  loomchannel: string;",
      "  data: Record<string, unknown>;",
      "}",
      "",
      "/** The publish/subscribe seam every transport implements — in-process,",
      " * the broker drivers, and the realtime relay (M-T1.10) all sit on this",
      " * interface.  `group` is null for broadcast (every subscriber sees every",
      " * envelope); competing-consumer groups arrive with the queue tier. */",
      "export interface ChannelTransport {",
      "  publish(address: string, envelope: LoomEventEnvelope): Promise<void>;",
      "  subscribe(",
      "    address: string,",
      "    group: string | null,",
      "    handler: (envelope: LoomEventEnvelope) => Promise<void>,",
      "  ): () => void;",
      "  close(): Promise<void>;",
      "}",
      "",
      "/** Redis (Valkey) driver — pub/sub over ioredis.  A dedicated",
      " * subscriber connection is required by the redis protocol (a",
      " * connection in subscribe mode can't publish). */",
      "export function createRedisTransport(url: string): ChannelTransport {",
      "  const pub = new Redis(url, { lazyConnect: false, maxRetriesPerRequest: 3 });",
      "  const sub = new Redis(url, { lazyConnect: false, maxRetriesPerRequest: 3 });",
      "  const handlers = new Map<string, Set<(e: LoomEventEnvelope) => Promise<void>>>();",
      '  sub.on("message", (address: string, message: string) => {',
      "    const set = handlers.get(address);",
      "    if (!set) return;",
      "    let envelope: LoomEventEnvelope;",
      "    try {",
      "      envelope = JSON.parse(message) as LoomEventEnvelope;",
      "    } catch {",
      '      baseLogger.warn({ event: "channel_consume_failed", address, error: "malformed envelope" });',
      "      return;",
      "    }",
      "    for (const h of set) {",
      "      void h(envelope).catch((err) => {",
      "        baseLogger.warn({",
      '          event: "channel_consume_failed",',
      "          address,",
      "          type: envelope.type,",
      "          error: err instanceof Error ? err.message : String(err),",
      "        });",
      "      });",
      "    }",
      "  });",
      "  return {",
      "    async publish(address, envelope) {",
      "      await pub.publish(address, JSON.stringify(envelope));",
      "    },",
      "    subscribe(address, _group, handler) {",
      "      let set = handlers.get(address);",
      "      if (!set) {",
      "        set = new Set();",
      "        handlers.set(address, set);",
      "        void sub.subscribe(address);",
      "      }",
      "      set.add(handler);",
      "      return () => {",
      "        set.delete(handler);",
      "        if (set.size === 0) {",
      "          handlers.delete(address);",
      "          void sub.unsubscribe(address);",
      "        }",
      "      };",
      "    },",
      "    async close() {",
      "      await Promise.allSettled([pub.quit(), sub.quit()]);",
      "    },",
      "  };",
      "}",
      "",
      "// The deployable's wired bindings: broker address per channelSource, with",
      "// the connection URL injected by compose/k8s as LOOM_CHANNEL_<NAME>_URL.",
      "export const CHANNEL_BINDINGS = [",
      ...unique.map(
        (b) =>
          `  { csName: ${JSON.stringify(b.csName)}, address: ${JSON.stringify(b.address)}, envVar: ${JSON.stringify(b.envVar)}, context: ${JSON.stringify(b.contextName)} },`,
      ),
      "] as const;",
      "",
      "// event type -> broker address (first carrying broker-bound channel,",
      "// mirroring the in-process dispatcher's first-by-declaration rule).",
      "export const CHANNEL_ROUTING: Record<string, string> = {",
      ...[...routing.entries()].map(([ev, addr]) => `  ${ev}: ${JSON.stringify(addr)},`),
      "};",
      "",
      "let counter = 0;",
      "function envelopeFor(event: DomainEvent, address: string): LoomEventEnvelope {",
      "  const { type, ...data } = event as unknown as { type: string } & Record<string, unknown>;",
      '  const context = CHANNEL_BINDINGS.find((b) => b.address === address)?.context ?? "";',
      "  counter += 1;",
      "  return {",
      '    specversion: "1.0",',
      "    id: `${Date.now().toString(36)}-${process.pid.toString(36)}-${counter.toString(36)}`,",
      "    type: `${context}.${type}`,",
      "    source: `/loom/${context}`,",
      "    time: new Date().toISOString(),",
      '    datacontenttype: "application/json",',
      "    loomchannel: address,",
      "    data,",
      "  };",
      "}",
      "",
      "/** One shared transport per broker URL for the process (publisher tee +",
      " * consumer loop reuse the same connections). */",
      "export function createChannelTransports(): Map<string, ChannelTransport> {",
      "  const byUrl = new Map<string, ChannelTransport>();",
      "  const byEnv = new Map<string, ChannelTransport>();",
      "  for (const b of CHANNEL_BINDINGS) {",
      "    const url = process.env[b.envVar];",
      "    if (!url) {",
      "      throw new Error(",
      "        `channel binding '${b.csName}' needs ${b.envVar} (the broker URL compose/k8s injects)`,",
      "      );",
      "    }",
      "    let t = byUrl.get(url);",
      "    if (!t) {",
      "      t = createRedisTransport(url);",
      "      byUrl.set(url, t);",
      "    }",
      "    byEnv.set(b.csName, t);",
      "  }",
      "  return byEnv;",
      "}",
      "",
      "/** Close every distinct transport (producer-only shutdown; the consumer",
      " * loop's stop function closes them itself). */",
      "export async function closeChannelTransports(",
      "  transports: Map<string, ChannelTransport>,",
      "): Promise<void> {",
      "  await Promise.allSettled([...new Set(transports.values())].map((t) => t.close()));",
      "}",
      "",
      "function transportForAddress(",
      "  transports: Map<string, ChannelTransport>,",
      "  address: string,",
      "): ChannelTransport {",
      "  const binding = CHANNEL_BINDINGS.find((b) => b.address === address);",
      "  const t = binding ? transports.get(binding.csName) : undefined;",
      "  if (!t) throw new Error(`no transport wired for channel address ${address}`);",
      "  return t;",
      "}",
      "",
      "/** Producer tee — the delivery-uniformity rule (design §4): an event",
      " * carried by a broker-bound channel is PUBLISHED and not fanned out",
      " * locally; co-located consumers receive it through their subscription",
      " * exactly like remote ones.  Everything else passes to `inner`. */",
      "export function channelPublishTee(",
      "  transports: Map<string, ChannelTransport>,",
      "  inner: DomainEventDispatcher,",
      "): DomainEventDispatcher {",
      "  return {",
      "    async dispatch(event: DomainEvent): Promise<void> {",
      "      const address = CHANNEL_ROUTING[event.type];",
      "      if (!address) return inner.dispatch(event);",
      "      const envelope = envelopeFor(event, address);",
      "      await transportForAddress(transports, address).publish(address, envelope);",
      '      baseLogger.info({ event: "channel_published", address, type: event.type, id: envelope.id });',
      "    },",
      "  };",
      "}",
      "",
      "/** Consumer loop — subscribes every wired address and dispatches received",
      " * envelopes into the given (in-process) dispatcher, so reactors and",
      " * event-triggered creates run identically for local and remote events. */",
      "export function startChannelConsumers(",
      "  transports: Map<string, ChannelTransport>,",
      "  dispatcher: DomainEventDispatcher,",
      "): () => Promise<void> {",
      "  const unsubs: Array<() => void> = [];",
      "  for (const b of CHANNEL_BINDINGS) {",
      "    const t = transports.get(b.csName);",
      "    if (!t) continue;",
      "    unsubs.push(",
      "      t.subscribe(b.address, null, async (envelope) => {",
      '        const bare = envelope.type.includes(".") ? envelope.type.slice(envelope.type.indexOf(".") + 1) : envelope.type;',
      "        const event = { type: bare, ...envelope.data } as DomainEvent;",
      "        await dispatcher.dispatch(event);",
      "        baseLogger.info({",
      '          event: "channel_consumed",',
      "          address: b.address,",
      "          type: envelope.type,",
      "          id: envelope.id,",
      "        });",
      "      }),",
      "    );",
      "  }",
      "  return async () => {",
      "    for (const u of unsubs) u();",
      "    await Promise.allSettled([...new Set(transports.values())].map((t) => t.close()));",
      "  };",
      "}",
    ) + "\n"
  );
}
