// Generated `http/channels.ts` — the broker transport module (M-T4.4
// slices 2–3, design §4–5).  Emitted only when the deployable wires at
// least one broker-bound channelSource via `channels:`; channel-less
// projects stay byte-identical.
//
// The module carries the `ChannelTransport` seam (the contract the
// in-process dispatcher, every broker driver, and M-T1.10's realtime relay
// share), the CloudEvents 1.0 envelope, the redis (Valkey) driver over
// ioredis pub/sub (`broadcast`/`ephemeral`), the RabbitMQ driver over
// amqplib (`queue`/`ephemeral`+`work`: one durable queue per consuming
// deployable — replicas compete; manual ack → bounded retry → DLX
// `loom.dlx` → `loom.dlq.<address>` parking), the producer tee, and the
// consumer loop.
//
// Producer path split (design §5): the delivery-uniformity tee publishes
// EPHEMERAL broker-bound events inline; DURABLE (`work`) events pass
// through to the outbox dispatcher and are published by the relay on drain
// (the relay wraps its dispatcher in the same tee with `fromRelay: true`).
// The envelope `id` is the outbox row id when the event rides the relay,
// so consumer-side idempotency markers dedup broker redeliveries.

import { lines } from "../../../util/code-builder.js";
import type { BrokerBinding } from "../../_channels/bindings.js";

/** envVar → address per binding, deduped (two bindings on one deployable
 *  may share a channelSource only via duplicate list entries). */
function uniqueBindings(bindings: BrokerBinding[]): BrokerBinding[] {
  const seen = new Set<string>();
  return bindings.filter((b) => {
    if (seen.has(b.csName)) return false;
    seen.add(b.csName);
    return true;
  });
}

export function renderChannelsModule(bindings: BrokerBinding[]): string {
  const unique = uniqueBindings(bindings);
  const hasRedis = unique.some((b) => b.transport === "redis");
  const hasRabbit = unique.some((b) => b.transport === "rabbitmq");
  // event type -> address, split by durability: ephemeral events publish
  // inline in the tee; durable (`work`) events ride the outbox relay.
  // First-by-declaration within each tier, mirroring the in-process
  // dispatcher's routing rule.
  const ephemeralRouting = new Map<string, string>();
  const durableRouting = new Map<string, string>();
  for (const b of unique) {
    const target = b.retention === "ephemeral" ? ephemeralRouting : durableRouting;
    for (const ev of b.events) {
      if (!target.has(ev)) target.set(ev, b.address);
    }
  }
  return (
    lines(
      "// Auto-generated.",
      "// Broker transport for the deployable's wired channels (channels.md;",
      "// M-T4.4 design §4-5).  CloudEvents 1.0 envelopes between deployables;",
      "// the consumer loop feeds received events into the same in-process",
      "// dispatcher local reactors use.",
      hasRabbit ? 'import amqp from "amqplib";' : null,
      hasRedis ? 'import { Redis } from "ioredis";' : null,
      'import type { DomainEvent, DomainEventDispatcher } from "../domain/events";',
      'import { baseLogger } from "../obs/log";',
      "",
      "/** CloudEvents 1.0 JSON envelope — the cross-backend wire contract",
      " * (loom envelope pin, src/util/channels.ts).  `id` doubles as the",
      " * consumer-side idempotency key: relay-published (durable) events carry",
      " * their outbox row id, so saga markers dedup broker redeliveries. */",
      "export interface LoomEventEnvelope {",
      '  specversion: "1.0";',
      "  id: string;",
      "  type: string;",
      "  source: string;",
      "  time: string;",
      '  datacontenttype: "application/json";',
      "  loomchannel: string;",
      "  data: Record<string, unknown>;",
      "}",
      "",
      "/** The publish/subscribe seam every transport implements — in-process,",
      " * the broker drivers, and the realtime relay (M-T1.10) all sit on this",
      " * interface.  `group` is null for broadcast (every subscriber sees every",
      " * envelope); a group name makes replicas competing consumers. */",
      "export interface ChannelTransport {",
      "  publish(address: string, envelope: LoomEventEnvelope): Promise<void>;",
      "  subscribe(",
      "    address: string,",
      "    group: string | null,",
      "    handler: (envelope: LoomEventEnvelope) => Promise<void>,",
      "  ): () => void;",
      "  close(): Promise<void>;",
      "}",
      ...(hasRedis
        ? [
            "",
            "/** Redis (Valkey) driver — pub/sub over ioredis.  A dedicated",
            " * subscriber connection is required by the redis protocol (a",
            " * connection in subscribe mode can't publish). */",
            "export function createRedisTransport(url: string): ChannelTransport {",
            "  const pub = new Redis(url, { lazyConnect: false, maxRetriesPerRequest: 3 });",
            "  const sub = new Redis(url, { lazyConnect: false, maxRetriesPerRequest: 3 });",
            "  const handlers = new Map<string, Set<(e: LoomEventEnvelope) => Promise<void>>>();",
            '  sub.on("message", (address: string, message: string) => {',
            "    const set = handlers.get(address);",
            "    if (!set) return;",
            "    let envelope: LoomEventEnvelope;",
            "    try {",
            "      envelope = JSON.parse(message) as LoomEventEnvelope;",
            "    } catch {",
            '      baseLogger.warn({ event: "channel_consume_failed", address, error: "malformed envelope" });',
            "      return;",
            "    }",
            "    for (const h of set) {",
            "      void h(envelope).catch((err) => {",
            "        baseLogger.warn({",
            '          event: "channel_consume_failed",',
            "          address,",
            "          type: envelope.type,",
            "          error: err instanceof Error ? err.message : String(err),",
            "        });",
            "      });",
            "    }",
            "  });",
            "  return {",
            "    async publish(address, envelope) {",
            "      await pub.publish(address, JSON.stringify(envelope));",
            "    },",
            "    subscribe(address, _group, handler) {",
            "      let set = handlers.get(address);",
            "      if (!set) {",
            "        set = new Set();",
            "        handlers.set(address, set);",
            "        void sub.subscribe(address);",
            "      }",
            "      set.add(handler);",
            "      return () => {",
            "        set.delete(handler);",
            "        if (set.size === 0) {",
            "          handlers.delete(address);",
            "          void sub.unsubscribe(address);",
            "        }",
            "      };",
            "    },",
            "    async close() {",
            "      await Promise.allSettled([pub.quit(), sub.quit()]);",
            "    },",
            "  };",
            "}",
          ]
        : []),
      ...(hasRabbit
        ? [
            "",
            "/** Bounded per-message retries before a poisoned message parks in the",
            " * DLQ (mirrors the outbox relay's maxAttempts). */",
            "const CHANNEL_MAX_ATTEMPTS = 5;",
            "",
            "/** RabbitMQ driver — amqplib over AMQP 0-9-1 (design §4 topology):",
            " * a durable fanout exchange per channel address; one durable queue",
            " * per consuming deployable (the consumer group) so replicas compete;",
            " * manual ack; a failed handler re-queues with an attempt header up to",
            " * CHANNEL_MAX_ATTEMPTS, then parks via DLX `loom.dlx` into",
            " * `loom.dlq.<address>`. */",
            "export function createRabbitTransport(url: string): ChannelTransport {",
            "  let connPromise: Promise<amqp.ChannelModel> | null = null;",
            "  let chPromise: Promise<amqp.Channel> | null = null;",
            "  const channel = (): Promise<amqp.Channel> => {",
            "    connPromise ??= amqp.connect(url);",
            "    chPromise ??= connPromise.then((c) => c.createChannel());",
            "    return chPromise;",
            "  };",
            "  const consumerTags: string[] = [];",
            "  return {",
            "    async publish(address, envelope) {",
            "      const ch = await channel();",
            '      await ch.assertExchange(address, "fanout", { durable: true });',
            '      ch.publish(address, "", Buffer.from(JSON.stringify(envelope)), {',
            "        persistent: true,",
            '        contentType: "application/json",',
            "      });",
            "    },",
            "    subscribe(address, group, handler) {",
            "      // The queue name IS the consumer group: replicas of one",
            "      // deployable share it and compete; other deployables bind",
            "      // their own queue to the same exchange (fan-out across",
            "      // deployables, one-of-N within).",
            "      const queue = group ?? address;",
            "      let cancelled = false;",
            "      void (async () => {",
            "        const ch = await channel();",
            '        await ch.assertExchange(address, "fanout", { durable: true });',
            '        await ch.assertExchange("loom.dlx", "direct", { durable: true });',
            "        const dlq = `loom.dlq.${address}`;",
            "        await ch.assertQueue(dlq, { durable: true });",
            '        await ch.bindQueue(dlq, "loom.dlx", address);',
            "        await ch.assertQueue(queue, {",
            "          durable: true,",
            '          deadLetterExchange: "loom.dlx",',
            "          deadLetterRoutingKey: address,",
            "        });",
            '        await ch.bindQueue(queue, address, "");',
            "        await ch.prefetch(1);",
            "        const { consumerTag } = await ch.consume(queue, (msg) => {",
            "          if (!msg || cancelled) return;",
            "          void (async () => {",
            "            let envelope: LoomEventEnvelope;",
            "            try {",
            "              envelope = JSON.parse(msg.content.toString()) as LoomEventEnvelope;",
            "            } catch {",
            "              // Malformed body: no retry can fix it — park immediately.",
            "              ch.nack(msg, false, false);",
            '              baseLogger.warn({ event: "channel_dead_lettered", address, error: "malformed envelope" });',
            "              return;",
            "            }",
            "            try {",
            "              await handler(envelope);",
            "              ch.ack(msg);",
            "            } catch (err) {",
            '              const attempts = Number(msg.properties.headers?.["x-loom-attempts"] ?? 0) + 1;',
            "              const error = err instanceof Error ? err.message : String(err);",
            "              if (attempts >= CHANNEL_MAX_ATTEMPTS) {",
            "                // nack without requeue routes through the queue's DLX",
            "                // into loom.dlq.<address> — parked, not lost.",
            "                ch.nack(msg, false, false);",
            "                baseLogger.warn({",
            '                  event: "channel_dead_lettered",',
            "                  address,",
            "                  type: envelope.type,",
            "                  id: envelope.id,",
            "                  attempts,",
            "                  error,",
            "                });",
            "              } else {",
            "                // Bounded retry: republish with the attempt header and",
            "                // ack the original (immediate nack-requeue would hot-loop).",
            '                ch.publish("", queue, msg.content, {',
            "                  persistent: true,",
            '                  headers: { ...msg.properties.headers, "x-loom-attempts": attempts },',
            "                });",
            "                ch.ack(msg);",
            "              }",
            "            }",
            "          })();",
            "        });",
            "        consumerTags.push(consumerTag);",
            "      })();",
            "      return () => {",
            "        cancelled = true;",
            "      };",
            "    },",
            "    async close() {",
            "      try {",
            "        const ch = chPromise ? await chPromise : null;",
            "        for (const tag of consumerTags) await ch?.cancel(tag);",
            "        await ch?.close();",
            "        const conn = connPromise ? await connPromise : null;",
            "        await conn?.close();",
            "      } catch {",
            "        // Already closed / never connected — shutdown is best-effort.",
            "      }",
            "    },",
            "  };",
            "}",
          ]
        : []),
      "",
      "// The deployable's wired bindings: broker address + consumer group per",
      "// channelSource, with the connection URL injected by compose/k8s as",
      "// LOOM_CHANNEL_<NAME>_URL.",
      "export const CHANNEL_BINDINGS = [",
      ...unique.map(
        (b) =>
          `  { csName: ${JSON.stringify(b.csName)}, address: ${JSON.stringify(b.address)}, envVar: ${JSON.stringify(b.envVar)}, context: ${JSON.stringify(b.contextName)}, transport: ${JSON.stringify(b.transport)}, group: ${JSON.stringify(b.group)}, queue: ${b.delivery === "queue"} },`,
      ),
      "] as const;",
      "",
      "// event type -> broker address.  Ephemeral events publish inline in the",
      "// tee; durable (`work`) events pass through to the outbox and publish on",
      "// relay drain (design §5).",
      "export const CHANNEL_ROUTING: Record<string, string> = {",
      ...[...ephemeralRouting.entries()].map(([ev, addr]) => `  ${ev}: ${JSON.stringify(addr)},`),
      "};",
      "",
      "export const DURABLE_CHANNEL_ROUTING: Record<string, string> = {",
      ...[...durableRouting.entries()].map(([ev, addr]) => `  ${ev}: ${JSON.stringify(addr)},`),
      "};",
      "",
      "let counter = 0;",
      "function envelopeFor(event: DomainEvent, address: string): LoomEventEnvelope {",
      "  const { type, __loomEventId, ...data } = event as unknown as {",
      "    type: string;",
      "    __loomEventId?: string;",
      "  } & Record<string, unknown>;",
      '  const context = CHANNEL_BINDINGS.find((b) => b.address === address)?.context ?? "";',
      "  counter += 1;",
      "  return {",
      '    specversion: "1.0",',
      "    // Relay-published events reuse their outbox row id — the stable",
      "    // consumer-side idempotency key across broker redeliveries.",
      "    id: __loomEventId ?? `${Date.now().toString(36)}-${process.pid.toString(36)}-${counter.toString(36)}`,",
      "    type: `${context}.${type}`,",
      "    source: `/loom/${context}`,",
      "    time: new Date().toISOString(),",
      '    datacontenttype: "application/json",',
      "    loomchannel: address,",
      "    data,",
      "  };",
      "}",
      "",
      "/** One shared transport per broker URL for the process (publisher tee +",
      " * consumer loop reuse the same connections). */",
      "export function createChannelTransports(): Map<string, ChannelTransport> {",
      "  const byUrl = new Map<string, ChannelTransport>();",
      "  const byEnv = new Map<string, ChannelTransport>();",
      "  for (const b of CHANNEL_BINDINGS) {",
      "    const url = process.env[b.envVar];",
      "    if (!url) {",
      "      throw new Error(",
      "        `channel binding '${b.csName}' needs ${b.envVar} (the broker URL compose/k8s injects)`,",
      "      );",
      "    }",
      "    let t = byUrl.get(url);",
      "    if (!t) {",
      hasRedis && hasRabbit
        ? '      t = b.transport === "rabbitmq" ? createRabbitTransport(url) : createRedisTransport(url);'
        : hasRabbit
          ? "      t = createRabbitTransport(url);"
          : "      t = createRedisTransport(url);",
      "      byUrl.set(url, t);",
      "    }",
      "    byEnv.set(b.csName, t);",
      "  }",
      "  return byEnv;",
      "}",
      "",
      "/** Close every distinct transport (producer-only shutdown; the consumer",
      " * loop's stop function closes them itself). */",
      "export async function closeChannelTransports(",
      "  transports: Map<string, ChannelTransport>,",
      "): Promise<void> {",
      "  await Promise.allSettled([...new Set(transports.values())].map((t) => t.close()));",
      "}",
      "",
      "function transportForAddress(",
      "  transports: Map<string, ChannelTransport>,",
      "  address: string,",
      "): ChannelTransport {",
      "  const binding = CHANNEL_BINDINGS.find((b) => b.address === address);",
      "  const t = binding ? transports.get(binding.csName) : undefined;",
      "  if (!t) throw new Error(`no transport wired for channel address ${address}`);",
      "  return t;",
      "}",
      "",
      "/** Producer tee — the delivery-uniformity rule (design §4): an event",
      " * carried by a broker-bound channel is PUBLISHED and not fanned out",
      " * locally; co-located consumers receive it through their subscription",
      " * exactly like remote ones.",
      " *",
      " * Two modes (design §5): on the request path (default) ephemeral events",
      " * publish inline while durable events pass to `inner` (the outbox",
      " * dispatcher captures them in the write tx); in relay mode the drained",
      " * durable rows publish here instead of re-entering the local chain. */",
      "export function channelPublishTee(",
      "  transports: Map<string, ChannelTransport>,",
      "  inner: DomainEventDispatcher,",
      "  opts: { fromRelay?: boolean } = {},",
      "): DomainEventDispatcher {",
      "  return {",
      "    async dispatch(event: DomainEvent): Promise<void> {",
      "      const durableAddress = DURABLE_CHANNEL_ROUTING[event.type];",
      "      if (durableAddress) {",
      "        if (!opts.fromRelay) return inner.dispatch(event); // outbox captures; relay publishes",
      "        const envelope = envelopeFor(event, durableAddress);",
      "        await transportForAddress(transports, durableAddress).publish(durableAddress, envelope);",
      '        baseLogger.info({ event: "channel_published", address: durableAddress, type: event.type, id: envelope.id });',
      "        return;",
      "      }",
      "      const address = CHANNEL_ROUTING[event.type];",
      "      if (!address) return inner.dispatch(event);",
      "      const envelope = envelopeFor(event, address);",
      "      await transportForAddress(transports, address).publish(address, envelope);",
      '      baseLogger.info({ event: "channel_published", address, type: event.type, id: envelope.id });',
      "    },",
      "  };",
      "}",
      "",
      "/** Consumer loop — subscribes every wired address (competing-consumer",
      " * group on `queue` channels, broadcast otherwise) and dispatches received",
      " * envelopes into the given (in-process) dispatcher, so reactors and",
      " * event-triggered creates run identically for local and remote events.",
      " * The envelope id rides along as the idempotency marker. */",
      "export function startChannelConsumers(",
      "  transports: Map<string, ChannelTransport>,",
      "  dispatcher: DomainEventDispatcher,",
      "): () => Promise<void> {",
      "  const unsubs: Array<() => void> = [];",
      "  for (const b of CHANNEL_BINDINGS) {",
      "    const t = transports.get(b.csName);",
      "    if (!t) continue;",
      "    unsubs.push(",
      "      t.subscribe(b.address, b.queue ? b.group : null, async (envelope) => {",
      '        const bare = envelope.type.includes(".") ? envelope.type.slice(envelope.type.indexOf(".") + 1) : envelope.type;',
      "        const event = {",
      "          type: bare,",
      "          ...envelope.data,",
      "          __loomEventId: envelope.id,",
      "        } as unknown as DomainEvent;",
      "        await dispatcher.dispatch(event);",
      "        baseLogger.info({",
      '          event: "channel_consumed",',
      "          address: b.address,",
      "          type: envelope.type,",
      "          id: envelope.id,",
      "        });",
      "      }),",
      "    );",
      "  }",
      "  return async () => {",
      "    for (const u of unsubs) u();",
      "    await Promise.allSettled([...new Set(transports.values())].map((t) => t.close()));",
      "  };",
      "}",
    ) + "\n"
  );
}
